import { seedPurpose } from './purpose-seed';
import { seedCollections } from './collections-seed';
import { DEMO_COVER_LIBRARY_FILE, DEMO_WORKSHEET_FILE, demoWorksheetPdf } from './demo-files';
import { normaliseQuiz } from './assessments';
import type { Workspace, Member, Space, Track, Lesson, Mission, Project, CommunityEvent, Upload, QuizAttempt, TrackInstructor, CoverLibraryItem } from '../../contracts/src/index';
export const DEMO_USER = 'member_alex';
export const DEMO_ADMIN = 'member_amina';
/** Fictional instructor of the product track, for previewing the teaching view. */
export const DEMO_INSTRUCTOR = 'member_idris';
export function createSeed(slug = 'code-black'): Workspace {
    const org = slug === 'code-black' ? 'org_code_black' : 'org_studio_north';
    const isCode = slug === 'code-black';
    const base = (id: string, createdAt = '2026-09-24T08:00:00.000Z') => ({ id, organizationId: org, createdAt });
    const people = [
        ['member_alex', 'Alex Morgan', 'Creative technologist', 'violet', 'member', 'Building useful things at the intersection of storytelling and technology.', ['Creative coding', 'Product design']],
        ['member_amina', 'Amina Okafor', 'Community lead · Code Black', 'mint', 'owner', 'Making space for ambitious people to learn, connect and ship meaningful work.', ['Community', 'Strategy']],
        ['member_jordan', 'Jordan Ellis', 'Brand designer & art director', 'amber', 'member', 'Turning a good idea into a brand people can feel.', ['Brand design', 'Art direction']],
        ['member_maya', 'Maya Bennett', 'Filmmaker & visual storyteller', 'rose', 'moderator', 'Stories first. Tools second. Currently experimenting with 30-second films.', ['Filmmaking', 'Editing']],
        ['member_idris', 'Idris Cole', 'Full-stack developer', 'blue', 'member', 'From a blank canvas to a useful first release. Looking for good collaborators.', ['React', 'TypeScript']],
        ['member_sofia', 'Sofia Chen', 'Creative strategist', 'peach', 'member', 'Helping creative people find the thing only they can say.', ['Strategy', 'Writing']],
        ['member_theo', 'Theo Williams', 'Motion & sound designer', 'lime', 'member', 'Exploring how things move, sound and make us feel.', ['Motion', 'Sound design']],
        ['member_nia', 'Nia James', 'Founder & photographer', 'sky', 'member', 'Building a small, independent creative business, one experiment at a time.', ['Photography', 'Business']],
    ];
    const members: Member[] = people.map(([id, name, headline, colour, role, bio, skills]) => ({ ...base(String(id)), userId: String(id), name: String(name), headline: String(headline), colour: String(colour), role: role as Member['role'], bio: String(bio), skills: skills as string[], avatar: '', status: 'active' }));
    const spaces: Space[] = [
        ['space_general', 'The commons', 'general', 'A good place to start. Introductions, ideas and conversations.', 'violet', 'discussion', 'members'],
        ['space_build', 'Build in public', 'build', 'Work in progress, honest feedback and small wins.', 'mint', 'project', 'members'],
        ['space_learn', 'Learning lab', 'learn', 'Share what you know. Find what you need next.', 'blue', 'learning', 'members'],
        ['space_feedback', 'Feedback room', 'feedback', 'Better work starts with a second pair of eyes.', 'amber', 'discussion', 'members'],
        ['space_wins', 'Small wins', 'wins', 'The progress worth celebrating. Big or small.', 'rose', 'discussion', 'members'],
        ['space_studio', 'The studio', 'studio', 'Private space for the community team.', 'peach', 'discussion', 'private'],
    ].map(([id, name, slug, description, colour, kind, visibility]) => ({ ...base(id), name, slug, description, colour, kind: kind as Space['kind'], visibility: visibility as Space['visibility'] }));
    const tracks: Track[] = [
        ['track_story', 'Stories that make people feel', 'Turn a simple idea into a story people remember.', 'Find an emotional point of view, shape a simple narrative and make a short film with intent.', 'Storytelling', 'All levels', 'amber', 'story', 'member_maya'],
        ['track_product', 'From idea to first version', 'Stop circling the idea. Put something useful into the world.', 'Learn to choose a clear problem, cut the unnecessary features and get a usable first version in front of real people.', 'Product building', 'Beginner', 'violet', 'product', 'member_idris'],
        ['track_brand', 'Build a brand with a point of view', 'Find your voice. Make every touchpoint mean something.', 'Define a distinct promise, make a coherent visual language and test whether your audience understands it.', 'Brand & design', 'All levels', 'mint', 'brand', 'member_jordan'],
        ['track_business', 'Make your first offer', 'Turn what you know into something somebody values.', 'Choose a customer, understand the real problem and create a clear, honest offer.', 'Creative business', 'Beginner', 'blue', 'business', 'member_nia'],
    ].map(([id, title, summary, description, category, level, colour, cover, authorId]) => ({ ...base(id), spaceId: 'space_learn', title, summary, description, category, level, colour, cover, authorId, published: true }));
    const lessonDefs: [
        string,
        string,
        string,
        string,
        number
    ][] = [
        ['track_story', 'Start with a feeling', 'Before a camera, choose an emotion.', 'A story is not a list of things that happen. It is a change that matters to somebody.\n\nChoose one person. What do they want? What is getting in the way? How should the audience feel at the end?\n\nTry this\nWrite one sentence: “This is a story about someone who wants ___, but ___.” Then name the feeling you want to leave behind.\n\nKeep the idea small enough to make. Your first proof is clarity, not production value.', 8],
        ['track_story', 'Find the turning point', 'Give the audience a reason to care.', 'An effective short story has a before and an after. Between them is a choice, discovery or obstacle that changes something.\n\nSketch three moments: the ordinary situation, the turning point and the consequence.\n\nExercise\nDescribe each moment in one visual sentence. Remove anything that does not help the audience feel the change.', 12],
        ['track_story', 'Make the 30-second version', 'Create a small piece of finished work.', 'Work with what is already available: a phone, one location and one willing collaborator.\n\nShoot three to five shots. Make one clear choice about sound. Edit for the feeling, not just the beat.\n\nShare your proof\nUpload your film to a service you trust and submit its HTTPS link to the story mission. Include what you tried and what you would improve.', 15],
        ['track_product', 'Choose one real problem', 'A product begins with a person, not a feature list.', 'Name one person you can talk to. Describe something they are already trying to do and what makes it frustrating.\n\nDo not ask whether they like your idea. Ask about the last time the problem happened.\n\nYour task\nWrite the problem in plain English. Describe how they currently solve it. Keep your assumptions separate from what they told you.', 10],
        ['track_product', 'Cut it down to the useful part', 'A first version should do one thing well.', 'Draw the shortest path from the person’s problem to a useful outcome.\n\nSeparate essentials from things that are impressive but unnecessary. Build one complete path rather than five half-finished features.\n\nShare a clickable prototype or a short walkthrough. Tell reviewers exactly what you need feedback on.', 14],
        ['track_product', 'Test before you celebrate', 'Real feedback is more useful than a launch graphic.', 'Put the first version in front of someone with the problem. Watch quietly as they try it.\n\nNote where they pause, what they expect and whether they reach the outcome.\n\nChoose one improvement based on observation. Keep a record of the change and the reason you made it.', 12],
        ['track_brand', 'Say something specific', 'A clear position gives design something to work with.', 'Complete these sentences: We help ___. We believe ___. We do it differently by ___.\n\nReplace abstract claims with things a customer can notice. “Creative solutions” is not a position.\n\nMake a one-page brand note with your promise, personality and a few examples of language you would and would not use.', 9],
        ['track_brand', 'Make it recognisable', 'Consistency can be expressive.', 'Choose a type hierarchy, a colour relationship and one visual behaviour that belongs to the brand.\n\nApply them to three different touchpoints. If they only work in a logo presentation, keep going.\n\nSubmit your three examples and explain the thinking behind the choices.', 16],
        ['track_business', 'Make the value obvious', 'An offer is a promise with clear boundaries.', 'Describe who the offer is for, the outcome, what is included and what is not.\n\nBe specific about the work you can actually deliver. Avoid promises that depend on results outside your control.\n\nShow the offer to one potential customer and ask which parts are unclear.', 11],
        ['track_business', 'Start a useful conversation', 'Outreach is about relevance, not volume.', 'Find a real reason the person might need your help. Reference something specific about their work.\n\nExplain the useful outcome in one sentence and propose a small next step.\n\nKeep a record of what you sent, what happened and what you learned. Respect a no.', 10],
    ];
    const counts: Record<string, number> = {};
    const lessons: Lesson[] = lessonDefs.map(([trackId, title, summary, body, minutes], i) => ({ ...base('lesson_' + (i + 1)), trackId, title, summary, body, minutes, position: (counts[trackId] = (counts[trackId] || 0) + 1), resourceUrl: '', published: true }));
    // One fictional lesson file. Its bytes are generated in the browser demo; no stored object exists elsewhere.
    const worksheetBytes = demoWorksheetPdf().length;
    const uploads: Upload[] = isCode ? [{ ...base(DEMO_WORKSHEET_FILE), userId: DEMO_ADMIN, purpose: 'lesson_resource', trackId: 'track_product', originalName: 'problem-interview-worksheet.pdf', contentType: 'application/pdf', sizeBytes: worksheetBytes, status: 'ready', objectKey: `fixtures/${org}/problem-interview-worksheet.pdf`, completedAt: '2026-09-24T08:00:00.000Z', generation: '1' },
        { ...base(DEMO_COVER_LIBRARY_FILE), userId: DEMO_ADMIN, purpose: 'cover_library', trackId: null, coverTrackId: null, coverProjectId: null, originalName: 'cover library picture', contentType: 'image/jpeg', sizeBytes: 14450, status: 'ready', objectKey: `fixtures/${org}/covers/library/mountain.jpg`, completedAt: '2026-09-24T08:00:00.000Z', generation: '1' }] : [];
    if (isCode) lessons.find(l => l.id === 'lesson_4')!.resources = [{ id: 'resource_problem_worksheet', fileId: DEMO_WORKSHEET_FILE, name: 'Problem interview worksheet', description: 'Five questions that keep what you heard separate from what you assume.', contentType: 'application/pdf', sizeBytes: worksheetBytes }];
    // Two fictional knowledge checks: one scored automatically, one with a written answer that a reviewer marks.
    if (isCode) {
        lessons.find(l => l.id === 'lesson_5')!.quiz = { questions: [
            { id: 'q5_feedback', kind: 'single', prompt: 'When you share a clickable prototype, what should you tell reviewers?', points: 1, options: [{ id: 'a', text: 'Exactly what you need feedback on', correct: true }, { id: 'b', text: 'How many features are planned', correct: false }, { id: 'c', text: 'Nothing, so their reaction stays unbiased', correct: false }], acceptedAnswers: [], explanation: 'Reviewers help most when they know the question you are trying to answer.' },
            { id: 'q5_essentials', kind: 'multiple', prompt: 'Which belong in a first version?', points: 2, options: [{ id: 'a', text: 'One complete path to a useful outcome', correct: true }, { id: 'b', text: 'The essentials for the person’s problem', correct: true }, { id: 'c', text: 'Five half-finished features', correct: false }, { id: 'd', text: 'Things that are impressive but unnecessary', correct: false }], acceptedAnswers: [], explanation: 'A first version does one thing well, from the problem to a useful outcome.' },
            { id: 'q5_outcome', kind: 'short', prompt: 'Complete the lesson’s instruction: draw the shortest path from the person’s problem to a ___ outcome.', points: 1, options: [], acceptedAnswers: ['useful'], explanation: 'The path ends in a useful outcome for one real person.' },
        ], passPercentage: 75, maxAttempts: 3, revealAnswers: true };
        lessons.find(l => l.id === 'lesson_6')!.quiz = { questions: [
            { id: 'q6_watch', kind: 'single', prompt: 'What should you do while someone tries your first version?', points: 1, options: [{ id: 'a', text: 'Watch quietly and note where they pause', correct: true }, { id: 'b', text: 'Explain each feature as they go', correct: false }, { id: 'c', text: 'Ask whether they like it', correct: false }], acceptedAnswers: [], explanation: 'Quiet observation shows what people expect without your help.' },
            { id: 'q6_change', kind: 'written', prompt: 'Describe one improvement you would choose after watching someone try your first version, and the reason for it.', points: 3, options: [], acceptedAnswers: [], explanation: '' },
        ], passPercentage: null, maxAttempts: null, revealAnswers: false };
    }
    const missions: Mission[] = [
        { ...base('mission_film'), spaceId: 'space_feedback', trackId: 'track_story', title: 'Make someone feel something in 30 seconds.', brief: 'Create a 30-second film built around one emotion. A phone is enough. Tell us who it is for, the feeling you chose and the choice that made the biggest difference.', criteria: ['A finished film of 30 seconds or less', 'A clear emotional intention', 'A short reflection on one creative choice'], category: 'Storytelling', points: 120, dueAt: '2026-10-02T18:00:00.000Z', difficulty: 'Open to everyone' },
        { ...base('mission_prototype'), spaceId: 'space_build', trackId: 'track_product', title: 'Put your first version in somebody’s hands.', brief: 'Build the smallest useful version of an idea. Let one person with the problem try it, then show us what changed because of their feedback.', criteria: ['A working prototype or walkthrough', 'Feedback from one real person', 'One documented improvement'], category: 'Product building', points: 180, dueAt: '2026-10-09T18:00:00.000Z', difficulty: 'Stretch yourself' },
        { ...base('mission_brand'), spaceId: 'space_feedback', trackId: 'track_brand', title: 'Give an idea a point of view.', brief: 'Create a miniature brand for something you believe should exist. Make three touchpoints feel like they belong to the same idea.', criteria: ['One clear brand promise', 'Three connected visual touchpoints', 'An explanation of your decisions'], category: 'Brand & design', points: 100, dueAt: '2026-10-06T18:00:00.000Z', difficulty: 'Open to everyone' },
        { ...base('mission_offer'), spaceId: 'space_wins', trackId: 'track_business', title: 'Make a real offer. Start one conversation.', brief: 'Turn a useful skill into a clear offer. Share it respectfully with one relevant person and reflect on what you learned.', criteria: ['A specific audience and outcome', 'One honest, bounded offer', 'A reflection without private customer details'], category: 'Creative business', points: 100, dueAt: '2026-10-12T18:00:00.000Z', difficulty: 'Take the first step' },
    ];
    const projects: Omit<Project, 'purposeId'>[] = [
        { ...base('project_afterhours'), spaceId: 'space_build', title: 'After Hours', tagline: 'A short film about the people who keep a city awake.', summary: 'An independently made short documentary about night workers and the lives we rarely notice. We are developing the visual treatment and looking for a sound collaborator.', category: 'Film', skills: ['Filmmaking', 'Sound design'], ownerId: 'member_maya', status: 'building', cover: 'afterhours' },
        { ...base('project_common'), spaceId: 'space_build', title: 'Common Ground', tagline: 'A better way for independent creatives to find each other.', summary: 'A small directory that puts collaboration before follower counts. The first prototype helps you find a person by what they make and what they need.', category: 'Product', skills: ['React', 'Product design'], ownerId: 'member_idris', status: 'building', cover: 'common' },
        { ...base('project_still'), spaceId: null, title: 'Still / Moving', tagline: 'An experimental identity for a more thoughtful creative studio.', summary: 'A brand study exploring the space between stillness and movement. We are collecting references and testing a small visual system.', category: 'Design', skills: ['Brand design', 'Motion'], ownerId: 'member_jordan', status: 'idea', cover: 'still' },
        { ...base('project_notes'), spaceId: null, title: 'Notes from the process', tagline: 'Small lessons from people making things.', summary: 'An independent digital zine about unfinished work, useful mistakes and the part behind the final image. Issue one is ready to share.', category: 'Editorial', skills: ['Writing', 'Photography'], ownerId: 'member_sofia', status: 'launched', cover: 'notes' },
    ];
    const events: CommunityEvent[] = [
        { ...base('event_open'), spaceId: null, title: 'The open studio', summary: 'Bring what you are working on. Leave with a fresh perspective. An informal feedback session for works in progress.', startsAt: '2026-09-25T18:00:00.000Z', duration: 60, hostId: 'member_amina', format: 'critique', location: 'Online · meeting link to follow', meetingUrl: '' },
        { ...base('event_story'), spaceId: 'space_learn', title: 'From a good idea to a story that stays', summary: 'Maya walks through a short-film treatment, from the first feeling to the final cut. Bring one idea you have not made yet.', startsAt: '2026-09-29T17:30:00.000Z', duration: 75, hostId: 'member_maya', format: 'workshop', location: 'Online · meeting link to follow', meetingUrl: '' },
        { ...base('event_focus'), spaceId: 'space_build', title: 'Build together: a focused hour', summary: 'Choose one small thing to finish. We will share our intentions, work quietly and compare notes at the end.', startsAt: '2026-10-01T11:00:00.000Z', duration: 60, hostId: 'member_idris', format: 'coworking', location: 'Online · meeting link to follow', meetingUrl: '' },
    ];
    const posts: Workspace['posts'] = [
        { ...base('post_welcome', '2026-09-24T08:50:00.000Z'), spaceId: 'space_general', authorId: 'member_amina', kind: 'update', title: 'Good people. Better things.', body: 'Welcome to Code Black. This is a place to ask the unfinished question, share the work before it is perfect, and find people to make it better with.\n\nStart small: tell us what you are making, and one thing you could use a hand with.', pinned: true, hidden: false, cover: '' },
        { ...base('post_common', '2026-09-24T08:40:00.000Z'), spaceId: 'space_build', authorId: 'member_idris', kind: 'project', title: 'The first version is never the final story.', body: 'Common Ground is taking shape. A small way for independent creatives to find collaborators by what they make, not how many followers they have.\n\nI would love a second pair of eyes on the onboarding. What would you need to know before reaching out to someone?', pinned: false, hidden: false, cover: 'common' },
        { ...base('post_maya', '2026-09-24T08:15:00.000Z'), spaceId: 'space_feedback', authorId: 'member_maya', kind: 'question', title: 'What is a film that made you feel something with almost no dialogue?', body: 'Working on a 30-second piece for this week’s mission. Looking for references where the emotion lives in the image and sound. Curious what stayed with you.', pinned: false, hidden: false, cover: '' },
        { ...base('post_win', '2026-09-23T17:00:00.000Z'), spaceId: 'space_wins', authorId: 'member_nia', kind: 'update', title: 'A small win worth sharing.', body: 'Sent the first version of my photography offer to somebody outside my usual circle. Not a sale yet, but a useful conversation and much clearer language. Progress is progress.', pinned: false, hidden: false, cover: '' },
        { ...base('post_resource', '2026-09-23T14:00:00.000Z'), spaceId: 'space_learn', authorId: 'member_sofia', kind: 'resource', title: 'A question I keep coming back to.', body: '“What is the smallest useful version of this?”\n\nIt helped me cut a 12-page project proposal down to one honest page. Sharing in case somebody else needs permission to make it simpler today.', pinned: false, hidden: false, cover: '' },
        { ...base('post_private', '2026-09-24T07:00:00.000Z'), spaceId: 'space_studio', authorId: 'member_amina', kind: 'update', title: 'Team notes for the open studio', body: 'Private team-only planning note. Confirm the session structure before publishing the next event.', pinned: false, hidden: false, cover: '' },
    ];
    // A fictional attempt waiting for feedback, so the review queue has something real to show.
    const lesson6 = lessons.find(l => l.id === 'lesson_6')!;
    const quizAttempts: QuizAttempt[] = isCode ? [{ ...base('attempt_sofia', '2026-09-25T10:30:00.000Z'), lessonId: 'lesson_6', trackId: 'track_product', userId: 'member_sofia', attemptNumber: 1, quiz: normaliseQuiz(lesson6.quiz)!, answers: [{ questionId: 'q6_watch', optionIds: ['a'], text: '' }, { questionId: 'q6_change', optionIds: [], text: 'They looked for a way to save before finishing the form, so I would save progress automatically and say so on screen. Three of the five steps were lost when they navigated away.' }], results: [{ questionId: 'q6_watch', correct: true, points: 1, maxPoints: 1 }, { questionId: 'q6_change', correct: null, points: null, maxPoints: 3 }], score: 1, maxScore: 4, status: 'awaiting_review', passed: null, feedback: '', reviewerId: null, reviewedAt: null, version: 1 }] : [];
    // Idris teaches the product track in the demo, so the instructor view can be previewed. Being named author grants nothing.
    const trackInstructors: TrackInstructor[] = isCode ? [{ ...base('instructor_idris_product', '2026-09-20T09:00:00.000Z'), trackId: 'track_product', userId: 'member_idris', grantedBy: DEMO_ADMIN, role: 'instructor' }] : [];
    // One fictional library picture, so the demo shows choosing a cover as well as uploading one.
    const coverLibrary: CoverLibraryItem[] = isCode ? [{ ...base('library_mountain', '2026-09-24T08:00:00.000Z'), fileId: DEMO_COVER_LIBRARY_FILE, label: 'Mountain ridge', contentType: 'image/jpeg', sizeBytes: 14450, addedBy: DEMO_ADMIN }] : [];
    return seedCollections(seedPurpose({ collections: [], collectionItems: [], notificationPreferences: [], coverLibrary, trackInstructors, quizAttempts, uploads, lessonDrafts: [], lessonRevisions: [], projectTasks: [], taskNotes: [], purposes: [], paths: [], milestones: [], pathEnrolments: [], contributions: [], outcomes: [], communityOutputs: [], memberGoals: [], organisation: { id: org, slug, name: isCode ? 'Code Black' : 'Studio North', tagline: isCode ? 'Good people. Remarkable things.' : 'A small space for thoughtful work.', accent: isCode ? 'violet' : 'mint', createdAt: '2026-09-01T09:00:00.000Z' }, revision: 0, members, spaces, spaceMembers: [{ ...base('sm_admin'), spaceId: 'space_studio', userId: DEMO_ADMIN }], posts, comments: [
            { ...base('comment_1'), postId: 'post_common', authorId: 'member_jordan', body: 'Love the intention. I would want to see one piece of their work and what sort of collaboration they are open to.' },
            { ...base('comment_2'), postId: 'post_common', authorId: 'member_alex', body: 'Happy to take a look at the first-run experience. The problem is very familiar.' },
            { ...base('comment_3'), postId: 'post_maya', authorId: 'member_theo', body: 'Try building the sound first, then choosing the images. It can completely change the rhythm.' },
        ], reactions: [['post_common', 'member_jordan'], ['post_common', 'member_amina'], ['post_maya', 'member_theo'], ['post_welcome', 'member_maya'], ['post_win', 'member_alex']].map(([postId, userId], i) => ({ ...base('reaction_' + i), postId, userId })), bookmarks: [], tracks, lessons, enrolments: [{ ...base('enrol_alex'), trackId: 'track_product', userId: DEMO_USER }, ...(isCode ? [{ ...base('enrol_sofia'), trackId: 'track_product', userId: 'member_sofia' }] : [])], completions: [{ ...base('completion_alex'), trackId: 'track_product', lessonId: 'lesson_4', userId: DEMO_USER }], missions, submissions: [{ ...base('submission_jordan'), missionId: 'mission_brand', authorId: 'member_jordan', body: 'A first identity study for Still / Moving: one clear promise, a restrained type system and three connected applications. The strongest learning was that motion should express the idea, not decorate it.', url: '', status: 'pending', feedback: '', reviewerId: null, updatedAt: '2026-09-24T08:00:00.000Z' }], projects: projects.map(p => ({ ...p, purposeId: null })), projectMembers: [['project_afterhours', 'member_maya'], ['project_afterhours', 'member_theo'], ['project_common', 'member_idris'], ['project_common', 'member_alex'], ['project_still', 'member_jordan'], ['project_notes', 'member_sofia'], ['project_notes', 'member_nia']].map(([projectId, userId], i) => ({ ...base('pm_' + i), projectId, userId })), projectUpdates: [{ ...base('update_common'), projectId: 'project_common', authorId: 'member_idris', body: 'The first clickable onboarding is ready for a review. Next step: test with one person who has not seen the idea before.' }], events, rsvps: [['event_open', 'member_maya'], ['event_open', 'member_jordan'], ['event_open', 'member_theo'], ['event_story', 'member_nia']].map(([eventId, userId], i) => ({ ...base('rsvp_' + i), eventId, userId })), notifications: [{ ...base('notification_1'), userId: DEMO_USER, title: 'A useful next step', body: 'Continue From idea to first version. Your next lesson is ready.', href: '/learn/track_product', readAt: null }, { ...base('notification_2'), userId: DEMO_USER, title: 'The studio is open', body: 'Bring your work in progress to the next community critique.', href: '/events/event_open', readAt: null }], reports: [], reputation: [{ ...base('rep_seed'), userId: DEMO_USER, dimension: 'learning', points: 20, sourceId: 'lesson:lesson_4:member_alex', description: 'Completed Choose one real problem' }], audit: [], outbox: [] }), isCode);
}
