import test from 'node:test';
import assert from 'node:assert/strict';
import { applyCommand, visibleWorkspace, progress, reputationTotals } from '../packages/domain/src/engine';
import { createSeed, DEMO_USER, DEMO_ADMIN } from '../packages/domain/src/seed';
import { commandSchema, safeUrl, type Workspace, type TenantContext } from '../packages/contracts/src/index';
const ctx = (userId = DEMO_USER, organizationId = 'org_code_black'): TenantContext => ({ userId, organizationId, requestId: 'test_request' });
const run = (command: unknown, s = createSeed(), c = ctx()) => applyCommand(s, c, command, () => '2026-09-24T09:00:00.000Z');
test('source workspace is not mutated', () => { const s = createSeed(); const before = JSON.stringify(s); run({ type: 'post.create', spaceId: 'space_general', kind: 'update', body: 'Hello team' }, s); assert.equal(JSON.stringify(s), before); });
for (const [name, c] of [['foreign tenant', ctx(DEMO_USER, 'org_foreign')], ['unknown member', ctx('outsider')]] as const)
    test(`rejects ${name}`, () => assert.throws(() => run({ type: 'track.enrol', trackId: 'track_product' }, createSeed(), c)));
test('suspended memberships denied', () => { const s = createSeed(); s.members[0].status = 'suspended'; assert.throws(() => visibleWorkspace(s, ctx())); });
test('member snapshot excludes private spaces and posts', () => { const s = visibleWorkspace(createSeed(), ctx()); assert(!s.spaces.some(x => x.id === 'space_studio')); assert(!s.posts.some(x => x.id === 'post_private')); });
test('private comments and reactions cannot leak', () => { const s = createSeed(); s.comments.push({ ...s.comments[0], id: 'private_comment', postId: 'post_private' }); s.reactions.push({ ...s.reactions[0], id: 'private_reaction', postId: 'post_private' }); const v = visibleWorkspace(s, ctx()); assert(!v.comments.some(x => x.id === 'private_comment')); assert(!v.reactions.some(x => x.id === 'private_reaction')); });
test('owner can access the team space', () => assert(visibleWorkspace(createSeed(), ctx(DEMO_ADMIN)).posts.some(x => x.id === 'post_private')));
for (const type of ['post.react', 'post.bookmark', 'post.comment', 'post.report'])
    test(`${type} denies inaccessible post`, () => assert.throws(() => run({ type, postId: 'post_private', ...(type === 'post.comment' ? { body: 'try' } : {}), ...(type === 'post.report' ? { reason: 'test' } : {}) })));
test('cannot post to a private space', () => assert.throws(() => run({ type: 'post.create', spaceId: 'space_studio', kind: 'update', body: 'No' })));
test('post uses verified actor and tenant', () => { const r = run({ type: 'post.create', spaceId: 'space_general', kind: 'question', body: 'A real question' }); assert.equal(r.workspace.posts[0].authorId, DEMO_USER); assert.equal(r.workspace.posts[0].organizationId, 'org_code_black'); });
for (const field of ['authorId', 'organizationId', 'role', 'points'])
    test(`forged ${field} is rejected`, () => assert.throws(() => run({ type: 'post.create', spaceId: 'space_general', kind: 'update', body: 'Hello', [field]: 'bad' })));
for (const body of ['', '  ', 'x'.repeat(10001)])
    test(`invalid post text (${body.length}) rejected`, () => assert.throws(() => run({ type: 'post.create', spaceId: 'space_general', kind: 'update', body })));
test('comment creates notification for its author', () => { const r = run({ type: 'post.comment', postId: 'post_common', body: 'Helpful feedback' }); assert(r.workspace.notifications.some(n => n.userId === 'member_idris')); });
test('reactions toggle without duplicates', () => { let s = createSeed(); s = run({ type: 'post.react', postId: 'post_common' }, s).workspace; assert.equal(s.reactions.filter(r => r.postId === 'post_common' && r.userId === DEMO_USER).length, 1); s = run({ type: 'post.react', postId: 'post_common' }, s).workspace; assert.equal(s.reactions.filter(r => r.postId === 'post_common' && r.userId === DEMO_USER).length, 0); });
test('bookmarks are private and toggle', () => { const r = run({ type: 'post.bookmark', postId: 'post_common' }); assert.equal(visibleWorkspace(r.workspace, ctx(DEMO_ADMIN)).bookmarks.length, 0); assert.equal(run({ type: 'post.bookmark', postId: 'post_common' }, r.workspace).workspace.bookmarks.length, 0); });
test('reports deduplicate', () => { const c = { type: 'post.report', postId: 'post_common', reason: 'Needs a review' }; const r = run(c); assert.equal(run(c, r.workspace).workspace.reports.length, 1); });
test('ordinary members cannot moderate', () => assert.throws(() => run({ type: 'post.moderate', postId: 'post_common', hidden: true })));
test('moderation hides content and adds audit', () => { const s = run({ type: 'post.moderate', postId: 'post_common', hidden: true }, createSeed(), ctx('member_maya')).workspace; assert(!visibleWorkspace(s, ctx()).posts.some(x => x.id === 'post_common')); assert.equal(s.audit.at(-1)?.action, 'post.hidden'); });
test('enrolment is idempotent', () => assert.equal(run({ type: 'track.enrol', trackId: 'track_product' }).workspace.enrolments.filter(e => e.userId === DEMO_USER).length, 1));
test('must enrol before completing', () => assert.throws(() => run({ type: 'lesson.complete', trackId: 'track_story', lessonId: 'lesson_1' })));
test('lesson must belong to the requested track', () => assert.throws(() => run({ type: 'lesson.complete', trackId: 'track_product', lessonId: 'lesson_1' })));
test('completion and points award once', () => { const c = { type: 'lesson.complete', trackId: 'track_product', lessonId: 'lesson_5' }; let s = run(c).workspace; s = run(c, s).workspace; assert.equal(s.completions.filter(x => x.lessonId === 'lesson_5').length, 1); assert.equal(reputationTotals(s, DEMO_USER).learning, 40); assert.equal(progress(s, DEMO_USER, 'track_product').percent, 67); });
test('mission submission begins pending, not approved', () => { const s = run({ type: 'mission.submit', missionId: 'mission_film', body: 'My work and reflection', url: 'https://example.com/work' }).workspace; assert.equal(s.submissions.at(-1)?.status, 'pending'); assert.equal(reputationTotals(s, DEMO_USER).building, 0); });
test('pending proof cannot be replaced silently', () => { const c = { type: 'mission.submit', missionId: 'mission_film', body: 'My work', url: '' }; const s = run(c).workspace; assert.throws(() => run(c, s)); });
test('ordinary member cannot review', () => assert.throws(() => run({ type: 'submission.review', submissionId: 'submission_jordan', decision: 'approved', feedback: 'Good work' })));
test('own proof cannot be self approved', () => { let s = run({ type: 'mission.submit', missionId: 'mission_film', body: 'My own film', url: '' }, createSeed(), ctx(DEMO_ADMIN)).workspace; const sub = s.submissions.at(-1)!; assert.throws(() => run({ type: 'submission.review', submissionId: sub.id, decision: 'approved', feedback: 'Approve' }, s, ctx(DEMO_ADMIN))); });
test('approval awards points only once', () => { const c = { type: 'submission.review', submissionId: 'submission_jordan', decision: 'approved', feedback: 'The three touchpoints feel connected.' }; const s = run(c, createSeed(), ctx(DEMO_ADMIN)).workspace; assert.equal(reputationTotals(s, 'member_jordan').building, 100); assert.throws(() => run(c, s, ctx(DEMO_ADMIN))); });
test('requested changes support resubmission', () => { const c = ctx('member_jordan'); let s = run({ type: 'submission.review', submissionId: 'submission_jordan', decision: 'changes_requested', feedback: 'Please add the third example.' }, createSeed(), ctx(DEMO_ADMIN)).workspace; s = run({ type: 'mission.submit', missionId: 'mission_brand', body: 'All three examples now included.', url: '' }, s, c).workspace; assert.equal(s.submissions[0].status, 'pending'); assert.equal(s.submissions.length, 1); });
for (const url of ['javascript:alert(1)', 'data:text/html,hello', 'http://example.com', 'https://user:pass@example.com', 'not a URL'])
    test(`reject unsafe link ${url}`, () => assert(!safeUrl(url)));
test('valid HTTPS link accepted', () => assert(safeUrl('https://example.com/work?q=test')));
test('project join idempotent', () => { const c = { type: 'project.join', projectId: 'project_afterhours' }; let s = run(c).workspace; s = run(c, s).workspace; assert.equal(s.projectMembers.filter(x => x.projectId === 'project_afterhours' && x.userId === DEMO_USER).length, 1); });
test('non-team member cannot update project', () => assert.throws(() => run({ type: 'project.update', projectId: 'project_afterhours', body: 'Update' })));
test('new project automatically includes its owner', () => { const r = run({ type: 'project.create', title: 'A new thing', tagline: 'A small useful thing.', summary: 'What it will do.', category: 'Product', skills: ['Design'], spaceId: null }); assert(r.workspace.projectMembers.some(m => m.projectId === r.objectId && m.userId === DEMO_USER)); });
test('RSVP toggles without duplicate entries', () => { const c = { type: 'event.rsvp', eventId: 'event_open' }; let s = run(c).workspace; assert.equal(s.rsvps.filter(x => x.eventId === 'event_open' && x.userId === DEMO_USER).length, 1); s = run(c, s).workspace; assert.equal(s.rsvps.filter(x => x.eventId === 'event_open' && x.userId === DEMO_USER).length, 0); });
test('past event cannot be joined', () => { const s = createSeed(); s.events[0].startsAt = '2020-01-01T00:00:00.000Z'; assert.throws(() => run({ type: 'event.rsvp', eventId: 'event_open' }, s)); });
test('profile updates cannot elevate role', () => assert.throws(() => run({ type: 'profile.update', name: 'Alex', headline: 'Maker', bio: 'Bio', skills: [], role: 'owner' })));
test('another person’s notification is inaccessible', () => assert.throws(() => run({ type: 'notification.read', notificationId: 'notification_1' }, createSeed(), ctx(DEMO_ADMIN))));
test('notification read is scoped to its user', () => { const s = run({ type: 'notification.read' }).workspace; assert(s.notifications.filter(n => n.userId === DEMO_USER).every(n => n.readAt)); });
for (const c of [{ type: 'organisation.update', name: 'New name', tagline: 'Together', accent: 'mint' }, { type: 'space.create', name: 'A space', description: 'A place', visibility: 'private', kind: 'discussion' }, { type: 'track.create', title: 'A track', summary: 'Something useful', description: 'Learn a skill', category: 'Design', spaceId: null }])
    test(`members cannot ${c.type}`, () => assert.throws(() => run(c)));
test('new private space includes creator', () => { const r = run({ type: 'space.create', name: 'A focused space', description: 'For a small team', visibility: 'private', kind: 'project' }, createSeed(), ctx(DEMO_ADMIN)); assert(r.workspace.spaceMembers.some(m => m.spaceId === r.objectId && m.userId === DEMO_ADMIN)); });
test('space slug conflicts rejected', () => assert.throws(() => run({ type: 'space.create', name: 'general', description: 'duplicate', visibility: 'members', kind: 'discussion' }, createSeed(), ctx(DEMO_ADMIN))));
test('empty course has zero rather than fabricated progress', () => assert.equal(progress(createSeed(), DEMO_USER, 'missing').percent, 0));
test('events carry request context but no input secrets', () => { const s = run({ type: 'post.react', postId: 'post_common' }).workspace; assert.equal(s.outbox.at(-1)?.payload.requestId, 'test_request'); assert.equal(visibleWorkspace(s, ctx()).outbox.length, 0); });
