import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { openDatabase, type Database } from '../packages/db/src/connection';
import { migrate } from '../packages/db/src/migrate';
import { WorkspaceRepository } from '../packages/db/src/repository';
import { createSeed, DEMO_USER, DEMO_ADMIN } from '../packages/domain/src/seed';
import { createApp } from '../apps/api/src/app';
import { createAuth } from '../apps/api/src/auth';
import { objectKey, uploadSchema } from '../apps/api/src/storage';
const origin = 'https://reunir.test', base = '/api/organisations/code-black';
let db: Database, repo: WorkspaceRepository, app: ReturnType<typeof createApp>, identity: {
    id: string;
    name: string;
} | null = { id: DEMO_USER, name: 'Alex' };
let authApp: ReturnType<typeof createApp>;
let cookie = '';
const jsonHeaders = (extra: Record<string, string> = {}) => ({ 'Content-Type': 'application/json', Origin: origin, 'Idempotency-Key': randomUUID(), ...extra });
const send = (cmd: unknown, extra: Record<string, string> = {}) => app.request(base + '/commands', { method: 'POST', headers: jsonHeaders(extra), body: JSON.stringify(cmd) });
before(async () => { db = await openDatabase('pglite:memory'); await migrate(db); repo = new WorkspaceRepository(db); await repo.seed(createSeed()); app = createApp({ repository: repo, origin, resolveSession: async () => identity }); });
after(async () => db?.close());
test('health reports actual database adapter, not Neon when using PGlite', async () => { const r = await app.request('/api/health'); assert.equal(r.status, 200); assert.equal((await r.json()).database, 'pglite'); });
test('anonymous session is null', async () => { identity = null; const r = await app.request('/api/session'); assert.equal(await r.json(), null); identity = { id: DEMO_USER, name: 'Alex' }; });
test('anonymous workspace request is 401 even with forged headers', async () => { identity = null; const r = await app.request(base + '/workspace', { headers: { 'X-User-Id': DEMO_ADMIN, 'X-Role': 'owner' } }); assert.equal(r.status, 401); identity = { id: DEMO_USER, name: 'Alex' }; });
test('workspace response is scoped and never cacheable', async () => { const r = await app.request(base + '/workspace'); assert.equal(r.status, 200); assert.equal(r.headers.get('cache-control'), 'no-store'); const s = await r.json(); assert(!s.spaces.some((x: any) => x.visibility === 'private')); });
test('mutations refuse a foreign Origin', async () => { assert.equal((await send({ type: 'post.react', postId: 'post_welcome' }, { Origin: 'https://evil.example' })).status, 403); });
test('mutations refuse a missing Origin', async () => { const r = await app.request(base + '/commands', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); assert.equal(r.status, 403); });
test('mutations reject non-JSON content', async () => { const r = await app.request(base + '/commands', { method: 'POST', headers: { Origin: origin, 'Content-Type': 'text/plain' }, body: '{}' }); assert.equal(r.status, 415); });
test('mutations reject malformed JSON', async () => { const r = await app.request(base + '/commands', { method: 'POST', headers: jsonHeaders(), body: '{oops' }); assert.equal(r.status, 400); });
test('mutation schema rejects invented role fields', async () => { const r = await send({ type: 'post.create', spaceId: 'space_general', kind: 'update', title: 'No', body: 'Attempted escalation', role: 'owner' }); assert.equal(r.status, 400); });
test('oversized HTTP body is rejected before persistence', async () => { const r = await app.request(base + '/commands', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ blob: 'x'.repeat(70000) }) }); assert.equal(r.status, 413); });
test('post creation persists and returns a usable object', async () => { const r = await send({ type: 'post.create', spaceId: 'space_general', kind: 'update', title: 'HTTP proof', body: 'The server actually saved this.' }); assert.equal(r.status, 200); const j = await r.json(); assert(j.objectId); assert(j.workspace.posts.some((p: any) => p.id === j.objectId)); });
test('unknown tenant returns 404 without revealing data', async () => { const r = await app.request('/api/organisations/another-tenant/workspace'); assert.equal(r.status, 404); });
test('a member cannot use the admin command', async () => { assert.equal((await send({ type: 'space.create', name: 'No', description: 'Not permitted', kind: 'discussion', visibility: 'members' })).status, 403); });
test('private post cannot be bookmarked through guessed IDs', async () => { assert.equal((await send({ type: 'post.bookmark', postId: 'post_private' })).status, 404); });
test('missing idempotency key is rejected', async () => { const r = await app.request(base + '/commands', { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'post.react', postId: 'post_welcome' }) }); assert.equal(r.status, 400); });
test('storage clearly fails closed when no bucket is configured', async () => { const r = await app.request(base + '/uploads', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ name: 'proof.pdf', contentType: 'application/pdf', sizeBytes: 100 }) }); assert.equal(r.status, 503); });
test('no arbitrary file names or active HTML accepted', () => { assert.throws(() => uploadSchema.parse({ name: '../secrets', contentType: 'application/pdf', sizeBytes: 10 })); assert.throws(() => uploadSchema.parse({ name: 'x.html', contentType: 'text/html', sizeBytes: 10 })); assert.throws(() => uploadSchema.parse({ name: 'x.pdf', contentType: 'application/pdf', sizeBytes: 11000000 })); });
test('object keys are generated under verified user and tenant', () => { const key = objectKey('org1', 'person1', 'image/png'); assert(key.startsWith('organisations/org1/members/person1/')); assert(key.endsWith('.png')); assert.throws(() => objectKey('../org', 'person1', 'image/png')); });
test('full mission submission to approval survives the HTTP/database boundary', async () => {
    let r = await send({ type: 'mission.submit', missionId: 'mission_film', body: 'An original thirty-second film and a reflection on the sound.', url: 'https://example.com/film' });
    assert.equal(r.status, 200);
    const id = (await r.json()).objectId;
    identity = { id: DEMO_ADMIN, name: 'Amina' };
    r = await send({ type: 'submission.review', submissionId: id, decision: 'approved', feedback: 'The sound choice makes the intention clear.' });
    assert.equal(r.status, 200);
    identity = { id: DEMO_USER, name: 'Alex' };
    const s = await repo.snapshot('code-black', DEMO_USER);
    assert.equal(s.submissions.find(x => x.id === id)?.status, 'approved');
    assert.equal(s.reputation.filter(x => x.dimension === 'building').length, 1);
    assert(s.notifications.some(n => n.href === '/missions/mission_film'));
});
test('real Better Auth creates an account without copying custom password logic', async () => {
    const secret = 'test_only_2e073dda06a88698b81f45de62344476';
    const boot = createAuth(db, origin, secret, true);
    const user = await boot.api.signUpEmail({ body: { name: 'Test Owner', email: 'owner@example.test', password: 'A-long-test-password-123!' } });
    assert(user.user.id);
    await repo.createCommunity({ id: user.user.id, name: user.user.name }, 'auth-community', 'Auth Community');
    const auth = createAuth(db, origin, secret);
    authApp = createApp({ repository: repo, origin, authHandler: r => auth.handler(r), resolveSession: async (headers) => { const s = await auth.api.getSession({ headers }); return s ? { id: s.user.id, name: s.user.name } : null; } });
    const r = await authApp.request('/api/auth/sign-in/email', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ email: 'owner@example.test', password: 'A-long-test-password-123!' }) });
    assert.equal(r.status, 200);
    cookie = r.headers.getSetCookie().map(x => x.split(';')[0]).join('; ');
    assert(cookie.includes('reunir'));
    assert(r.headers.getSetCookie().some(x => x.toLowerCase().includes('httponly')));
});
test('verified cookie session resolves actual membership', async () => { const r = await authApp.request('/api/session', { headers: { Cookie: cookie } }); assert.equal(r.status, 200); const j = await r.json(); assert.equal(j.name, 'Test Owner'); assert.equal(j.memberships[0].slug, 'auth-community'); });
test('authenticated API can read newly bootstrapped community', async () => { const r = await authApp.request('/api/organisations/auth-community/workspace', { headers: { Cookie: cookie } }); assert.equal(r.status, 200); const j = await r.json(); assert.equal(j.members.length, 1); assert.equal(j.tracks.length, 0); });
test('production-style handler does not allow public signups', async () => { const r = await authApp.request('/api/auth/sign-up/email', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ name: 'Nobody', email: 'new@example.test', password: 'Another-long-password-123!' }) }); assert(r.status >= 400); });
test('fake session cookie does not authenticate', async () => { const r = await authApp.request('/api/organisations/auth-community/workspace', { headers: { Cookie: 'reunir.session_token=fake' } }); assert.equal(r.status, 401); });
test('an authenticated user cannot cross to another tenant', async () => { const r = await authApp.request('/api/organisations/code-black/workspace', { headers: { Cookie: cookie } }); assert.equal(r.status, 404); });
// The real Google service is not called here: test capability boundaries with an explicit fake provider.
let uploadApp: ReturnType<typeof createApp>, uploadId = '', expectedBytes = 200;
let mintedKey = '';
test('private upload policy is minted only beneath the authorised tenant/user', async () => {
    uploadApp = createApp({ repository: repo, origin, resolveSession: async () => identity, storage: { upload: async (key, type, size) => { mintedKey = key; assert.equal(size, 200); assert.equal(type, 'application/pdf'); return { url: 'https://storage.example.test/upload', fields: { key, 'Content-Type': type } }; }, download: async () => 'https://storage.example.test/download', metadata: async () => ({ size: expectedBytes, contentType: 'application/pdf' }) } });
    const r = await uploadApp.request(base + '/uploads', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ name: 'proof.pdf', contentType: 'application/pdf', sizeBytes: 200 }) });
    assert.equal(r.status, 201);
    const j = await r.json();
    uploadId = j.id;
    assert.equal(j.method, 'POST');
    assert.equal(j.expiresIn, 300);
    assert(mintedKey.startsWith('organisations/org_code_black/members/member_alex/'));
});
test('an incomplete file cannot be downloaded', async () => { const r = await uploadApp.request(base + `/uploads/${uploadId}/download`); assert.equal(r.status, 409); });
test('a different member cannot complete another member file', async () => { identity = { id: DEMO_ADMIN, name: 'Amina' }; const r = await uploadApp.request(base + `/uploads/${uploadId}/complete`, { method: 'POST', headers: jsonHeaders(), body: '{}' }); assert.equal(r.status, 404); identity = { id: DEMO_USER, name: 'Alex' }; });
test('matching storage metadata completes a private upload', async () => { const r = await uploadApp.request(base + `/uploads/${uploadId}/complete`, { method: 'POST', headers: jsonHeaders(), body: '{}' }); assert.equal(r.status, 200); assert.equal((await r.json()).status, 'ready'); });
test('only the owner receives the short-lived download capability', async () => { let r = await uploadApp.request(base + `/uploads/${uploadId}/download`); assert.equal(r.status, 200); assert.equal((await r.json()).expiresIn, 120); identity = { id: DEMO_ADMIN, name: 'Amina' }; r = await uploadApp.request(base + `/uploads/${uploadId}/download`); assert.equal(r.status, 404); identity = { id: DEMO_USER, name: 'Alex' }; });
test('mismatched storage metadata rejects the upload', async () => { expectedBytes = 201; const r = await uploadApp.request(base + `/uploads/${uploadId}/complete`, { method: 'POST', headers: jsonHeaders(), body: '{}' }); assert.equal(r.status, 400); assert.equal((await uploadApp.request(base + `/uploads/${uploadId}/download`)).status, 409); });
