import {useState,useEffect} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {Mail,Plus,Shield,Lock,Check,Copy,ArrowRight} from 'lucide-react';
import {useWorkspace} from '../lib/context';
import {api,displayError,type Identity} from '../lib/data';
import {Avatar,Empty,PageHeading,Pill,Modal,Mark,present} from '../components/ui';
import {isAdmin} from '../../../../packages/domain/src/access';
import {HandOverDialogue} from '../components/ownership';
import {newId} from '../../../../packages/contracts/src/index';
interface Invite {id:string;email:string;status:string;createdAt:string;expiresAt:string;delivery:string}
const demoInvites:Record<string,Invite[]>={};
window.addEventListener('reunir:reset-demo',()=>{for(const key of Object.keys(demoInvites))delete demoInvites[key];});
export function MemberAccessPage(){
 const {data,me,slug,userId,command,busy,mode,toast}=useWorkspace();const [filter,Filter]=useState(''),[invite,InviteModal]=useState(false),[email,Email]=useState(''),[link,NewLink]=useState(''),[working,Working]=useState(false),[manage,Manage]=useState<string|null>(null),[handover,HandOver]=useState<string|null>(null);
 const q=useQuery({queryKey:['invitations',slug,userId],enabled:isAdmin(me),queryFn:async()=>mode==='live'?api<Invite[]>(`/api/organisations/${slug}/invitations`):demoInvites[slug]||[]});
 if(!isAdmin(me))return <Empty title="The community team manages access." body="Your own profile is available from the sidebar."/>;
 const target=data.members.find(m=>m.id===manage),successor=data.members.find(m=>m.id===handover);
 async function send(){Working(true);try{if(mode==='demo'){const now=new Date().toISOString();demoInvites[slug]=[{id:newId(),email,status:'pending',createdAt:now,expiresAt:new Date(Date.now()+604800000).toISOString(),delivery:'demo-only'},...(demoInvites[slug]||[]).filter(i=>i.email!==email)];NewLink('demo');}else{const r=await api<{url:string;emailConfigured:boolean}>(`/api/organisations/${slug}/invitations`,{email});NewLink(r.url);toast(r.emailConfigured?'Invitation queued for email delivery.':'Invitation created. Email delivery needs configuration.');}await q.refetch();}catch(e){toast(displayError(e));}finally{Working(false);}}
 return <><PageHeading eyebrow="BELONGING BEGINS WITH AN INVITATION." title="Make room for your people." body="Welcome new members. Give the right access. Protect the work already here." action={<button className="button primary" onClick={()=>{InviteModal(true);NewLink('');Email('');}}><Plus size={16}/>Invite a member</button>}/>
 <div className="access-summary"><div className="panel"><strong>{data.members.filter(m=>m.status==='active').length}</strong><span>Active people</span></div><div className="panel"><strong>{q.data?.filter(i=>i.status==='pending'&&new Date(i.expiresAt)>new Date()).length||0}</strong><span>Open invitations</span></div><div className="panel"><Shield size={22}/><span>Roles are assigned deliberately, not earned through likes.</span></div></div>
 <section className="panel"><div className="panel-title"><h2>Membership & permissions</h2><input className="access-search" aria-label="Filter members" value={filter} onChange={e=>Filter(e.target.value)} placeholder="Find a member…"/></div><div className="access-members">{present(data.members).filter(m=>m.name.toLowerCase().includes(filter.toLowerCase())).map(m=><div className="access-member" key={m.id}><Avatar member={m}/><span><strong>{m.name}</strong><small>{m.headline||'Community member'}</small></span><Pill tone={m.status==='active'?'mint':'amber'}>{m.status}</Pill><Pill>{m.role}</Pill><button className="button secondary compact" onClick={()=>Manage(m.id)}>Manage<span className="sr-only"> {m.name}</span></button></div>)}</div></section>
 <section className="panel"><div className="panel-title"><h2>Invitations</h2><Pill>7-day expiry · one use</Pill></div>{q.error&&<p role="alert">{displayError(q.error)}</p>}{q.data?.map(i=><div className="invite-row" key={i.id}><span><strong>{i.email}</strong><small>{i.status==='pending'&&new Date(i.expiresAt)<new Date()?'expired':i.status} · {i.delivery||'queued'} · Expires {new Date(i.expiresAt).toLocaleDateString('en-GB')}</small></span>{i.status==='pending'&&<button className="button secondary compact" disabled={working} onClick={async()=>{Working(true);try{if(mode==='demo')demoInvites[slug]=demoInvites[slug].map(x=>x.id===i.id?{...x,status:'revoked',delivery:'cancelled'}:x);else await api(`/api/organisations/${slug}/invitations/${i.id}/revoke`,{});q.refetch();toast('Invitation revoked.');}catch(e){toast(displayError(e));}finally{Working(false);}}}>Revoke</button>}</div>)}{!q.data?.length&&!q.error&&<p className="muted">No invitations yet. Start with a few people who care about the purpose.</p>}<p className="sample-note">Invitations grant ordinary membership only. Sending a new invitation to the same email replaces the old link. {mode==='demo'?'This preview never sends email.':'Email is queued; delivery depends on the configured provider and worker.'}</p></section>
 {invite&&<Modal title="Invite someone good." onClose={()=>InviteModal(false)}>{!link?<form className="form-stack" onSubmit={e=>{e.preventDefault();send();}}><p>Invite a person to {data.organisation.name}. They will join as a member, without access to private spaces.</p><label>Email address<input type="email" required value={email} onChange={e=>Email(e.target.value.trim().toLowerCase())} autoComplete="off"/></label><p className="sample-note">Only invite people who are expecting to hear from you. This is not a bulk marketing tool.</p><button className="button primary" disabled={working}><Mail size={16}/>{working?'Creating invitation…':mode==='demo'?'Try creating an invitation':'Create invitation'}</button></form>:<div className="form-stack"><Pill tone="mint"><Check size={13}/>Invitation created</Pill><h3>{email}</h3>{mode==='demo'?<p>No email was sent. New-account registration and link acceptance are tested in connected mode, not simulated here.</p>:<><p>This personal link is shown once. Treat it like a key. Share it only with the intended recipient.</p><label>Personal invitation link<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);toast('Link copied.');}catch{toast('Select the link and copy it manually.');}}}><Copy size={16}/>Copy invitation</button></>}<button className="button primary" onClick={()=>InviteModal(false)}>Done</button></div>}</Modal>}
 {target&&<Modal title={`Access for ${target.name}`} onClose={()=>Manage(null)}><div className="form-stack"><p>Access changes apply only inside {data.organisation.name}. Existing posts, contributions and reviewed outcomes are retained.</p><label>Community role<select aria-label="Community role" value={target.role} disabled={busy||me.role!=='owner'||target.role==='owner'||target.status!=='active'} onChange={e=>{const role=e.target.value as 'member'|'moderator'|'admin';if(window.confirm(`Change ${target.name}'s role to ${role}?`))command({type:'member.role',memberId:target.id,role});}}>{['member','moderator','admin',...(target.role==='owner'?['owner']:[])].map(r=><option key={r}>{r}</option>)}</select></label>{me.role!=='owner'&&<small>Only the owner can assign community roles.</small>}{me.role==='owner'&&target.userId!==userId&&target.status==='active'&&(target.role==='admin'?<div className="form-stack access-ownership"><h3>Ownership</h3><p>Hand {data.organisation.name} to {target.name}. You stay as an administrator.</p><button type="button" className="button secondary" disabled={busy} onClick={()=>{Manage(null);HandOver(target.id);}}>Hand over ownership…</button></div>:<small>To hand {target.name} ownership, make them an administrator first.</small>)}<h3>Private spaces</h3>{data.spaces.filter(s=>s.visibility==='private').map(s=><label className="access-checkbox" key={s.id}><input type="checkbox" checked={isAdmin(target)||data.spaceMembers.some(m=>m.userId===target.userId&&m.spaceId===s.id)} disabled={busy||isAdmin(target)||target.status!=='active'} onChange={e=>command({type:'space.access',spaceId:s.id,userId:target.userId,granted:e.target.checked})}/><Lock size={14}/>{s.name}</label>)}{isAdmin(target)&&<small>Owners and administrators can access private spaces. This does not grant access to private goals or other members’ messages.</small>}{target.role!=='owner'&&target.userId!==userId&&(me.role==='owner'||target.role!=='admin')&&<form className="form-stack access-suspend" onSubmit={async e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason'));if(window.confirm(`${target.status==='active'?'Suspend':'Restore'} access for ${target.name}?`)){const r=await command({type:'member.status',memberId:target.id,status:target.status==='active'?'suspended':'active',reason});if(r)Manage(null);}}}><label>Reason for changing access<input name="reason" required maxLength={500} placeholder="A note for the private audit trail"/></label><button className="button secondary" disabled={busy}>{target.status==='active'?'Suspend community access':'Restore community access'}</button></form>}{target.role==='owner'&&<p className="sample-note">The owner cannot be suspended or demoted here. The owner can hand the community to an administrator from that administrator’s access settings.</p>}</div></Modal>}
 {successor&&<HandOverDialogue target={successor} onClose={()=>HandOver(null)}/>}
 </>;
}
export function AccountAccessPage({identity,onDone}:{identity?:Identity|null;onDone:()=>void}){
 const loc=useLocation(),navigate=useNavigate();
 const params=new URLSearchParams(loc.search),token=params.get('token')||new URLSearchParams(window.location.search).get('token')||'';
 const reset=loc.pathname==='/reset-password';
 const [name,Name]=useState(''),[email,Email]=useState(''),[password,Password]=useState(''),[busy,Busy]=useState(false),[error,ErrorText]=useState(''),[done,Done]=useState(''),[existing,Existing]=useState(!!identity);
 useEffect(()=>{if(identity)Existing(true);},[identity?.id]);
 const q=useQuery({queryKey:['invite',token],queryFn:()=>api<{community:string;emailHint:string;expiresAt:string}>('/api/invitations/inspect',{token}),enabled:!reset&&!!token,retry:false});
 async function submit(){Busy(true);ErrorText('');try{
  if(reset){await api('/api/auth/reset-password',{token,newPassword:password});Done('Your password has been updated. Sign in again with your new password.');}
  else if(existing){if(!identity)await api('/api/auth/sign-in/email',{email,password});await api('/api/invitations/accept',{token});onDone();navigate('/');}
  else{await api('/api/invitations/register',{token,name,password});Done('Your account and community membership are ready. Sign in with the invited email address and your new password.');}
 }catch(e){ErrorText(displayError(e));}finally{Busy(false);}}
 return <main className="login-page"><div className="login-art"><Mark size={40}/><span className="eyebrow">REUNIR · YOUR NEXT CHAPTER</span><h1>Your people.<br/>Real progress.</h1><p>Come for the people. Stay for what you become, build and achieve together.</p></div><section className="form-stack account-access"><Pill tone="mint"><Lock size={13}/>{reset?'Secure account recovery':'A personal invitation'}</Pill><h2>{reset?'A fresh start.':q.data?`Welcome to ${q.data.community}.`:'Your invitation.'}</h2>{done?<><p role="status">{done}</p><button className="button primary" onClick={()=>{window.history.replaceState(null,'',window.location.pathname+'#/');window.location.reload();}}>Go to sign in <ArrowRight size={16}/></button></>:!token||q.error?<><p className="form-error" role="alert">{!token?'This link is incomplete. Ask the community owner for a new invitation.':displayError(q.error)}</p><Link className="button secondary" to="/">Return to sign in</Link></>:<form className="form-stack" onSubmit={e=>{e.preventDefault();submit();}}>{!reset&&q.data&&<p>Invited for <strong>{q.data.emailHint}</strong>. The link expires on {new Date(q.data.expiresAt).toLocaleDateString('en-GB')}.</p>}{!reset&&!existing&&<label>Your name<input required maxLength={80} minLength={2} autoComplete="name" value={name} onChange={e=>Name(e.target.value)}/></label>}{!reset&&existing&&!identity&&<label>Invited email address<input type="email" required autoComplete="email" value={email} onChange={e=>Email(e.target.value)}/></label>}{(!identity||reset||!existing)&&<label><span id="access-password-label">{reset||!existing?'New password':'Password'}</span><input type="password" aria-labelledby="access-password-label" aria-describedby={reset||!existing?'access-password-help':undefined} required minLength={reset||!existing?12:1} maxLength={128} autoComplete={reset||!existing?'new-password':'current-password'} value={password} onChange={e=>Password(e.target.value)}/><small id="access-password-help">{reset||!existing?'Use at least 12 characters.':''}</small></label>}{identity&&!reset&&existing&&<p>Signed in as {identity.name}. Accepting uses your existing account.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy||(!reset&&q.isPending)}>{busy?'Working…':reset?'Update password':existing?'Accept invitation':'Create my account'}</button>{!reset&&!identity&&<button type="button" className="button secondary" onClick={()=>{Existing(!existing);Password('');ErrorText('');}}>{existing?'Create a new account instead':'Already have an account? Sign in'}</button>}{!reset&&identity&&<button type="button" className="button secondary" onClick={async()=>{await api('/api/auth/sign-out',{});onDone();window.location.reload();}}>Use a different account</button>}</form>}</section></main>;
}
