import { LessonEditor } from '../components/lesson-editor';
import { LessonBody } from '../components/lesson-content';
import { ResourceEditor } from '../components/lesson-resources';
import { ResourceList } from '../components/resource-list';
import { QuizEditor, quizProblems } from '../components/quiz-editor';
import { QuizPreview } from '../components/quiz-view';
import { resourceUploadsAvailable } from '../lib/resources';
import { useQuery } from '@tanstack/react-query';
import { isLessonDocument } from '../../../../packages/contracts/src/lesson-document';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowDown, ArrowUp, ArrowUpRight, BookOpen, Check, Eye, History, LockKeyhole, Pencil, Plus, Save } from 'lucide-react';
import { type LessonDraft, type MutationResult, safeUrl } from '../../../../packages/contracts/src/index';
import { lessonContent, type EditableLessonContent } from '../../../../packages/domain/src/authoring';
import { isAdmin } from '../../../../packages/domain/src/access';
import { useWorkspace } from '../lib/context';
import { Empty, PageHeading, Pill } from '../components/ui';

export function AuthoringPage() {
    const {id}=useParams(); const {data,me,busy,command}=useWorkspace();
    const [selected,select]=useState<string|null>(null); const [archived,showArchived]=useState(false);
    const track=data.tracks.find(t=>t.id===id);
    if(!isAdmin(me)||!track)return <Empty title="The creator studio is private." body="A community owner or administrator can author lessons here."/>;
    const lessons=data.lessons.filter(l=>l.trackId===track.id).sort((a,b)=>a.position-b.position);
    const drafts=data.lessonDrafts.filter(d=>d.trackId===track.id&&(archived||!d.archived));
    const current=data.lessonDrafts.find(d=>d.trackId===track.id&&d.id===selected);
    const open=async(lessonId:string|null=null)=>{const r=await command({type:'lesson.draft.create',trackId:track.id,lessonId});if(r?.objectId){select(r.objectId);showArchived(true);}};
    const move=async(index:number,delta:number)=>{const ids=lessons.map(l=>l.id),next=[...ids];[next[index],next[index+delta]]=[next[index+delta],next[index]];await command({type:'track.lessons.reorder',trackId:track.id,expectedOrder:ids,lessonIds:next});};
    return <section className="creator-studio"><Link className="text-link" to={`/learn/${track.id}`}>← Back to the learning track</Link>
        <PageHeading eyebrow="CREATOR STUDIO" title="Teach something that matters." body={track.title} action={<button className="button primary" disabled={busy} onClick={()=>open()}><Plus size={17}/>New lesson draft</button>}/>
        <div className="creator-notice"><LockKeyhole size={19}/><div><strong>A place to work before you share.</strong><span>Drafts and revisions are visible only to your community’s owners and administrators. Publishing is a separate decision.</span></div></div>
        <div className="creator-layout"><aside className="panel creator-outline"><h2><BookOpen size={18}/>Curriculum <small>{lessons.length}</small></h2>
            <p className="muted">Reorder the live outline without resetting anyone’s progress.</p>
            <ol className="creator-lessons">{lessons.map((l,i)=><li key={l.id}><span className="creator-position">{String(i+1).padStart(2,'0')}</span><button className="creator-title" disabled={busy} onClick={()=>open(l.id)}>{l.title}<small>Open for editing</small></button><div className="creator-move"><button className="icon-button" aria-label={`Move ${l.title} up`} disabled={busy||i===0} onClick={()=>move(i,-1)}><ArrowUp size={14}/></button><button className="icon-button" aria-label={`Move ${l.title} down`} disabled={busy||i===lessons.length-1} onClick={()=>move(i,1)}><ArrowDown size={14}/></button></div></li>)}</ol>
            <div className="creator-draft-heading"><h2><Pencil size={17}/>Your drafts</h2><label><input type="checkbox" checked={archived} onChange={e=>showArchived(e.target.checked)}/>Show archive</label></div>
            <div className="creator-drafts">{drafts.map(d=><button key={d.id} className={d.id===selected?'selected':''} onClick={()=>select(d.id)}><strong>{d.title||'Untitled lesson'}</strong><small>{d.archived?'Archived':d.publishedVersion===d.version?'Matches published version':'Unpublished changes'} · v{d.version}</small></button>)}</div>
            {!drafts.length&&<p className="muted">Open an existing lesson or create your first private draft.</p>}
        </aside>{current?<DraftEditor key={current.id} draft={current}/>:<div className="panel creator-welcome"><span className="creator-welcome-icon"><Pencil size={32}/></span><h2>Good teaching starts<br/>with a useful first draft.</h2><p>Write, save and preview privately. Publish when the lesson is ready for your people.</p><button className="button primary" disabled={busy} onClick={()=>open()}>Create a lesson draft <ArrowUpRight size={16}/></button><small>Existing lessons, missions and completion records stay in place.</small></div>}</div>
    </section>;
}
function DraftEditor({draft}:{draft:LessonDraft}) {
    const {data,me,busy,command,downloadResource}=useWorkspace();
    const [fields,setFields]=useState<EditableLessonContent>(()=>lessonContent(draft));
    const [saved,setSaved]=useState<EditableLessonContent>(()=>lessonContent(draft));
    const storage=useQuery({queryKey:['resource-uploads'],queryFn:resourceUploadsAvailable,staleTime:300000});
    const [version,setVersion]=useState(draft.version); const [preview,showPreview]=useState(false);
    const dirty=JSON.stringify(fields)!==JSON.stringify(saved),stale=draft.version!==version;
    const invalid=!!fields.richBody&&!isLessonDocument(fields.richBody);
    const filesInvalid=fields.resources.some(r=>!r.name.trim()||r.name.trim().length>120||r.description.trim().length>280);
    const quizInvalid=quizProblems(fields.quiz).length>0;
    const revisions=data.lessonRevisions.filter(r=>r.lessonId===draft.lessonId).sort((a,b)=>b.sequence-a.sequence);
    const change=<K extends keyof EditableLessonContent>(key:K,value:EditableLessonContent[K])=>setFields(f=>({...f,[key]:value}));
    const refresh=(d:LessonDraft)=>{setFields(lessonContent(d));setSaved(lessonContent(d));setVersion(d.version);};
    const accept=(result:MutationResult|undefined)=>{const d=result?.workspace.lessonDrafts.find(d=>d.id===draft.id);if(d)refresh(d);};
    useEffect(()=>{if(!dirty&&!stale) return;const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty,stale]);
    // Guard in-app anchor and button navigation away from this editor while unsaved.
    // The editor's own controls remain interactive. No additional unsaved-editor buffer is persisted; demo mode retains its explicit fictional dataset.
    useEffect(()=>{if(!dirty)return;const guard=(e:MouseEvent)=>{const target=e.target as Element;if(target.closest('.creator-editor'))return;const actionable=target.closest('a,button');if(actionable&&!window.confirm('Discard your unsaved lesson edits?')){e.preventDefault();e.stopPropagation();}};document.addEventListener('click',guard,true);return()=>document.removeEventListener('click',guard,true);},[dirty]);
    return <div className="panel creator-editor"><div className="creator-toolbar"><Pill tone={draft.archived?'neutral':dirty?'amber':'mint'}>{draft.archived?'Archived draft':dirty?'Unsaved edits':'Saved privately'}</Pill><span>Version {version}</span><div className="creator-mode"><button className={!preview?'selected':''} onClick={()=>showPreview(false)}><Pencil size={14}/>Write</button><button className={preview?'selected':''} onClick={()=>showPreview(true)}><Eye size={14}/>Preview</button></div></div>
        {stale&&<div className="creator-conflict" role="alert">A newer version was saved. Your edits have not been overwritten. <button className="text-link" onClick={()=>{if(!dirty||window.confirm('Replace these unsaved edits with the latest saved draft?'))refresh(draft);}}>Reload saved draft</button></div>}
        {preview?<article className="creator-preview"><span className="eyebrow">PRIVATE LESSON PREVIEW · {fields.minutes} MIN READ</span><h2>{fields.title||'Untitled lesson'}</h2><p className="lesson-summary">{fields.summary||'Add a short introduction to the lesson.'}</p><LessonBody body={fields.body} richBody={fields.richBody}/><ResourceList resources={fields.resources} onDownload={r=>downloadResource({context:'draft',recordId:draft.id,resourceId:r.id})} available={r=>!dirty&&!stale&&saved.resources.some(x=>x.id===r.id&&x.fileId===r.fileId)} note={dirty?'Save the draft to download files from this preview.':'Preview downloads use the saved draft. Learners receive these files only after you publish.'}/>{fields.quiz&&<QuizPreview quiz={fields.quiz} name={`preview-${draft.id}`}/>}{fields.resourceUrl&&safeUrl(fields.resourceUrl)&&<a className="text-link" href={fields.resourceUrl} target="_blank" rel="noopener noreferrer">Further reading <ArrowUpRight size={15}/></a>}<p className="sample-note">This is a preview of your draft. It is not published and cannot award completion points.</p></article>:<div className="form-stack creator-form"><label>Lesson title<input maxLength={120} value={fields.title} disabled={draft.archived} onChange={e=>change('title',e.target.value)}/></label><label>Lesson summary<textarea aria-label="Lesson summary" rows={2} maxLength={240} value={fields.summary} disabled={draft.archived} onChange={e=>change('summary',e.target.value)}/></label><div><span className="lesson-body-label">Lesson body</span><LessonEditor body={fields.body} richBody={fields.richBody} disabled={draft.archived||busy} onChange={(richBody,body)=>setFields(f=>({...f,body,richBody}))}/>{invalid&&<p role="alert">This lesson is too large or has unsupported formatting. Shorten it or undo the last change before saving.</p>}</div><div className="creator-form-pair"><label>Reading time (minutes)<input type="number" min={1} max={240} value={fields.minutes} disabled={draft.archived} onChange={e=>change('minutes',Number(e.target.value))}/></label><label>Further reading URL<input type="url" maxLength={2000} placeholder="https://" value={fields.resourceUrl} disabled={draft.archived} onChange={e=>change('resourceUrl',e.target.value)}/></label></div><ResourceEditor trackId={draft.trackId} resources={fields.resources} saved={saved.resources} disabled={draft.archived||busy} uploadsAvailable={storage.data!==false} onChange={update=>setFields(f=>({...f,resources:update(f.resources)}))}/><QuizEditor quiz={fields.quiz} disabled={draft.archived||busy} onChange={update=>setFields(f=>({...f,quiz:update(f.quiz)}))}/><small className="muted">Format your lesson, preview it, then save privately. External images and videos load only when a learner chooses.</small></div>}
        <div className="creator-actions"><button className="button secondary" disabled={busy||draft.archived||!dirty||stale||invalid||filesInvalid||quizInvalid} onClick={async()=>accept(await command({type:'lesson.draft.save',draftId:draft.id,expectedVersion:version,...fields,body:fields.richBody?'':fields.body}))}><Save size={16}/>Save draft</button><button className="button primary" disabled={busy||dirty||stale||draft.archived||draft.publishedVersion===draft.version} onClick={async()=>{if(window.confirm('Publish this saved version? People with access to the track will see the updated lesson. Existing completion records will not reset.'))accept(await command({type:'lesson.draft.publish',draftId:draft.id,expectedVersion:version}));}}><Check size={16}/>Publish saved lesson</button></div><p className="creator-save-note">{dirty?'Save your edits before publishing.':draft.publishedVersion===draft.version?'This saved version matches the published lesson.':'Your saved changes are private until you publish.'}</p>
        <details className="creator-history"><summary><History size={17}/>Revision history <span>{revisions.length}</span></summary>{revisions.length?revisions.map(r=><div className="creator-revision" key={r.id}><div><strong>{r.kind==='captured'?'Captured existing lesson':`Published revision ${r.sequence}`}</strong><small>{new Date(r.createdAt).toLocaleString('en-GB')} · {data.members.find(m=>m.userId===r.actorId)?.name||'Community administrator'}</small><p>{r.title}</p><ResourceList compact resources={r.resources??[]} onDownload={x=>downloadResource({context:'revision',recordId:r.id,resourceId:x.id})}/>{r.quiz&&<small className="creator-revision-quiz">Knowledge check · {r.quiz.questions.length} {r.quiz.questions.length===1?'question':'questions'}</small>}{r.kind==='captured'&&<small>Captured at the start of editing, not a claim about the original publisher.</small>}</div><button className="button secondary compact" disabled={busy||dirty||stale||draft.archived} onClick={async()=>{if(window.confirm('Copy this revision into the saved draft? It will not change the live lesson until you publish.'))accept(await command({type:'lesson.draft.restore',draftId:draft.id,expectedVersion:version,revisionId:r.id}));}}>Restore as draft</button></div>):<p className="muted">The first published version will appear here.</p>}</details>
        <div className="creator-archive"><small>Working as {me.name}. Archiving a draft never unpublishes a lesson.</small><button className="text-link" disabled={busy||dirty||stale} onClick={async()=>accept(await command({type:'lesson.draft.archive',draftId:draft.id,expectedVersion:version,archived:!draft.archived}))}>{draft.archived?'Restore draft':'Archive draft'}</button></div>
    </div>;
}
