import { useState } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Bookmark, Check, ChevronRight, Clock, Heart, MessageCircle, MoreHorizontal, Pin, Plus, Send, Sparkles, Flag, Layers, FileText, Users, Play, Target, BookOpen, CheckCircle2, ShieldCheck, SearchX, Lock } from 'lucide-react';
import { useWorkspace } from '../lib/context';
import { Avatar, AvatarStack, Back, Empty, PageHeading, PersonLink, Pill, RelativeTime, dayParts, date, Modal, present } from '../components/ui';
import { Cover } from '../components/cover';
import { CreateModal } from '../components/forms';
import { progress, reputationTotals, isModerator } from '../../../../packages/domain/src/engine';
import type { Post } from '../../../../packages/contracts/src/index';
export function PostCard({ post, detail = false }: {
    post: Post;
    detail?: boolean;
}) {
    const { data, me, command, busy, toast } = useWorkspace();
    const [menu, M] = useState(false);
    const [report, R] = useState(false);
    const [reason, Reason] = useState('');
    const author = data.members.find(m => m.userId === post.authorId);
    const space = data.spaces.find(s => s.id === post.spaceId);
    const reacted = data.reactions.some(r => r.postId === post.id && r.userId === me.userId);
    const saved = data.bookmarks.some(r => r.postId === post.id && r.userId === me.userId);
    const count = data.comments.filter(c => c.postId === post.id).length;
    // A project post shows the project it names. Posts store the project's original art name for this link.
    const linked = post.cover ? data.projects.find(p => p.cover === post.cover) : undefined;
    return <article className={`post-card ${post.pinned ? 'post-pinned' : ''} ${post.hidden ? 'post-hidden' : ''}`}>
 {post.pinned && <div className="pinned-label"><Pin size={12}/> A NOTE FROM THE COMMUNITY</div>}
 <div className="post-meta">{author && author.status !== 'left' ? <Link to={`/members/${author.userId}`}><Avatar member={author}/></Link> : <Avatar member={author}/>}<div className="post-byline"><PersonLink member={author}>{author?.name}{author?.role === 'owner' && <ShieldCheck size={13} className="verified"/>}</PersonLink><span><Link to={`/spaces/${space?.id}`}>{space?.name}</Link><i>·</i><RelativeTime value={post.createdAt}/></span></div><div className="post-menu"><button aria-label="Post options" className="icon-button" onClick={() => M(!menu)} aria-expanded={menu}><MoreHorizontal size={19}/></button>{menu && <div className="dropdown"><button onClick={() => { M(false); R(true); }}><Flag size={14}/>Report privately</button>{isModerator(me) && <button onClick={() => { M(false); command({ type: 'post.moderate', postId: post.id, hidden: !post.hidden }); }}>{post.hidden ? 'Restore post' : 'Hide post'}</button>}</div>}</div></div>
 {post.hidden && <Pill tone="rose">Hidden from members</Pill>}
 {post.title && <h3>{detail ? post.title : <Link to={`/post/${post.id}`}>{post.title}</Link>}</h3>}
 <p className="post-body">{post.body}</p>
 {linked && <Link to={`/projects/${linked.id}`} className="post-visual" aria-label={`Explore ${linked.title}`}><Cover kind="project" subject={linked}/><div className="post-project-label"><span><i className="dot mint"/>WORK IN PROGRESS</span><ArrowUpRight size={21}/></div></Link>}
 <div className="post-actions"><button aria-label={reacted ? 'Remove appreciation' : 'Appreciate post'} aria-pressed={reacted} className={reacted ? 'active' : ''} disabled={busy} onClick={() => command({ type: 'post.react', postId: post.id })}><Heart size={17} fill={reacted ? 'currentColor' : 'none'}/>{data.reactions.filter(r => r.postId === post.id).length}<span>Appreciate</span></button><Link to={`/post/${post.id}`} aria-label={`Read ${count} replies`}><MessageCircle size={17}/>{count}<span>{count === 1 ? 'Reply' : 'Replies'}</span></Link><button className={`save-button ${saved ? 'active' : ''}`} aria-label={saved ? 'Unsave post' : 'Save post'} aria-pressed={saved} onClick={() => command({ type: 'post.bookmark', postId: post.id })} disabled={busy}><Bookmark size={17} fill={saved ? 'currentColor' : 'none'}/><span>{saved ? 'Saved' : 'Save'}</span></button></div>
 {report && <Modal title="Report this post" onClose={() => R(false)}><p className="modal-intro">This goes privately to the community team, not into the conversation.</p><form className="form-stack" onSubmit={async (e) => { e.preventDefault(); const r = await command({ type: 'post.report', postId: post.id, reason }); if (r)
        R(false); }}><label>What should the team know?<textarea value={reason} onChange={e => Reason(e.target.value)} rows={4} maxLength={1000} required/></label><button className="button primary" disabled={busy}>Send report</button></form></Modal>}
 </article>;
}
export function Home() {
    const { data, me } = useWorkspace();
    return <><PageHeading eyebrow="A LITTLE CONNECTION. A LITTLE MOMENTUM." title={`Good to see you, ${me.name.split(' ')[0]}.`} body="There is something good in bringing the right people together."/><div className="home-columns"><section className="main-feed"><div className="welcome-hero"><div className="hero-landscape"/><div className="hero-content"><span className="eyebrow"><span className="live-dot"/> YOUR NEXT CHAPTER STARTS HERE</span><h2>Good people.<br /><span>Remarkable things.</span></h2><p>A conversation. A new skill. That thing you have been meaning to make. Start here.</p><Link to="/missions" className="button hero-button">Find your next move <ArrowUpRight size={17}/></Link><div className="hero-people"><AvatarStack members={present(data.members).slice(1, 5)}/><span>Better, with your people.</span></div></div><span className="hero-coordinate">{data.organisation.name.toUpperCase()} / EST. 2026</span></div><Feed /></section><aside className="right-column"><Momentum /><NextLesson /><NextEvent /><MissionSpotlight /><div className="community-footer">Made for people, not algorithms.<br /><span>REUNIR <i>·</i> Community. Learning. Doing.</span></div></aside></div></>;
}
export function Feed({ spaceId, savedOnly = false }: {
    spaceId?: string;
    savedOnly?: boolean;
}) {
    const { data, me } = useWorkspace();
    const [kind, K] = useState('all');
    const [create, C] = useState(false);
    const scoped = data.posts.filter(p => (!spaceId || p.spaceId === spaceId) && (!savedOnly || data.bookmarks.some(b => b.postId === p.id && b.userId === me.userId)));
    const posts = scoped.filter(p => kind === 'all' || p.kind === kind).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.createdAt.localeCompare(a.createdAt));
    return <><button className="composer" onClick={() => C(true)}><div><Avatar member={me}/><span>Share something with your people…</span><Plus size={19}/></div><footer><span><MessageCircle size={14}/>Start a conversation</span><span><Layers size={14}/>Share your work</span><span><FileText size={14}/>Something useful</span></footer></button><div className="feed-heading"><h2>{savedOnly ? 'Worth coming back to' : 'In the conversation'}<span>{posts.length}</span></h2><span className="muted small">Latest first</span></div><div className="filter-tabs" role="group" aria-label="Filter posts">{[['all', 'Everything'], ['question', 'Questions'], ['project', 'Work in progress'], ['resource', 'Resources']].map(([k, l]) => <button key={k} onClick={() => K(k)} className={kind === k ? 'selected' : ''} aria-pressed={kind === k}>{l}</button>)}</div><div className="post-list">{posts.map(p => <PostCard key={p.id} post={p}/>)}{!posts.length && (scoped.length ? <Empty icon={SearchX} title="Nothing of this kind here yet." body="No posts match this filter. The others are still here." action={<button className="button secondary" onClick={() => K('all')}>Show everything</button>}/>
        : savedOnly ? <Empty icon={Bookmark} title="Save something good." body="Bookmark a post and find it here when you have a moment. Only you can see what you save." action={<Link to="/discussions" className="button secondary">Browse the conversation</Link>}/>
        : <Empty icon={MessageCircle} title="Room for a first thought." body="Start a conversation. You do not need to have it all figured out." action={<button className="button primary" onClick={() => C(true)}>Write the first post</button>}/>)}</div>{create && <CreateModal kind="post" spaceId={spaceId} onClose={() => C(false)}/>}</>;
}
function Momentum() { const { data, me } = useWorkspace(); const points = reputationTotals(data, me.userId); const target = Math.max(100, Math.ceil((points.total + 1) / 100) * 100); return <section className="panel momentum"><div className="panel-title"><h2>Your momentum</h2><Sparkles size={17}/></div><div className="momentum-main"><div className="progress-ring" style={{ '--progress': `${points.total / target * 100}%` } as React.CSSProperties}><span>{points.total}<small>POINTS</small></span></div><div><strong>Small steps.<br />Real progress.</strong><p>{target - points.total} to your next milestone</p><Link to="/profile">View your journey <ArrowRight size={13}/></Link></div></div><div className="points-split"><span><i className="dot blue"/>{points.learning}<small>Learn</small></span><span><i className="dot mint"/>{points.building}<small>Build</small></span><span><i className="dot amber"/>{points.contribution}<small>Contribute</small></span></div></section>; }
function NextLesson() { const { data, me } = useWorkspace(); const track = data.tracks.find(t => data.enrolments.some(e => e.userId === me.userId && e.trackId === t.id) && progress(data, me.userId, t.id).percent < 100) || data.tracks[0]; if (!track)
    return null; const p = progress(data, me.userId, track.id); return <section className="panel next-lesson"><div className="panel-title"><h2>Keep the thread going</h2><BookOpen size={16}/></div><Link to={`/learn/${track.id}`} className="next-track"><Cover small kind="track" subject={track}/><span><small>YOUR LEARNING</small><strong>{track.title}</strong></span><ChevronRight size={17}/></Link><div className="mini-progress"><span style={{ width: `${p.percent}%` }}/></div><div className="progress-caption"><span>{p.completed} of {p.total} lessons</span><strong>{p.percent}%</strong></div></section>; }
function NextEvent() { const { data } = useWorkspace(); const e = data.events.filter(e => new Date(e.startsAt).getTime() + e.duration * 60000 > Date.now()).sort((a, b) => a.startsAt.localeCompare(b.startsAt))[0]; if (!e)
    return null; const d = dayParts(e.startsAt); const members = data.rsvps.filter(r => r.eventId === e.id).map(r => data.members.find(m => m.userId === r.userId)!).filter(Boolean); return <section className="panel next-event"><div className="panel-title"><h2>A date with your people</h2><Link to="/events" aria-label="View all events"><ArrowUpRight size={17}/></Link></div><Link to={`/events/${e.id}`} className="event-mini"><div className="date-block"><small>{d.month}</small><strong>{d.day}</strong></div><div><h3>{e.title}</h3><p>{date(e.startsAt, { weekday: 'short' })} · {date(e.startsAt, { hour: '2-digit', minute: '2-digit' })} UK</p><Pill tone="mint">{e.format}</Pill></div></Link><div className="event-footer"><AvatarStack members={members}/><span>{members.length} people joining</span></div><Link to={`/events/${e.id}`} className="button secondary full">Take a look <ArrowRight size={14}/></Link></section>; }
function MissionSpotlight() { const { data } = useWorkspace(); const m = data.missions[0]; if (!m)
    return null; return <Link to={`/missions/${m.id}`} className="mission-spotlight"><div><span className="eyebrow">A LITTLE CHALLENGE</span><Target size={25}/></div><h3>{m.title}</h3><p>Learn something. Make something. Share the proof.</p><footer><Pill tone="amber">+{m.points} building points</Pill><ArrowUpRight size={18}/></footer></Link>; }
export function SpacePage() { const { id } = useParams(); const { data } = useWorkspace(); const s = data.spaces.find(s => s.id === id); if (!s)
    return <Empty icon={Lock} title="This space is not available." body="It may be private, or it may have been removed. You may need an invitation to see it." action={<Link to="/discussions" className="button secondary">Back to discussions</Link>}/>; return <><Back to="/" label="Your community"/><PageHeading eyebrow={s.visibility === 'private' ? 'PRIVATE SPACE' : 'YOUR SHARED SPACE'} title={s.name} body={s.description}/><div className="reading-width"><Feed spaceId={s.id}/></div></>; }
export function SavedPage() { return <><PageHeading eyebrow="FOR A QUIETER MOMENT" title="Keep the good stuff." body="Ideas, references and conversations you want to return to."/><div className="reading-width"><Feed savedOnly/></div></>; }
export function PostPage() { const { id } = useParams(); const { data, me, command, busy } = useWorkspace(); const [body, B] = useState(''); const p = data.posts.find(x => x.id === id); if (!p)
    return <Empty icon={MessageCircle} title="That conversation is not available." body="It may be private or have been removed." action={<Link to="/discussions" className="button secondary">Back to discussions</Link>}/>; const comments = data.comments.filter(c => c.postId === p.id); return <div className="reading-width"><Back to={`/spaces/${p.spaceId}`} label="Back to the conversation"/><PostCard post={p} detail/><section className="panel comments-panel"><h2>{comments.length} {comments.length === 1 ? 'perspective' : 'perspectives'}</h2>{comments.map(c => { const author = data.members.find(m => m.userId === c.authorId); return <div className="comment" key={c.id}><Avatar member={author} size="sm"/><div><strong>{author?.name ?? 'Community member'}</strong><RelativeTime value={c.createdAt}/><p>{c.body}</p></div></div>; })}<form className="reply-form" onSubmit={async (e) => { e.preventDefault(); if (await command({ type: 'post.comment', postId: p.id, body }))
    B(''); }}><Avatar member={me} size="sm"/><label className="sr-only" htmlFor="reply">Add your perspective</label><textarea id="reply" placeholder="Add your perspective…" value={body} onChange={e => B(e.target.value)} rows={2} maxLength={4000} required/><button aria-label="Publish reply" className="button primary" disabled={busy || !body.trim()}><Send size={17}/></button></form></section></div>; }
