import { ProjectEvidence } from './purpose';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, Clock, ExternalLink, Flag, FolderPlus, Layers, Link as LinkIcon, Plus, Send, Target, Trophy, Users, SearchX } from 'lucide-react';
import { useWorkspace } from '../lib/context';
import { Avatar, AvatarStack, Back, CheckList, Empty, Modal, PageHeading, Pill, date } from '../components/ui';
import { Cover, CoverButton } from '../components/cover';
import { ProjectTeam } from '../components/project-team';
import { CreateModal } from '../components/forms';
import { isAdmin } from '../../../../packages/domain/src/engine';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
export function MissionsPage() { const { data, me } = useWorkspace(); const [filter, F] = useState('All missions'); const [create, C] = useState(false); const missions = data.missions.filter(m => filter === 'All missions' || (filter === 'My submissions' ? data.submissions.some(s => s.missionId === m.id && s.authorId === me.userId) : m.category === filter)); return <><PageHeading eyebrow="GOOD INTENTIONS. REAL-WORLD ACTION." title="Your next move." body="Small challenges that turn what you know into something you can show." action={isAdmin(me) ? <Button variant="secondary" className="button secondary" onClick={() => C(true)}><Plus size={16}/>Create a mission</Button> : undefined}/><div className="mission-intro-strip"><Target size={24}/><span><strong>Learn it. Try it. Show it.</strong><small>Submit your proof. Get thoughtful feedback. Build a record of real progress.</small></span><Pill tone="amber">PROGRESS, NOT PERFECTION</Pill></div><div className="filter-tabs spaced" role="group" aria-label="Filter missions">{['All missions', 'My submissions', ...new Set(data.missions.map(m => m.category))].map(f => <button onClick={() => F(f)} key={f} aria-pressed={filter === f} className={filter === f ? 'selected' : ''}>{f}</button>)}</div><div className="mission-grid">{missions.map((m, i) => { const sub = data.submissions.find(s => s.missionId === m.id && s.authorId === me.userId); return <Link className="mission-card" to={`/missions/${m.id}`} key={m.id}><div className="mission-card-top"><span className={`mission-symbol tone-${['amber', 'violet', 'mint', 'blue'][i % 4]}`}><Target size={24}/></span><Pill tone={sub?.status === 'approved' ? 'mint' : sub ? 'violet' : 'neutral'}>{sub ? sub.status.replace('_', ' ') : m.difficulty}</Pill></div><span className="category-label">{m.category}</span><h2>{m.title}</h2><p>{m.brief}</p><CheckList items={m.criteria.slice(0, 2)}/><footer><span><Trophy size={15}/>+{m.points} building points</span><ArrowUpRight size={20}/></footer><div className="mission-due"><Clock size={13}/>Submit by {date(m.dueAt)}</div></Link>; })}</div>{!missions.length && (data.missions.length ? <Empty icon={SearchX} title={filter === 'My submissions' ? 'No proof submitted yet.' : 'No missions in this category.'} body={filter === 'My submissions' ? 'Missions you send proof for will collect here, with their review status.' : 'Try another category.'} action={<Button variant="secondary" className="button secondary" onClick={() => F('All missions')}>Show all missions</Button>}/>
        : <Empty icon={Target} title="No missions yet." body={isAdmin(me) ? 'Missions turn learning into something real. Set the first one for your community.' : 'The community team has not set a mission yet. When they do, it will appear here.'} action={isAdmin(me) ? <Button variant="default" className="button primary" onClick={() => C(true)}>Set the first mission</Button> : undefined}/>)}{create && <CreateModal kind="mission" onClose={() => C(false)}/>}</>; }
export function MissionPage() { const { id } = useParams(); const { data, me, command, busy } = useWorkspace(); const [body, B] = useState(''); const [url, U] = useState(''); const m = data.missions.find(m => m.id === id); if (!m)
    return <Empty icon={Target} title="Mission not available." body="This challenge may be private, or it may have been removed." action={<Link to="/missions" className="button secondary">All missions</Link>}/>; const sub = data.submissions.find(s => s.missionId === m.id && s.authorId === me.userId); const track = data.tracks.find(t => t.id === m.trackId); return <><Back to="/missions" label="All missions"/><div className="detail-layout"><article className="detail-main"><div className="mission-detail-hero"><span className="mission-symbol tone-amber"><Target size={33}/></span><span className="eyebrow">{m.category}</span><h1>{m.title}</h1><div className="detail-tags"><Pill tone="amber">+{m.points} building points</Pill><Pill>{m.difficulty}</Pill><span><Clock size={14}/>{date(m.dueAt)}</span></div></div><section className="panel prose-panel"><h2>The brief</h2><p>{m.brief}</p><h3>What good looks like</h3><CheckList items={m.criteria}/><div className="gentle-note"><SparkleNote />Your first version does not have to be perfect. It does have to be yours.</div></section>{sub && <section className={`panel submission-status status-${sub.status}`}><div className="panel-title"><h2>Your proof</h2><Pill tone={sub.status === 'approved' ? 'mint' : 'amber'}>{sub.status.replace('_', ' ')}</Pill></div><p className="preline">{sub.body}</p>{sub.url && <a className="text-link" href={sub.url} rel="noopener noreferrer" target="_blank">Open your work <ExternalLink size={14}/></a>}{sub.feedback && <div className="review-feedback"><strong>Feedback from your community team</strong><p>{sub.feedback}</p></div>}{sub.status === 'approved' && <div className="gentle-note"><CheckCircle2 size={19}/>+{m.points} building points. Your work has been recognised.</div>}</section>}{(!sub || sub.status === 'changes_requested') && <section className="panel proof-form"><h2>{sub ? 'Bring the next version.' : 'Show us what you made.'}</h2><p>A link, a little context and an honest reflection.</p><form className="form-stack" onSubmit={async (e) => { e.preventDefault(); if (await command({ type: 'mission.submit', missionId: m.id, body, url })) {
    B('');
    U('');
} }}><Label>Your proof and reflection<Textarea required rows={6} maxLength={10000} value={body} onChange={e => B(e.target.value)} placeholder="What did you make? What was your intention? What did you learn?"/></Label><Label>A link to your work <small>Optional</small><div className="input-with-icon"><LinkIcon size={16}/><Input type="url" pattern="https://.*" placeholder="https://…" value={url} onChange={e => U(e.target.value)}/></div></Label><p className="sample-note">Share only work you have permission to share. Never include private client details.</p><Button variant="default" className="button primary" disabled={busy}><Send size={16}/>{busy ? 'Submitting…' : 'Submit your proof'}</Button></form></section>}</article><aside className="detail-aside"><section className="panel"><h2>A mission, not a test.</h2><p>You will get feedback from a community administrator. Points are awarded after review, not just for clicking submit.</p><CheckList items={['Make your own work', 'Share the context', 'Learn from the feedback']}/></section>{track && <Link to={`/learn/${track.id}`} className="panel linked-track"><Cover kind="track" subject={track} small/><span className="eyebrow">A USEFUL STARTING POINT</span><h3>{track.title}</h3><p>{track.summary}</p><span className="text-link">Explore the track <ArrowUpRight size={16}/></span></Link>}<Link to={`/spaces/${data.spaces.find(s => s.slug === 'feedback')?.id || data.spaces[0]?.id}`} className="panel ask-for-help"><Users size={24}/><h3>Better with another perspective.</h3><p>Ask a question or show your work in the feedback room.</p><span className="text-link">Find your people <ArrowRight size={15}/></span></Link></aside></div></>; }
function SparkleNote() { return <Flag size={19}/>; }
export function ProjectsPage() { const { data, me } = useWorkspace(); const [filter, F] = useState('All projects'); const [create, C] = useState(false); const projects = data.projects.filter(p => filter === 'All projects' || (filter === 'My teams' ? data.projectMembers.some(m => m.projectId === p.id && m.userId === me.userId && !m.leftAt) : p.status === filter)); return <><PageHeading eyebrow="FROM ‘WHAT IF’ TO ‘WE MADE THIS’." title="Good things are taking shape." body="Works in progress. New collaborators. Ideas that deserve to exist." action={<Button variant="default" className="button primary" onClick={() => C(true)}><Plus size={17}/>Start a project</Button>}/><div className="filter-tabs spaced" role="group" aria-label="Filter projects">{[['All projects', 'All projects'], ['My teams', 'My teams'], ['idea', 'Early ideas'], ['building', 'In the making'], ['launched', 'Out in the world']].map(([v, l]) => <button key={v} aria-pressed={v === filter} className={v === filter ? 'selected' : ''} onClick={() => F(v)}>{l}</button>)}</div><div className="project-grid">{projects.map(p => { const members = data.projectMembers.filter(x => x.projectId === p.id && !x.leftAt).map(x => data.members.find(m => m.userId === x.userId)!).filter(Boolean); return <Link className="project-card" to={`/projects/${p.id}`} key={p.id}><div className="project-cover"><Cover kind="project" subject={p}/><Pill tone="dark">{p.status === 'building' ? 'In the making' : p.status === 'launched' ? 'Out in the world' : 'Early idea'}</Pill></div><div className="project-copy"><span className="category-label">{p.category}</span><h2>{p.title}<ArrowUpRight size={20}/></h2><p>{p.tagline}</p><div className="skill-tags">{p.skills.map(s => <Pill key={s}>{s}</Pill>)}</div><footer><AvatarStack members={members}/><span>{members.length} {members.length === 1 ? 'person' : 'people'} building</span></footer></div></Link>; })}</div>{!projects.length && (data.projects.length ? <Empty icon={SearchX} title={filter === 'My teams' ? 'You are not on a project team yet.' : 'No projects at this stage.'} body={filter === 'My teams' ? 'Join a project that could use your perspective, or start your own.' : 'Try another stage.'} action={<Button variant="secondary" className="button secondary" onClick={() => F('All projects')}>Show all projects</Button>}/>
        : <Empty icon={Layers} title="Make room for an idea." body="No projects yet. Start something, and others can join you." action={<Button variant="default" className="button primary" onClick={() => C(true)}>Start the first project</Button>}/>)}{create && <CreateModal kind="project" onClose={() => C(false)}/>}</>; }
export function ProjectPage() { const { id } = useParams(); const { data, me, command, busy } = useWorkspace(); const [body, B] = useState(''); const p = data.projects.find(p => p.id === id); if (!p)
    return <Empty icon={Layers} title="Project not available." body="This project may be private, or it may have been removed." action={<Link to="/projects" className="button secondary">All projects</Link>}/>; const joined = data.projectMembers.some(x => x.projectId === p.id && x.userId === me.userId && !x.leftAt); const updates = data.projectUpdates.filter(x => x.projectId === p.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return <><Back to="/projects" label="All projects"/><div className="detail-layout"><article className="detail-main"><div className="project-detail-cover"><Cover kind="project" subject={p} described/></div><PageHeading eyebrow={p.category} title={p.title} body={p.tagline} action={<CoverButton kind="project" subject={p}/>}/><section className="panel prose-panel"><h2>The idea</h2><p>{p.summary}</p><h3>Useful skills to bring</h3><div className="skill-tags">{p.skills.map(s => <Pill key={s}>{s}</Pill>)}</div></section><section className="panel work-entry"><div><span className="eyebrow">FROM IDEA TO SHARED WORK</span><h2>Make the next step clear.</h2><p>Plan tasks, share responsibility and turn finished work into reviewed contributions.</p></div><Link to={`/projects/${p.id}/work`} className="button primary">Open project workspace <ArrowUpRight size={17}/></Link></section><ProjectEvidence projectId={p.id}/><section className="panel"><div className="panel-title"><h2>Notes from the process</h2><Pill>{updates.length} updates</Pill></div>{updates.map(u => <div className="project-update" key={u.id}><Avatar member={data.members.find(m => m.userId === u.authorId)} size="sm"/><div><strong>{data.members.find(m => m.userId === u.authorId)?.name}</strong><small>{date(u.createdAt)}</small><p>{u.body}</p></div></div>)}{!updates.length && <p className="muted">The story starts with the first update.</p>}{(joined || isAdmin(me)) && <form className="form-stack" onSubmit={async (e) => { e.preventDefault(); if (await command({ type: 'project.update', projectId: p.id, body }))
    B(''); }}><Label>Share a little progress<Textarea rows={3} required maxLength={5000} value={body} onChange={e => B(e.target.value)} placeholder="What is taking shape? What could use a hand?"/></Label><Button variant="secondary" className="button secondary" disabled={busy}><Send size={15}/>Publish update</Button></form>}</section></article><aside className="detail-aside"><ProjectTeam project={p}/></aside></div></>; }
