import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Calendar, CalendarCheck, Check, Clock, Download, MapPin, Plus, Users, Video } from 'lucide-react';
import { useWorkspace } from '../lib/context';
import { Avatar, AvatarStack, Back, CheckList, Empty, PageHeading, Pill, date, dayParts } from '../components/ui';
import { CreateModal } from '../components/forms';
import { isAdmin } from '../../../../packages/domain/src/engine';
import type { CommunityEvent } from '../../../../packages/contracts/src/index';
function exportCalendar(e: CommunityEvent) { const stamp = (d: Date) => d.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z/, 'Z'); const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/\r?\n/g, '\\n').replace(/,/g, '\\,').replace(/;/g, '\\;'); const text = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//REUNIR//Community//EN', 'BEGIN:VEVENT', `UID:${e.id}@reunir.local`, `DTSTAMP:${stamp(new Date())}`, `DTSTART:${stamp(new Date(e.startsAt))}`, `DTEND:${stamp(new Date(new Date(e.startsAt).getTime() + e.duration * 60000))}`, `SUMMARY:${escape(e.title)}`, `DESCRIPTION:${escape(e.summary)}`, `LOCATION:${escape(e.location)}`, 'END:VEVENT', 'END:VCALENDAR'].join('\r\n'); const u = URL.createObjectURL(new Blob([text], { type: 'text/calendar' })); const a = document.createElement('a'); a.href = u; a.download = `reunir-${e.id}.ics`; a.click(); setTimeout(() => URL.revokeObjectURL(u), 1000); }
export function EventsPage() { const { data, me } = useWorkspace(); const [filter, F] = useState('Upcoming'); const [create, C] = useState(false); const events = [...data.events].filter(e => (new Date(e.startsAt).getTime() + e.duration * 60000 > Date.now()) && (filter !== 'I am going' || data.rsvps.some(r => r.eventId === e.id && r.userId === me.userId))).sort((a, b) => a.startsAt.localeCompare(b.startsAt)); return <><PageHeading eyebrow="MAKE TIME FOR YOUR PEOPLE." title="A good reason to show up." body="Workshops, honest critiques and a little space to make things together." action={isAdmin(me) ? <button className="button secondary" onClick={() => C(true)}><Plus size={16}/>Create an event</button> : undefined}/><div className="filter-tabs spaced">{['Upcoming', 'I am going'].map(f => <button key={f} className={filter === f ? 'selected' : ''} onClick={() => F(f)}>{f}</button>)}</div><div className="events-list">{events.map((e, i) => { const d = dayParts(e.startsAt); const people = data.rsvps.filter(r => r.eventId === e.id).map(r => data.members.find(m => m.userId === r.userId)!).filter(Boolean); const going = people.some(m => m.userId === me.userId); return <Link to={`/events/${e.id}`} className="event-card" key={e.id}><div className={`event-art event-art-${i % 3}`}><span>{d.month}</span><strong>{d.day}</strong><small>{date(e.startsAt, { weekday: 'long' })}</small><i /><Video size={26}/></div><div className="event-card-content"><div className="detail-tags"><Pill tone={i % 2 ? 'violet' : 'mint'}>{e.format}</Pill>{going && <Pill tone="mint"><Check size={12}/>You are going</Pill>}</div><h2>{e.title}</h2><p>{e.summary}</p><div className="event-time"><span><Clock size={14}/>{date(e.startsAt, { hour: '2-digit', minute: '2-digit' })} UK · {e.duration} min</span><span><MapPin size={14}/>{e.location}</span></div><footer><AvatarStack members={people}/><span>{people.length} joining</span><ArrowUpRight size={20}/></footer></div></Link>; })}</div>{!events.length && (filter === 'I am going' ? <Empty icon={CalendarCheck} title="Nothing in your diary yet." body="Events you say you are going to will appear here." action={<button className="button secondary" onClick={() => F('Upcoming')}>See upcoming events</button>}/>
        : <Empty icon={Calendar} title="Keep a little space in the diary." body={isAdmin(me) ? 'No upcoming events. Make time for your people.' : 'No upcoming events yet. Your next gathering will appear here.'} action={isAdmin(me) ? <button className="button primary" onClick={() => C(true)}>Plan the next event</button> : undefined}/>)}{create && <CreateModal kind="event" onClose={() => C(false)}/>}</>; }
export function EventPage() { const { id } = useParams(); const { data, me, command, busy } = useWorkspace(); const e = data.events.find(e => e.id === id); if (!e)
    return <Empty icon={Calendar} title="Event not available." body="This gathering may be private, or it may have been removed." action={<Link to="/events" className="button secondary">All events</Link>}/>; const going = data.rsvps.some(r => r.eventId === e.id && r.userId === me.userId); const people = data.rsvps.filter(r => r.eventId === e.id).map(r => data.members.find(m => m.userId === r.userId)!).filter(Boolean); const d = dayParts(e.startsAt); return <><Back to="/events" label="All events"/><div className="detail-layout"><article className="detail-main"><div className="event-detail-hero"><div className="date-block"><small>{d.month}</small><strong>{d.day}</strong></div><span className="eyebrow">{e.format} · {data.organisation.name.toUpperCase()}</span><h1>{e.title}</h1><p>{date(e.startsAt, { weekday: 'long', day: 'numeric', month: 'long' })} · {date(e.startsAt, { hour: '2-digit', minute: '2-digit' })} UK time</p></div><section className="panel prose-panel"><h2>Make a little time.</h2><p>{e.summary}</p><CheckList items={['Bring a question, an idea or your work in progress.', 'Give others room to share their perspective.', 'Leave with one useful next step.']}/><div className="teacher-row"><Avatar member={data.members.find(m => m.userId === e.hostId)}/><span>Hosted by <strong>{data.members.find(m => m.userId === e.hostId)?.name}</strong></span></div></section></article><aside className="detail-aside"><section className="panel event-join"><Pill tone="mint">{going ? 'YOU ARE ON THE LIST' : 'A SPACE FOR YOU'}</Pill><h2>Show up as you are.</h2><p><Clock size={16}/>{e.duration} minutes, together</p><p><MapPin size={16}/>{e.location}</p><button className={`button ${going ? 'secondary' : 'primary'} full`} disabled={busy || new Date(e.startsAt).getTime() + e.duration * 60000 < Date.now()} onClick={() => command({ type: 'event.rsvp', eventId: e.id })}>{going ? <Check size={17}/> : <Plus size={17}/>}{going ? 'Cancel my RSVP' : 'Count me in'}</button><button className="button ghost full" onClick={() => exportCalendar(e)}><Download size={15}/>Add to calendar</button>{e.meetingUrl ? <a className="button secondary full" href={e.meetingUrl} target="_blank" rel="noopener noreferrer">Open meeting <ArrowUpRight size={15}/></a> : <small className="sample-note">The host has not added a meeting link yet. Calendar export and RSVP are available.</small>}</section><section className="panel"><h2>{people.length} people joining</h2><div className="team-list">{people.map(m => <Link key={m.id} to={`/members/${m.userId}`}><Avatar member={m} size="sm"/><span><strong>{m.name}</strong><small>{m.headline}</small></span></Link>)}</div></section></aside></div></>; }
