import {useState,useEffect,useRef} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useParams,useNavigate,Link} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,MessageCircle,Plus,Send,Shield,Flag,Lock,Search,RefreshCw,Users,Mail,SearchX,UserRound} from 'lucide-react';
import {GroupAvatar,GroupPeopleDialog,NewGroupDialog} from './message-groups';
import {InlineError,Loading} from '../components/states';
import {useWorkspace} from '../lib/context';
import {messageRequest} from '../lib/messaging';
import {displayError} from '../lib/data';
import {Avatar,Empty,Modal,PageHeading,Pill} from '../components/ui';
import {newId} from '../../../../packages/contracts/src/index';
import type {Conversation,ConversationPage,MessagePage,DirectMessage,MessageReport} from '../../../../packages/contracts/src/messaging';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { useConfirm } from '../components/confirm';
export function MessagesPage(){
 const {slug,userId,data,toast,mode}=useWorkspace(),confirm=useConfirm(),{id}=useParams(),navigate=useNavigate(),cache=useQueryClient();
 const [start,Start]=useState(false),[grouping,Grouping]=useState(false),[people,People]=useState(false),[search,SearchText]=useState(''),[who,Who]=useState(''),[body,Body]=useState(''),[busy,Busy]=useState(false),[report,Report]=useState<string|null>(null),[reason,Reason]=useState(''),[older,Older]=useState<DirectMessage[]>([]),[olderCursor,OlderCursor]=useState<string|null|undefined>();
 const retry=useRef<{body:string;key:string;id:string}|undefined>(undefined),bottom=useRef<HTMLDivElement|null>(null);
 const query=useQuery({queryKey:['messages',slug,userId,'threads'],queryFn:()=>messageRequest<ConversationPage>(slug,userId,'conversations'),refetchInterval:mode==='live'?15000:false});
 const messages=useQuery({queryKey:['messages',slug,userId,id],queryFn:()=>messageRequest<MessagePage>(slug,userId,`conversations/${id}/messages`),enabled:!!id,refetchInterval:mode==='live'?10000:false});
 const detail=useQuery({queryKey:['messages',slug,userId,'detail',id],queryFn:()=>messageRequest<Conversation>(slug,userId,`conversations/${id}`),enabled:!!id,refetchInterval:mode==='live'?15000:false});
 const [moreThreads,MoreThreads]=useState<Conversation[]>([]),[threadCursor,ThreadCursor]=useState<string|null|undefined>();
 const threads=[...(query.data?.items||[]),...moreThreads].filter((t,i,a)=>a.findIndex(x=>x.id===t.id)===i);
 const nextThreadCursor=threadCursor===undefined?query.data?.nextCursor:threadCursor;
 const t=detail.data||threads.find(t=>t.id===id),isGroup=t?.kind==='group',peer=isGroup?undefined:t?.participantIds.find(p=>p!==userId),member=data.members.find(m=>m.userId===peer),former=member?.status==='left';
 const nameOf=(id:string)=>data.members.find(m=>m.userId===id)?.name||'Former member';
 /** A group is found by its name or anyone in it; a direct thread by the other person. */
 const label=(c:Conversation)=>c.kind==='group'?[c.title||'',...c.participantIds.map(nameOf)].join(' '):nameOf(c.participantIds.find(p=>p!==userId)||'');
 const found=threads.filter(t=>!search||label(t).toLowerCase().includes(search.toLowerCase()));
 const candidates=data.members.filter(m=>m.userId!==userId&&m.status==='active'&&(m.name+' '+m.skills.join(' ')).toLowerCase().includes(who.toLowerCase()));
 const refresh=()=>cache.invalidateQueries({queryKey:['messages',slug,userId]});
 useEffect(()=>{Body('');People(false);Older([]);OlderCursor(undefined);retry.current=undefined;},[id,slug,userId]);
 const last=messages.data?.items.at(-1);
 useEffect(()=>{if(id&&last){bottom.current?.scrollIntoView({block:'nearest'});messageRequest(slug,userId,`conversations/${id}/read`,{messageId:last.id}).then(()=>cache.invalidateQueries({queryKey:['messages',slug,userId,'threads']})).catch(()=>{});}},[id,last?.id,slug,userId]);
 async function act(fn:()=>Promise<unknown>,notice?:string){Busy(true);try{await fn();await refresh();if(notice)toast(notice);}catch(e){toast(displayError(e),'error');}finally{Busy(false);}}
 async function send(){if(!body.trim()||!id||busy)return;const content=body.trim();if(!retry.current||retry.current.body!==content||retry.current.id!==id)retry.current={body:content,key:newId(),id};Busy(true);try{await messageRequest(slug,userId,`conversations/${id}/messages`,{body:content},retry.current.key);Body('');retry.current=undefined;await refresh();}catch(e){toast(displayError(e)+' Your draft is still here.','error');}finally{Busy(false);}}
 const all=[...older,...(messages.data?.items||[])].filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i);
 const cursor=olderCursor===undefined?messages.data?.nextCursor:olderCursor;
 return <><PageHeading eyebrow="GOOD WORK STARTS WITH A CONVERSATION." title="A little closer." body="Make an introduction. Ask for a hand. Keep a good idea moving." action={<div className="heading-actions"><Button variant="secondary" className="button secondary" onClick={()=>Grouping(true)}><Users size={16}/>New group</Button><Button variant="default" className="button primary" onClick={()=>Start(true)}><Plus size={16}/>New message</Button></div>}/>
 <div className={`inbox-layout ${id?'thread-open':''}`}>
 <aside className="inbox-list" aria-label="Your conversations"><div className="inbox-list-heading"><strong>Messages</strong><Pill tone="mint">Private</Pill></div><Label className="inbox-search"><Search size={16}/><Input aria-label="Find a conversation" placeholder="Find a person or group…" value={search} onChange={e=>SearchText(e.target.value)}/></Label>
 {query.error?<InlineError error={query.error} onRetry={()=>query.refetch()}/>:query.isPending?<Loading label="Opening your inbox…" lines={4}/>:found.map(t=>{const p=t.kind==='group'?undefined:data.members.find(m=>m.userId===t.participantIds.find(p=>p!==userId));return <button key={t.id} className={`inbox-person ${id===t.id?'selected':''}`} aria-current={id===t.id?'true':undefined} onClick={()=>navigate('/messages/'+t.id)}>{t.kind==='group'?<GroupAvatar/>:<Avatar member={p}/>}<span><strong>{t.kind==='group'?t.title:p?.name||'Former member'}</strong><small>{t.blocked?'Messaging paused':t.lastBody||'Say hello.'}</small></span>{t.unread>0&&<b className="unread-count">{t.unread}<span className="sr-only"> unread {t.unread===1?'message':'messages'}</span></b>}</button>;})}
 {!query.isPending&&!query.error&&!threads.length&&<Empty icon={Mail} title="Your next collaborator?" body="No conversations yet. Start with a thoughtful hello. Only the people in a conversation can read it." action={<Button variant="secondary" className="button secondary" onClick={()=>Start(true)}>Write a first message</Button>}/>}{!query.isPending&&!query.error&&threads.length>0&&!found.length&&<Empty icon={SearchX} title="No conversation with that name." body="Only people and groups you have messaged are listed here." action={<Button variant="secondary" className="button secondary" onClick={()=>SearchText('')}>Clear the search</Button>}/>}<p className="inbox-disclosure"><Lock size={13}/>Only participants can open a conversation.</p>
 {nextThreadCursor&&<Button variant="secondary" className="button secondary" disabled={busy} aria-busy={busy||undefined} onClick={async()=>{Busy(true);try{const more=await messageRequest<ConversationPage>(slug,userId,'conversations?before='+encodeURIComponent(nextThreadCursor));MoreThreads(x=>[...x,...more.items]);ThreadCursor(more.nextCursor);}catch(e){toast(displayError(e),'error');}finally{Busy(false);}}}>More conversations</Button>}
 </aside>
 <section className="inbox-thread" aria-label="Conversation">
 {!id?<div className="inbox-welcome"><span className="inbox-welcome-icon"><MessageCircle size={34}/></span><h2>Some things begin<br/>with a simple hello.</h2><p>Your people are right here. Start a conversation about what you’re working towards.</p><Button variant="secondary" className="button secondary" onClick={()=>Start(true)}>Find your next collaborator <ArrowUpRight size={16}/></Button></div>:<>
 <header className="thread-heading"><button className="icon-button inbox-back" aria-label="Back to inbox" onClick={()=>navigate('/messages')}><ArrowLeft size={19}/></button>{isGroup?<GroupAvatar/>:<Avatar member={member}/>}<span><strong>{isGroup?t?.title:member?.name||'Community conversation'}</strong><small>{isGroup?`${t?.participantIds.length} people · only people in this group can read it`:former?'This account was deleted. Their messages stay here for you.':member?.headline||'Only the two participants can read this thread'}</small></span>{isGroup&&<Button variant="secondary" size="sm" className="button secondary compact" onClick={()=>People(true)}><Users size={14}/>People</Button>}{member&&!former&&<Link className="icon-button" aria-label="View member profile" to={'/members/'+member.userId}><ArrowUpRight size={18}/></Link>}<button className="icon-button" aria-label="Refresh messages" onClick={()=>refresh()}><RefreshCw size={16}/></button>{peer&&!former&&<Button variant="secondary" size="sm" className="button secondary compact" disabled={busy} onClick={async()=>{if(t?.blockedByMe||await confirm({title:'Block private messaging with this member?',body:'Your existing conversation stays available.',confirmText:'Block'}))act(()=>messageRequest(slug,userId,'member-blocks',{userId:peer,blocked:!t?.blockedByMe}),t?.blockedByMe?'Messaging unblocked.':'Member blocked from messaging you.');}}><Shield size={14}/>{t?.blockedByMe?'Unblock':'Block'}</Button>}</header>
 <div className="thread-body">{messages.error?<Empty icon={Lock} title="This conversation is not available." body={displayError(messages.error)} action={<Button variant="secondary" className="button secondary" onClick={()=>messages.refetch()}>Try again</Button>}/>:<>{cursor&&<Button variant="secondary" size="sm" className="button secondary compact" disabled={busy} onClick={()=>act(async()=>{const more=await messageRequest<MessagePage>(slug,userId,`conversations/${id}/messages?before=${encodeURIComponent(cursor)}`);Older(x=>[...more.items,...x]);OlderCursor(more.nextCursor);})}>Earlier messages</Button>}<p className="thread-privacy"><Lock size={12}/>{isGroup?'Private to the people in this group.':'Private to this conversation.'} Reporting shares only the selected message with moderators.</p>{all.map(m=><div key={m.id} className={`message-row ${m.senderId===userId?'mine':'theirs'}`}><div className="message-bubble">{isGroup&&m.senderId!==userId&&<span className="message-sender">{nameOf(m.senderId)}</span>}<p>{m.body}</p><div className="message-meta"><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time>{m.senderId!==userId&&<button aria-label="Report this message" className="icon-button" onClick={()=>{Report(m.id);Reason('');}}><Flag size={12}/></button>}</div></div></div>)}{messages.isPending&&<Loading label="Opening the conversation…"/>}{!all.length&&!messages.isPending&&<Empty icon={MessageCircle} title="Say something worth starting." body="A question, an introduction or an offer to help."/>}<div ref={bottom}/></>}</div>
 {former?<p className="message-composer former-thread" role="note">You can read this conversation, but you cannot reply to a former member.</p>:<form className="message-composer" onSubmit={e=>{e.preventDefault();send();}}><Label className="sr-only" htmlFor="message-body">Your message</Label><Textarea id="message-body" maxLength={4000} rows={2} placeholder={!isGroup&&t?.blocked?'Messaging is paused.':'A thoughtful message…'} disabled={!isGroup&&(t?.blocked||!member)||!!messages.error} value={body} onChange={e=>Body(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();send();}}}/><div><small>{body.length}/4000 · ⌘ / Ctrl + Enter to send</small><Button variant="default" className="button primary" disabled={busy||!body.trim()||!isGroup&&(t?.blocked||!member)||!!messages.error}><Send size={15}/>{busy?'Sending…':'Send message'}</Button></div></form>}
 </>}
 </section></div>
 {start&&<Modal title="Start with hello." onClose={()=>{Start(false);Who('');}}><p>Connect with someone in {data.organisation.name}.</p><Label className="inbox-search"><Search size={16}/><Input autoFocus aria-label="Find a member to message" value={who} onChange={e=>Who(e.target.value)} placeholder="Name or skill…"/></Label><div className="new-message-people">{!candidates.length&&<Empty icon={UserRound} title="No one matches that name." body="Try a first name or a skill. Only active members can be messaged."/>}{candidates.map(m=><button className="inbox-person" key={m.id} disabled={busy} onClick={()=>act(async()=>{const t=await messageRequest<{id:string}>(slug,userId,'conversations',{userId:m.userId});Start(false);Who('');navigate('/messages/'+t.id);})}><Avatar member={m}/><span><strong>{m.name}</strong><small>{m.headline}</small></span><ArrowUpRight size={17}/></button>)}</div></Modal>}
 {grouping&&<NewGroupDialog onClose={()=>Grouping(false)} onCreated={g=>{Grouping(false);refresh();navigate('/messages/'+g);}}/>}
 {people&&t&&isGroup&&<GroupPeopleDialog thread={t} onClose={()=>People(false)} onChanged={refresh} onLeft={()=>{People(false);navigate('/messages');}}/>}
 {report&&<Modal title="Report this message" onClose={()=>{Report(null);Reason('');}}><p>Only this message, your reason and the people involved will be shared with community moderators. This does not give them access to the conversation.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();act(async()=>{await messageRequest(slug,userId,`conversations/${id}/messages/${report}/report`,{reason});Report(null);Reason('');},'The selected message has been reported.');}}><Label>What needs attention?<Textarea minLength={5} maxLength={1000} required rows={4} value={reason} onChange={e=>Reason(e.target.value)}/></Label><Button variant="default" className="button primary" disabled={busy||reason.trim().length<5}>Share with moderators</Button></form></Modal>}
 </>;
}
export function MessageReportQueue(){const {slug,userId,data,toast}=useWorkspace();const q=useQuery({queryKey:['message-reports',slug,userId],queryFn:()=>messageRequest<MessageReport[]>(slug,userId,'message-reports'),staleTime:0});return <section className="panel"><h2>Reported private messages</h2><p className="muted">A member has chosen to share these specific messages. Their inbox remains private. When a report is closed, the member who made it is told, and can ask once for another moderator to look again.</p>{q.isPending&&<Loading label="Loading reported messages…" lines={2}/>}{q.error?<InlineError error={q.error} onRetry={()=>q.refetch()}/>:q.data?.filter(r=>r.status==='open').map(r=>{const first=r.firstReviewedBy===userId;return <div className="message-report" key={r.id}><Pill tone="amber">{r.secondLook?'Second look':'Member report'}</Pill><p className="preline">{r.reportedBody}</p><small>Sent by {data.members.find(m=>m.userId===r.senderId)?.name||'a former member'} · Reported by {data.members.find(m=>m.userId===r.reporterId)?.name||'a former member'}</small><p><strong>Reason:</strong> {r.reason}</p>{r.secondLook&&<p className="preline"><strong>Why they asked again:</strong> {r.secondLook}</p>}{first&&<p className="sample-note">You closed this report the first time, so another moderator takes the second look.</p>}<Button variant="secondary" className="button secondary" disabled={r.senderId===userId||r.reporterId===userId||first} onClick={async()=>{try{await messageRequest(slug,userId,`message-reports/${r.id}/resolve`,{});q.refetch();toast(r.secondLook?'Report looked at again and closed.':'Report reviewed and resolved.');}catch(e){toast(displayError(e),'error');}}}>{r.secondLook?'Close after second look':'Resolve report'}</Button></div>;})}{!q.isPending&&!q.error&&!q.data?.some(r=>r.status==='open')&&<p>No private-message reports need review.</p>}</section>;}
