import {useState,useEffect,useRef} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useParams,useNavigate,Link} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,MessageCircle,Plus,Send,Shield,Flag,Lock,Search,RefreshCw,Mail,SearchX,UserRound} from 'lucide-react';
import {InlineError,Loading} from '../components/states';
import {useWorkspace} from '../lib/context';
import {messageRequest} from '../lib/messaging';
import {displayError} from '../lib/data';
import {Avatar,Empty,Modal,PageHeading,Pill} from '../components/ui';
import {newId} from '../../../../packages/contracts/src/index';
import type {Conversation,ConversationPage,MessagePage,DirectMessage,MessageReport} from '../../../../packages/contracts/src/messaging';
export function MessagesPage(){
 const {slug,userId,data,toast,mode}=useWorkspace(),{id}=useParams(),navigate=useNavigate(),cache=useQueryClient();
 const [start,Start]=useState(false),[search,SearchText]=useState(''),[body,Body]=useState(''),[busy,Busy]=useState(false),[report,Report]=useState<string|null>(null),[reason,Reason]=useState(''),[older,Older]=useState<DirectMessage[]>([]),[olderCursor,OlderCursor]=useState<string|null|undefined>();
 const retry=useRef<{body:string;key:string;id:string}|undefined>(undefined),bottom=useRef<HTMLDivElement|null>(null);
 const query=useQuery({queryKey:['messages',slug,userId,'threads'],queryFn:()=>messageRequest<ConversationPage>(slug,userId,'conversations'),refetchInterval:mode==='live'?15000:false});
 const messages=useQuery({queryKey:['messages',slug,userId,id],queryFn:()=>messageRequest<MessagePage>(slug,userId,`conversations/${id}/messages`),enabled:!!id,refetchInterval:mode==='live'?10000:false});
 const detail=useQuery({queryKey:['messages',slug,userId,'detail',id],queryFn:()=>messageRequest<Conversation>(slug,userId,`conversations/${id}`),enabled:!!id,refetchInterval:mode==='live'?15000:false});
 const [moreThreads,MoreThreads]=useState<Conversation[]>([]),[threadCursor,ThreadCursor]=useState<string|null|undefined>();
 const threads=[...(query.data?.items||[]),...moreThreads].filter((t,i,a)=>a.findIndex(x=>x.id===t.id)===i);
 const nextThreadCursor=threadCursor===undefined?query.data?.nextCursor:threadCursor;
 const found=threads.filter(t=>{const peer=data.members.find(m=>m.userId===t.participantIds.find(p=>p!==userId));return !search||peer?.name.toLowerCase().includes(search.toLowerCase());});
 const people=data.members.filter(m=>m.userId!==userId&&m.status==='active'&&(m.name+' '+m.skills.join(' ')).toLowerCase().includes(search.toLowerCase()));
 const t=detail.data||threads.find(t=>t.id===id),peer=t?.participantIds.find(p=>p!==userId),member=data.members.find(m=>m.userId===peer),former=member?.status==='left';
 const refresh=()=>cache.invalidateQueries({queryKey:['messages',slug,userId]});
 useEffect(()=>{Body('');Older([]);OlderCursor(undefined);retry.current=undefined;},[id,slug,userId]);
 const last=messages.data?.items.at(-1);
 useEffect(()=>{if(id&&last){bottom.current?.scrollIntoView({block:'nearest'});messageRequest(slug,userId,`conversations/${id}/read`,{messageId:last.id}).then(()=>cache.invalidateQueries({queryKey:['messages',slug,userId,'threads']})).catch(()=>{});}},[id,last?.id,slug,userId]);
 async function act(fn:()=>Promise<unknown>,notice?:string){Busy(true);try{await fn();await refresh();if(notice)toast(notice);}catch(e){toast(displayError(e),'error');}finally{Busy(false);}}
 async function send(){if(!body.trim()||!id||busy)return;const content=body.trim();if(!retry.current||retry.current.body!==content||retry.current.id!==id)retry.current={body:content,key:newId(),id};Busy(true);try{await messageRequest(slug,userId,`conversations/${id}/messages`,{body:content},retry.current.key);Body('');retry.current=undefined;await refresh();}catch(e){toast(displayError(e)+' Your draft is still here.','error');}finally{Busy(false);}}
 const all=[...older,...(messages.data?.items||[])].filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i);
 const cursor=olderCursor===undefined?messages.data?.nextCursor:olderCursor;
 return <><PageHeading eyebrow="GOOD WORK STARTS WITH A CONVERSATION." title="A little closer." body="Make an introduction. Ask for a hand. Keep a good idea moving." action={<button className="button primary" onClick={()=>Start(true)}><Plus size={16}/>New message</button>}/>
 <div className={`inbox-layout ${id?'thread-open':''}`}>
 <aside className="inbox-list" aria-label="Your conversations"><div className="inbox-list-heading"><strong>Messages</strong><Pill tone="mint">Private</Pill></div><label className="inbox-search"><Search size={16}/><input aria-label="Find a conversation" placeholder="Find a person…" value={search} onChange={e=>SearchText(e.target.value)}/></label>
 {query.error?<InlineError error={query.error} onRetry={()=>query.refetch()}/>:query.isPending?<Loading label="Opening your inbox…" lines={4}/>:found.map(t=>{const p=data.members.find(m=>m.userId===t.participantIds.find(p=>p!==userId));return <button key={t.id} className={`inbox-person ${id===t.id?'selected':''}`} onClick={()=>navigate('/messages/'+t.id)}><Avatar member={p}/><span><strong>{p?.name||'Former member'}</strong><small>{t.blocked?'Messaging paused':t.lastBody||'Say hello.'}</small></span>{t.unread>0&&<b className="unread-count">{t.unread}</b>}</button>;})}
 {!query.isPending&&!query.error&&!threads.length&&<Empty icon={Mail} title="Your next collaborator?" body="No conversations yet. Start with a thoughtful hello. Only the two of you can read it." action={<button className="button secondary" onClick={()=>Start(true)}>Write a first message</button>}/>}{!query.isPending&&!query.error&&threads.length>0&&!found.length&&<Empty icon={SearchX} title="No conversation with that name." body="Only people you have messaged are listed here." action={<button className="button secondary" onClick={()=>SearchText('')}>Clear the search</button>}/>}<p className="inbox-disclosure"><Lock size={13}/>Only participants can open a conversation.</p>
 {nextThreadCursor&&<button className="button secondary" disabled={busy} aria-busy={busy||undefined} onClick={async()=>{Busy(true);try{const more=await messageRequest<ConversationPage>(slug,userId,'conversations?before='+encodeURIComponent(nextThreadCursor));MoreThreads(x=>[...x,...more.items]);ThreadCursor(more.nextCursor);}catch(e){toast(displayError(e),'error');}finally{Busy(false);}}}>More conversations</button>}
 </aside>
 <section className="inbox-thread" aria-label="Conversation">
 {!id?<div className="inbox-welcome"><span className="inbox-welcome-icon"><MessageCircle size={34}/></span><h2>Some things begin<br/>with a simple hello.</h2><p>Your people are right here. Start a conversation about what you’re working towards.</p><button className="button secondary" onClick={()=>Start(true)}>Find your next collaborator <ArrowUpRight size={16}/></button></div>:<>
 <header className="thread-heading"><button className="icon-button inbox-back" aria-label="Back to inbox" onClick={()=>navigate('/messages')}><ArrowLeft size={19}/></button><Avatar member={member}/><span><strong>{member?.name||'Community conversation'}</strong><small>{former?'This account was deleted. Their messages stay here for you.':member?.headline||'Only the two participants can read this thread'}</small></span>{member&&!former&&<Link className="icon-button" aria-label="View member profile" to={'/members/'+member.userId}><ArrowUpRight size={18}/></Link>}<button className="icon-button" aria-label="Refresh messages" onClick={()=>refresh()}><RefreshCw size={16}/></button>{peer&&!former&&<button className="button secondary compact" disabled={busy} onClick={()=>{if(t?.blockedByMe||window.confirm('Block private messaging with this member? Your existing conversation stays available.'))act(()=>messageRequest(slug,userId,'member-blocks',{userId:peer,blocked:!t?.blockedByMe}),t?.blockedByMe?'Messaging unblocked.':'Member blocked from messaging you.');}}><Shield size={14}/>{t?.blockedByMe?'Unblock':'Block'}</button>}</header>
 <div className="thread-body">{messages.error?<Empty icon={Lock} title="This conversation is not available." body={displayError(messages.error)} action={<button className="button secondary" onClick={()=>messages.refetch()}>Try again</button>}/>:<>{cursor&&<button className="button secondary compact" disabled={busy} onClick={()=>act(async()=>{const more=await messageRequest<MessagePage>(slug,userId,`conversations/${id}/messages?before=${encodeURIComponent(cursor)}`);Older(x=>[...more.items,...x]);OlderCursor(more.nextCursor);})}>Earlier messages</button>}<p className="thread-privacy"><Lock size={12}/>Private to this conversation. Reporting shares only the selected message with moderators.</p>{all.map(m=><div key={m.id} className={`message-row ${m.senderId===userId?'mine':'theirs'}`}><div className="message-bubble"><p>{m.body}</p><div className="message-meta"><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time>{m.senderId!==userId&&<button aria-label="Report this message" className="icon-button" onClick={()=>{Report(m.id);Reason('');}}><Flag size={12}/></button>}</div></div></div>)}{messages.isPending&&<Loading label="Opening the conversation…"/>}{!all.length&&!messages.isPending&&<Empty icon={MessageCircle} title="Say something worth starting." body="A question, an introduction or an offer to help."/>}<div ref={bottom}/></>}</div>
 {former?<p className="message-composer former-thread" role="note">You can read this conversation, but you cannot reply to a former member.</p>:<form className="message-composer" onSubmit={e=>{e.preventDefault();send();}}><label className="sr-only" htmlFor="message-body">Your message</label><textarea id="message-body" maxLength={4000} rows={2} placeholder={t?.blocked?'Messaging is paused.':'A thoughtful message…'} disabled={t?.blocked||!member||!!messages.error} value={body} onChange={e=>Body(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();send();}}}/><div><small>{body.length}/4000 · ⌘ / Ctrl + Enter to send</small><button className="button primary" disabled={busy||!body.trim()||t?.blocked||!member||!!messages.error}><Send size={15}/>{busy?'Sending…':'Send message'}</button></div></form>}
 </>}
 </section></div>
 {start&&<Modal title="Start with hello." onClose={()=>Start(false)}><p>Connect with someone in {data.organisation.name}.</p><label className="inbox-search"><Search size={16}/><input autoFocus aria-label="Find a member to message" value={search} onChange={e=>SearchText(e.target.value)} placeholder="Name or skill…"/></label><div className="new-message-people">{!people.length&&<Empty icon={UserRound} title="No one matches that name." body="Try a first name or a skill. Only active members can be messaged."/>}{people.map(m=><button className="inbox-person" key={m.id} disabled={busy} onClick={()=>act(async()=>{const t=await messageRequest<{id:string}>(slug,userId,'conversations',{userId:m.userId});Start(false);SearchText('');navigate('/messages/'+t.id);})}><Avatar member={m}/><span><strong>{m.name}</strong><small>{m.headline}</small></span><ArrowUpRight size={17}/></button>)}</div></Modal>}
 {report&&<Modal title="Report this message" onClose={()=>Report(null)}><p>Only this message, your reason and the people involved will be shared with community moderators. This does not give them access to the conversation.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();act(async()=>{await messageRequest(slug,userId,`conversations/${id}/messages/${report}/report`,{reason});Report(null);},'The selected message has been reported.');}}><label>What needs attention?<textarea minLength={5} maxLength={1000} required rows={4} value={reason} onChange={e=>Reason(e.target.value)}/></label><button className="button primary" disabled={busy||reason.trim().length<5}>Share with moderators</button></form></Modal>}
 </>;
}
export function MessageReportQueue(){const {slug,userId,data,toast}=useWorkspace();const q=useQuery({queryKey:['message-reports',slug,userId],queryFn:()=>messageRequest<MessageReport[]>(slug,userId,'message-reports')});return <section className="panel"><h2>Reported private messages</h2><p className="muted">A member has chosen to share these specific messages. Their inbox remains private.</p>{q.isPending&&<Loading label="Loading reported messages…" lines={2}/>}{q.error?<InlineError error={q.error} onRetry={()=>q.refetch()}/>:q.data?.filter(r=>r.status==='open').map(r=><div className="message-report" key={r.id}><Pill tone="amber">Member report</Pill><p className="preline">{r.reportedBody}</p><small>Sent by {data.members.find(m=>m.userId===r.senderId)?.name||'a former member'} · Reported by {data.members.find(m=>m.userId===r.reporterId)?.name||'a former member'}</small><p><strong>Reason:</strong> {r.reason}</p><button className="button secondary" disabled={r.senderId===userId||r.reporterId===userId} onClick={async()=>{try{await messageRequest(slug,userId,`message-reports/${r.id}/resolve`,{});q.refetch();toast('Report reviewed and resolved.');}catch(e){toast(displayError(e),'error');}}}>Resolve report</button></div>)}{!q.isPending&&!q.error&&!q.data?.some(r=>r.status==='open')&&<p>No private-message reports need review.</p>}</section>;}
