import { Button } from '../components/ui/button';
import mountainImage from '../assets/community-mountain.jpg';
import type { CSSProperties } from 'react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CalendarDays, ArrowRight, ArrowUpRight, BookOpen, Check, CheckCircle2, Compass, Flag, Layers, Lock, Plus, Route as RouteIcon, ShieldCheck, Target, Users } from 'lucide-react';
import { useWorkspace } from '../lib/context';
import { Avatar, AvatarStack, Back, Empty, Modal, PageHeading, Pill, dayParts, date, present } from '../components/ui';
import { Cover } from '../components/cover';
import { EvidenceHistory } from '../components/evidence-history';
import { ContributionCredits, CreditedOn } from '../components/credits';
import { PostCard, Feed } from './community';
import { isAdmin } from '../../../../packages/domain/src/engine';
import { pathProgress } from '../../../../packages/domain/src/purpose';
import type { Purpose, Path, MemberGoal, Contribution, Outcome, OutputKind, Id } from '../../../../packages/contracts/src/index';

const kindLabel = {become:'Become',build:'Build',achieve:'Achieve'};
const kindTone = {become:'violet',build:'mint',achieve:'amber'};
const kindIcon = {become:Compass,build:Layers,achieve:Flag};
const read = (f:FormData,k:string) => String(f.get(k)||'');
const idOrNull = (f:FormData,k:string) => read(f,k)||null;
function SectionTitle({title,link,to,aside}:{title:string;link?:string;to?:string;aside?:ReactNode}) { return <div className="purpose-section-title"><h2>{title}</h2>{to&&<Link to={to}>{link||'Explore'} <ArrowUpRight size={16}/></Link>}{aside}</div>; }

export function PurposeHome() {
 const {data,me,mode}=useWorkspace(); const [goal,G]=useState(false);
 const purposes=data.purposes.filter(p=>p.status==='active');
 const personal=data.memberGoals.find(g=>g.userId===me.userId&&g.status==='active');
 const enrolled=data.paths.find(p=>p.id===personal?.pathId)||data.paths.find(p=>data.pathEnrolments.some(e=>e.userId===me.userId&&e.pathId===p.id));
 const step=enrolled?pathProgress(data,me.userId,enrolled.id):null;
 const projects=data.projects.slice(0,3);
 const upcoming=data.events.filter(e=>new Date(e.startsAt).getTime()+e.duration*60000>Date.now()).sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).slice(0,3);
 const activity=[...data.posts.filter(p=>!p.hidden).map(p=>({id:`post:${p.id}`,userId:p.authorId,at:p.createdAt,title:p.title||p.body.slice(0,70),detail:data.spaces.find(s=>s.id===p.spaceId)?.name||'Community discussion',to:`/post/${p.id}`})),...data.contributions.filter(c=>c.status==='recognised').map(c=>({id:`contribution:${c.id}`,userId:c.userId,at:c.reviewedAt||c.createdAt,title:c.title,detail:'Recognised contribution · '+(data.projects.find(p=>p.id===c.projectId)?.title||'Project'),to:`/projects/${c.projectId}`}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,3);
 return <div className="purpose-home v4-home">
  <header className="v4-intro"><div><span className="eyebrow">YOUR COMMUNITY. YOUR NEXT CHAPTER.</span><h1>Build together.<br/>Become more.</h1></div><p>Good people. Meaningful work.<br/>A place to become more, together.</p></header>
  <section className="v4-hero" aria-label="Community direction"><div className="v4-hero-copy"><span className="eyebrow">WHAT WE’RE HERE TO DO</span><h2>{purposes.length===1?purposes[0].title:purposes.length?'Turn an idea into something real.':'Start with your people.'}</h2><p>{purposes.length===1?purposes[0].description:data.organisation.tagline||'Learn something. Make something. Find your people.'}</p><div className="v4-hero-actions"><Button asChild size="sm"><Link to={enrolled?`/paths/${enrolled.id}`:'/paths'}>Continue your path <ArrowRight size={16}/></Link></Button><Button asChild variant="outline" size="sm"><Link to="/projects">Explore projects</Link></Button></div><div className="v4-hero-people"><AvatarStack members={present(data.members).filter(m=>m.userId!==me.userId).slice(0,4)}/><span>Better with your people.</span></div></div><img className="v4-hero-image" src={mountainImage} alt=""/><nav className="purpose-pillars v4-purpose-links" aria-label="Community purposes">{purposes.map(p=><Link key={p.id} to={`/paths?purpose=${p.id}`} className={`pillar-${p.kind}`} title={p.title}>{kindLabel[p.kind]}</Link>)}</nav></section>
  <div className="v4-card-grid">
   <section className="panel v4-next"><SectionTitle title="Your next action" to={enrolled?`/paths/${enrolled.id}`:'/paths'} link="Open path"/><h2>{step?.next?.title||personal?.title||'Choose a useful first step.'}</h2><p>{personal?.title||'A small useful step. Keep the momentum visible.'}</p>{personal?.visibility==='private'&&<small className="goal-privacy"><Lock size={12}/>Only you can see this goal</small>}<ul className="v4-milestones">{step?.milestones.slice(0,3).map(m=><li key={m.id}><span className={m.done?'step-complete':'step-pending'}>{m.done&&<Check size={12}/>}</span><Link to={`/paths/${enrolled!.id}`}>{m.title}</Link></li>)}</ul><Button variant="ghost" size="sm" onClick={()=>G(true)} disabled={!purposes.length}>{personal?'Refine my goal':'Set a personal goal'}</Button></section>
   <section className="panel personal-direction v4-progress"><SectionTitle title="Path progress" to={enrolled?`/paths/${enrolled.id}`:'/paths'} link="Open path"/>{enrolled&&step?<><div className="v4-progress-body"><div className="v4-progress-ring" role="progressbar" aria-label="Milestones evidenced" aria-valuemin={0} aria-valuemax={100} aria-valuenow={step.percent} style={{'--progress':`${step.percent}%`} as CSSProperties}><strong>{step.percent}%</strong></div><div><h2>{enrolled.title}</h2><p>{step.completed} of {step.total} milestones evidenced</p><small>{step.total-step.completed} remaining</small></div></div><p className="v4-progress-note">Progress from completed lessons and reviewed work, not time spent scrolling.</p></>:<><h2>Your path starts here.</h2><p>Choose a direction that means something to you.</p><Button asChild variant="outline" size="sm"><Link to="/paths">Explore paths</Link></Button></>}</section>
   <section className="panel v4-projects"><SectionTitle title="Active projects" to="/projects" link="View all"/>{projects.map(p=>{const team=data.projectMembers.filter(m=>m.projectId===p.id).map(m=>data.members.find(x=>x.userId===m.userId)!).filter(Boolean);return <Link className="v4-project-row" key={p.id} to={`/projects/${p.id}`}><span className="v4-project-thumb"><Cover kind="project" subject={p} small/></span><span className="v4-row-copy"><strong>{p.title}</strong><small>{p.category} · {team.length} {team.length===1?'collaborator':'collaborators'}</small></span><AvatarStack members={team} limit={2}/></Link>;})}{!projects.length&&<p>No projects yet. Your first shared idea belongs here.</p>}</section>
   <section className="panel v4-activity"><SectionTitle title="Recent activity" to="/discussions" link="See all"/>{activity.map(a=><Link className="v4-activity-row" to={a.to} key={a.id}><Avatar member={data.members.find(m=>m.userId===a.userId)} size="sm"/><span className="v4-row-copy"><strong>{a.title}</strong><small>{data.members.find(m=>m.userId===a.userId)?.name} · {a.detail}</small></span><time dateTime={a.at}>{date(a.at)}</time></Link>)}{!activity.length&&<p>A conversation or a piece of work will give this space its first story.</p>}</section>
   <section className="panel v4-events"><SectionTitle title="Upcoming" to="/events" link="Calendar"/>{upcoming.map(e=>{const d=dayParts(e.startsAt);return <Link className="v4-event-row" to={`/events/${e.id}`} key={e.id}><div className="date-block"><small>{d.month}</small><strong>{d.day}</strong></div><span className="v4-row-copy"><strong>{e.title}</strong><small>{date(e.startsAt,{hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'})} UK · {e.format}</small></span><ArrowRight size={14}/></Link>})}{!upcoming.length&&<div className="v4-quiet-calendar"><CalendarDays size={23}/><h2>Make time for your people.</h2><p>No upcoming events. Find the next session in the community calendar.</p><Button asChild variant="outline" size="sm"><Link to="/events">Open calendar</Link></Button></div>}</section>
  </div>
  {data.communityOutputs.length>0&&<section className="v4-output-strip" aria-label="Community outputs"><ShieldCheck size={18}/><span><small>MADE BY THIS COMMUNITY</small><strong>{data.communityOutputs[0].title}</strong></span><Link to="/outputs">View reviewed work <ArrowUpRight size={14}/></Link></section>}
  <div className="v4-home-footnote"><span>{mode==='demo'?'Fictional community · real application interactions':'Your community · your next step'}</span><em>Progress becomes identity when there is proof.</em></div>
  {goal&&<GoalModal existing={personal} onClose={()=>G(false)}/>}
 </div>;
}

export function DiscussionsPage(){return <><PageHeading eyebrow="THE CONVERSATION STILL MATTERS" title="Talk about what comes next." body="Questions, feedback, work in progress and the people behind it."/><div className="reading-width"><Feed/></div></>;}

export function PathsPage(){
    const {data,me}=useWorkspace();const [create,C]=useState(false);const [params,setParams]=useSearchParams();const filter=params.get('purpose')||'all';
    const F=(value:string)=>setParams(value==='all'?{}:{purpose:value});const paths=data.paths.filter(p=>filter==='all'||p.purposeId===filter);
    return <><PageHeading eyebrow="LEARN. PRACTISE. MAKE YOUR MARK." title="A direction worth following." body="Paths connect useful learning to real work. Progress follows what you do, not how long you scroll." action={isAdmin(me)?<button className="button primary" onClick={()=>C(true)} disabled={!data.purposes.some(p=>p.status==='active')}><Plus size={16}/>Create path</button>:undefined}/><div className="path-subnav"><strong><RouteIcon size={16}/>Paths</strong><Link to="/learn"><BookOpen size={16}/>Course library</Link><Link to="/missions"><Target size={16}/>Missions</Link><Link to="/outputs"><ShieldCheck size={16}/>Community outputs</Link></div><div className="filter-tabs spaced"><button className={filter==='all'?'selected':''} onClick={()=>F('all')}>All directions</button>{data.purposes.filter(p=>p.status==='active').map(p=><button key={p.id} className={filter===p.id?'selected':''} onClick={()=>F(p.id)}>{p.title}</button>)}</div><div className="purpose-path-grid">{paths.map(p=><PathCard path={p} key={p.id}/>)}</div>{!paths.length&&<Empty title="A direction is taking shape." body="The community team can connect existing lessons, missions and projects into its first path."/>}{create&&<PathModal onClose={()=>C(false)}/>}</>;
}
function PathCard({path:p}:{path:Path}){const {data,me}=useWorkspace();const purpose=data.purposes.find(x=>x.id===p.purposeId)!;const pr=pathProgress(data,me.userId,p.id);const joined=data.pathEnrolments.some(e=>e.pathId===p.id&&e.userId===me.userId);const Icon=kindIcon[purpose.kind];return <Link className={`path-card pillar-${purpose.kind}`} to={`/paths/${p.id}`}><header><span className={`purpose-icon tone-${kindTone[purpose.kind]}`}><Icon size={23}/></span><Pill tone={p.status==='published'?kindTone[purpose.kind]:'amber'}>{p.status==='published'?kindLabel[purpose.kind]:'Draft'}</Pill></header><h2>{p.title}</h2><p>{p.summary}</p><div className="path-step-types"><span><BookOpen size={14}/>Learn</span><i/><span><Target size={14}/>Do</span><i/><span><ShieldCheck size={14}/>Prove</span></div>{joined&&<><div className="mini-progress"><span style={{width:`${pr.percent}%`}}/></div><span className="progress-caption">{pr.completed} / {pr.total} milestones evidenced</span></>}<footer><span>{joined?'Continue your path':`${pr.total} meaningful steps`}</span><ArrowUpRight size={19}/></footer></Link>}
export function PathPage(){
    const {id}=useParams();const {data,me,command,busy}=useWorkspace();const [milestone,M]=useState(false),[goal,G]=useState(false);const p=data.paths.find(p=>p.id===id);
    if(!p)return <Empty title="This path is not available." body="It may still be a draft, or belong to a private space."/>;
    const purpose=data.purposes.find(x=>x.id===p.purposeId)!;const pr=pathProgress(data,me.userId,p.id);const joined=data.pathEnrolments.some(x=>x.pathId===p.id&&x.userId===me.userId);const existing=data.memberGoals.find(g=>g.userId===me.userId&&g.purposeId===p.purposeId);
    return <><Back to="/paths" label="All paths"/><PageHeading eyebrow={`${kindLabel[purpose.kind].toUpperCase()} / ${purpose.title.toUpperCase()}`} title={p.title} body={p.summary}/><div className="detail-layout"><article className="detail-main"><div className="panel path-progress-summary"><RouteIcon size={24}/><span><strong>{pr.completed} of {pr.total} milestones evidenced</strong><small>A lesson completed. Proof reviewed. A contribution recognised.</small></span><strong>{pr.percent}%</strong></div><ol className="milestone-list">{pr.milestones.map((m,i)=><li className={m.done?'evidenced':''} key={m.id}><span className="milestone-number">{m.done?<Check size={20}/>:String(i+1).padStart(2,'0')}</span><div><Pill tone={m.done?'mint':'violet'}>{m.done?'Evidenced':m.label}</Pill><h2>{m.title}</h2><p>{m.description}</p><Link className="text-link" to={m.href}>{m.done?'Revisit the work':'Take this step'} <ArrowRight size={16}/></Link></div></li>)}</ol>{isAdmin(me)&&p.status==='draft'&&<button className="button secondary" onClick={()=>M(true)}><Plus size={16}/>Add milestone</button>}</article><aside className="detail-aside"><section className="panel"><span className="eyebrow">YOUR PATH, YOUR PACE</span><h2>Progress you can point to.</h2><p className="muted">You can explore in any order. Evidence counts only when the underlying step is complete. Joining a project is not a contribution.</p>{p.status==='published'?<button className="button primary full" disabled={busy||joined} onClick={()=>command({type:'path.enrol',pathId:p.id})}>{joined?<><Check size={16}/>You’re on this path</>:<>Join this path <ArrowRight size={16}/></>}</button>:<button className="button primary full" disabled={busy||!pr.total} onClick={()=>command({type:'path.publish',pathId:p.id})}>Publish path</button>}<button className="button secondary full" onClick={()=>G(true)} disabled={p.status!=='published'}><Target size={16}/>{existing?'Refine my goal':'Make it my goal'}</button><p className="sample-note">Personal goals are private by default. Learning is an action record, not an accredited credential.</p></section><Link className="panel purpose-evidence-link" to="/outputs"><ShieldCheck size={21}/><h3>What changed because of the work?</h3><p>Record a reviewed outcome when you have something to show.</p><span className="text-link">Outcomes & outputs <ArrowRight size={15}/></span></Link></aside></div>{milestone&&<MilestoneModal path={p} onClose={()=>M(false)}/>} {goal&&<GoalModal existing={existing} purposeId={p.purposeId} pathId={p.id} onClose={()=>G(false)}/>}</>;
}

export function GoalModal({onClose,existing,purposeId,pathId}:{onClose:()=>void;existing?:MemberGoal;purposeId?:Id;pathId?:Id}){
    const {data,command,busy}=useWorkspace();const [purpose,P]=useState(purposeId||existing?.purposeId||data.purposes.find(p=>p.status==='active')?.id||'');const [path,S]=useState(pathId||existing?.pathId||'');
    return <Modal title="What are you working towards?" onClose={onClose}><p className="modal-intro">Something specific to you. You can keep this private, change direction or pause it.</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await command({type:'goal.set',purposeId:purpose,pathId:path||null,title:read(f,'title'),visibility:read(f,'visibility') as 'private'|'members'}))onClose();}}><label>Community purpose<select value={purpose} onChange={e=>{P(e.target.value);S('')}} required>{data.purposes.filter(p=>p.status==='active').map(p=><option key={p.id} value={p.id}>{kindLabel[p.kind]} · {p.title}</option>)}</select></label><label>My goal<input required maxLength={180} name="title" defaultValue={existing?.title||''} placeholder="What would meaningful progress look like for you?"/></label><label>Link a path (optional)<select value={path} onChange={e=>S(e.target.value)}><option value="">No path yet</option>{data.paths.filter(p=>p.purposeId===purpose&&p.status==='published').map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Who can see my goal?<select name="visibility" defaultValue={existing?.visibility||'private'}><option value="private">Only me</option><option value="members">Members of this community</option></select></label><p className="sample-note">A goal is an intention, not a credential. Completing it requires path evidence or a reviewed outcome.</p><button className="button primary" disabled={busy||!purpose}>Save my goal</button></form></Modal>;
}

export function PurposeSettings(){
    const {data,me}=useWorkspace();const [editing,E]=useState<Purpose|'new'|null>(null);if(!isAdmin(me))return null;
    return <section className="panel settings-form purpose-settings"><SectionTitle title="What are we here to do?" aside={<button className="button secondary compact" onClick={()=>E('new')}><Plus size={15}/>Add purpose</button>}/><p className="muted">Define what people are becoming, building or trying to achieve. One is enough. None is invented for you.</p>{data.purposes.map(p=><div className="purpose-setting-row" key={p.id}><span><Pill tone={kindTone[p.kind]}>{kindLabel[p.kind]}{p.status==='archived'?' · archived':''}</Pill><strong>{p.title}</strong><small>{p.description}</small></span><button className="button secondary compact" onClick={()=>E(p)}>Edit</button></div>)}{!data.purposes.length&&<p className="sample-note">Your existing spaces and discussions still work without a purpose. Add one when you know the direction.</p>}{editing&&<PurposeModal purpose={editing==='new'?undefined:editing} onClose={()=>E(null)}/>}</section>;
}
function PurposeModal({purpose,onClose}:{purpose?:Purpose;onClose:()=>void}){const {command,busy}=useWorkspace();return <Modal title={purpose?'Refine your community purpose':'Give your community a direction'} onClose={onClose}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await command({type:'purpose.save',purposeId:purpose?.id,kind:read(f,'kind') as Purpose['kind'],title:read(f,'title'),description:read(f,'description'),status:read(f,'status') as Purpose['status']}))onClose();}}><label>Direction<select name="kind" defaultValue={purpose?.kind||'become'}><option value="become">Become · capability or personal development</option><option value="build">Build · something to create together</option><option value="achieve">Achieve · a destination or outcome</option></select></label><label>What are we here to do?<input required name="title" maxLength={120} defaultValue={purpose?.title||''} placeholder="Make our first independent film"/></label><label>Why it matters<textarea name="description" rows={3} maxLength={2000} defaultValue={purpose?.description||''}/></label><label>Status<select name="status" defaultValue={purpose?.status||'active'}><option value="active">Active</option><option value="archived">Archived · retain previous evidence</option></select></label><button className="button primary" disabled={busy}>Save purpose</button></form></Modal>}
function PathModal({onClose}:{onClose:()=>void}){const {data,command,busy}=useWorkspace();const navigate=useNavigate();return <Modal title="Create a path, not another course" onClose={onClose}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await command({type:'path.create',purposeId:read(f,'purpose'),title:read(f,'title'),summary:read(f,'summary'),spaceId:idOrNull(f,'space')});if(r){onClose();navigate(`/paths/${r.objectId}`)}}}><label>Purpose<select name="purpose" required>{data.purposes.filter(p=>p.status==='active').map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label>Path title<input name="title" required maxLength={120}/></label><label>The journey<textarea name="summary" rows={3} required maxLength={1000}/></label><label>Audience<select name="space"><option value="">Whole community</option>{data.spaces.map(s=><option value={s.id} key={s.id}>{s.name}{s.visibility==='private'?' · private':''}</option>)}</select></label><p className="sample-note">The path starts as a draft. You will add milestones linked to existing work, then publish.</p><button className="button primary" disabled={busy}>Create draft path</button></form></Modal>}
function MilestoneModal({path,onClose}:{path:Path;onClose:()=>void}){const {data,command,busy}=useWorkspace();const [kind,K]=useState('lesson');return <Modal title="A milestone with evidence" onClose={onClose}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),target=read(f,'target');if(await command({type:'milestone.create',pathId:path.id,title:read(f,'title'),description:read(f,'description'),lessonId:kind==='lesson'?target:null,missionId:kind==='mission'?target:null,projectId:kind==='project'?target:null}))onClose();}}><label>Meaningful step<input name="title" required maxLength={120}/></label><label>What should someone do?<textarea name="description" rows={2} maxLength={1000}/></label><label>Evidence type<select value={kind} onChange={e=>K(e.target.value)}><option value="lesson">Complete a lesson</option><option value="mission">Submit reviewed mission proof</option><option value="project">Make a recognised project contribution</option></select></label><label>Existing work<select name="target" required key={kind}>{(kind==='lesson'?data.lessons.map(l=>({id:l.id,title:l.title})):kind==='mission'?data.missions:data.projects).map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><p className="sample-note">Private content cannot be linked into a wider-audience path. Published milestones stay stable for learners.</p><button className="button primary" disabled={busy}>Add evidence-backed milestone</button></form></Modal>}

export function ProjectEvidence({projectId}:{projectId:string}){
    const {data,me,command,busy}=useWorkspace();const [add,A]=useState<true|Contribution|false>(false);const p=data.projects.find(p=>p.id===projectId);if(!p)return null;
    const contributions=data.contributions.filter(c=>c.projectId===p.id);const joined=data.projectMembers.some(m=>m.projectId===p.id&&m.userId===me.userId);const purpose=data.purposes.find(x=>x.id===p.purposeId);
    return <><section className="panel project-purpose"><span className="eyebrow">WHAT THIS WORK SERVES</span><h2>{purpose?.title||'A project finding its direction.'}</h2>{(isAdmin(me)||p.ownerId===me.userId)&&<label className="inline-purpose-label">Community purpose<select aria-label="Project purpose" value={p.purposeId||''} disabled={busy} onChange={e=>command({type:'project.purpose',projectId:p.id,purposeId:e.target.value||null})}><option value="">Not linked yet</option>{data.purposes.filter(x=>x.status==='active').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}</section><section className="panel project-evidence"><SectionTitle title="Work worth recognising" aside={joined?<button className="button secondary compact" onClick={()=>A(true)}><Plus size={15}/>Record contribution</button>:undefined}/><p className="muted">Show what you actually did. A project owner or community administrator reviews it. Team membership alone is not proof.</p>{contributions.map(c=><article className={'evidence-item'+(c.status==='withdrawn'?' is-withdrawn':'')} key={c.id}><div className="teacher-row"><Avatar size="sm" member={data.members.find(m=>m.userId===c.userId)}/><span><strong>{data.members.find(m=>m.userId===c.userId)?.name}</strong><small>{date(c.createdAt)}</small></span><Pill tone={c.status==='recognised'?'mint':c.status==='withdrawn'?'neutral':'amber'}>{c.status.replaceAll('_',' ')}</Pill></div><h3>{c.title}</h3><p className="preline">{c.body}</p>{c.evidenceUrl&&<a className="text-link" href={c.evidenceUrl} target="_blank" rel="noopener noreferrer">View evidence <ArrowUpRight size={14}/></a>}{c.feedback&&<div className="evidence-feedback"><ShieldCheck size={16}/><span><strong>{data.members.find(m=>m.userId===c.reviewerId)?.name||'Community reviewer'}</strong><p>{c.feedback}</p></span></div>}{c.status==='submitted'&&c.userId!==me.userId&&!(data.contributionCredits??[]).some(k=>k.contributionId===c.id&&k.userId===me.userId&&k.status==='accepted')&&(p.ownerId===me.userId||isAdmin(me))&&<EvidenceReview objectId={c.id} kind="contribution"/>}{c.status==='changes_requested'&&c.userId===me.userId&&<button className="button secondary compact" onClick={()=>A(c)}>Revise contribution</button>}<ContributionCredits contribution={c}/><EvidenceHistory subject="contribution" record={c}/></article>)}{!contributions.length&&<p className="sample-note">The first contribution is waiting to be recorded.</p>}</section>{add&&<ContributionModal projectId={p.id} existing={add===true?undefined:add} onClose={()=>A(false)}/>}</>;
}
function ContributionModal({projectId,existing,onClose}:{projectId:string;existing?:Contribution;onClose:()=>void}){const {command,busy}=useWorkspace();return <Modal title={existing?'Improve your contribution record':'What did you contribute?'} onClose={onClose}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const common={title:read(f,'title'),body:read(f,'body'),evidenceUrl:read(f,'url')};if(await command(existing?{type:'contribution.resubmit',contributionId:existing.id,...common}:{type:'contribution.submit',projectId,...common}))onClose();}}><label>Contribution title<input required name="title" maxLength={140} defaultValue={existing?.title||''} placeholder="Tested the first onboarding with three creators"/></label><label>What you did and what changed<textarea required name="body" rows={5} maxLength={8000} defaultValue={existing?.body||''}/></label><label>Evidence link (optional)<input type="url" name="url" maxLength={2000} placeholder="https://…" defaultValue={existing?.evidenceUrl||''}/></label><p className="sample-note">Recognised work appears to people who can access this project. Only share material you have permission to share.</p><button className="button primary" disabled={busy}>Submit contribution</button></form></Modal>}
export function EvidenceReview({objectId,kind}:{objectId:string;kind:'contribution'|'outcome'}){const {command,busy}=useWorkspace();const [feedback,F]=useState('');return <div className="evidence-review"><label>Review feedback<textarea aria-label={`${kind} review feedback`} maxLength={2000} value={feedback} onChange={e=>F(e.target.value)} rows={2} placeholder="What evidence did you check? What changed?"/></label><div><button className="button secondary compact" disabled={busy||!feedback.trim()} onClick={()=>command(kind==='contribution'?{type:'contribution.review',contributionId:objectId,decision:'changes_requested',feedback}:{type:'outcome.review',outcomeId:objectId,decision:'changes_requested',feedback})}>Request changes</button><button className="button primary compact" disabled={busy||!feedback.trim()} onClick={()=>command(kind==='contribution'?{type:'contribution.review',contributionId:objectId,decision:'recognised',feedback}:{type:'outcome.review',outcomeId:objectId,decision:'verified',feedback})}><Check size={14}/>{kind==='contribution'?'Recognise contribution':'Verify outcome'}</button></div></div>}

export function OutputsPage(){const {data,me,mode}=useWorkspace();const [form,F]=useState<true|Outcome|false>(false);const candidates=data.purposes.some(p=>p.status==='active')&&(data.submissions.some(s=>s.authorId===me.userId&&s.status==='approved'&&!data.outcomes.some(o=>o.submissionId===s.id))||data.contributions.some(c=>c.userId===me.userId&&c.status==='recognised'&&!data.outcomes.some(o=>o.contributionId===c.id))); return <><PageHeading eyebrow="WHAT CAME OUT OF COMING TOGETHER" title="Made here. Meant something." body="The films, products and work this community can point to. Every published output is linked to a reviewed outcome." action={<button className="button primary" disabled={!candidates} onClick={()=>F(true)}><Plus size={16}/>Record outcome</button>}/>{mode==='demo'&&<p className="sample-note output-demo-note">Illustrative community data. These are fictional examples, not claims about real members or completed work.</p>}<div className="output-grid">{data.communityOutputs.map(o=>{const outcome=data.outcomes.find(x=>x.id===o.outcomeId);return <article className="output-card" key={o.id}><div className="output-card-art"><span>{o.kind.toUpperCase()}</span><BookOpen size={60}/></div><div><Pill tone="mint"><ShieldCheck size={12}/>Community reviewed</Pill><h2>{o.title}</h2><p>{o.summary}</p><footer><Avatar size="sm" member={data.members.find(m=>m.userId===outcome?.authorId)}/><span>{data.members.find(m=>m.userId===outcome?.authorId)?.name}<small>{data.purposes.find(p=>p.id===o.purposeId)?.title}</small></span></footer>{o.projectId?<Link className="text-link" to={`/projects/${o.projectId}`}>See the work and its contributors <ArrowRight size={15}/></Link>:outcome?.submissionId?<Link className="text-link" to={`/missions/${data.submissions.find(s=>s.id===outcome.submissionId)?.missionId}`}>See the reviewed proof <ArrowRight size={15}/></Link>:null}</div></article>})}</div>{!data.communityOutputs.length&&<Empty title="Something real will belong here." body="No invented milestones, income totals or engagement badges. Publish a reviewed outcome when the work exists."/>}<SectionTitle title={isAdmin(me)?'Outcomes and reviews':'Your outcomes & community evidence'}/><div className="outcome-list">{data.outcomes.map(o=><OutcomeCard key={o.id} outcome={o} onRevise={()=>F(o)}/>)}</div>{!data.outcomes.length&&<p className="muted">An approved mission proof or recognised project contribution can support your first outcome.</p>}{form&&<OutcomeModal existing={form===true?undefined:form} onClose={()=>F(false)}/>}</>}
function OutcomeCard({outcome:o,onRevise}:{outcome:Outcome;onRevise:()=>void}){const {data,me,command,busy}=useWorkspace();const [kind,K]=useState<OutputKind>('other');const source=o.contributionId?data.contributions.find(c=>c.id===o.contributionId):undefined;const sub=o.submissionId?data.submissions.find(s=>s.id===o.submissionId):undefined;const published=data.communityOutputs.some(x=>x.outcomeId===o.id);return <article className={'panel outcome-card'+(o.status==='withdrawn'?' is-withdrawn':'')}><header><Pill tone={o.status==='verified'?'mint':o.status==='withdrawn'?'neutral':'amber'}>{o.status==='verified'?'Community verified':o.status.replaceAll('_',' ')}</Pill><span>{data.members.find(m=>m.userId===o.authorId)?.name}</span></header><h3>{o.title}</h3><p>{o.summary}</p><Link className="text-link" to={source?`/projects/${source.projectId}`:`/missions/${sub?.missionId}`}><ShieldCheck size={15}/>{source?'Recognised contribution':'Approved mission proof'} · {source?.title||data.missions.find(m=>m.id===sub?.missionId)?.title}</Link>{o.feedback&&<p className="evidence-feedback"><ShieldCheck size={17}/>{o.feedback}</p>}{o.evidenceUrl&&<a className="text-link" href={o.evidenceUrl} target="_blank" rel="noopener noreferrer">Outcome evidence <ArrowUpRight size={14}/></a>}{o.status==='submitted'&&isAdmin(me)&&o.authorId!==me.userId&&<EvidenceReview kind="outcome" objectId={o.id}/>} {o.status==='changes_requested'&&o.authorId===me.userId&&<button className="button secondary" onClick={onRevise}>Revise outcome</button>}{o.status==='verified'&&isAdmin(me)&&!published&&<div className="publish-output"><label>Output type<select aria-label="Output type" value={kind} onChange={e=>K(e.target.value as OutputKind)}>{['film','software','research','event','music','book','company','campaign','other'].map(k=><option key={k} value={k}>{k}</option>)}</select></label><button className="button primary compact" disabled={busy} onClick={()=>command({type:'output.publish',outcomeId:o.id,kind})}>Publish output</button></div>}{published&&o.status==='verified'&&<p className="sample-note"><Check size={14}/> In the community archive</p>}<EvidenceHistory subject="outcome" record={o}/></article>}
function OutcomeModal({existing,onClose}:{existing?:Outcome;onClose:()=>void}){const {data,me,command,busy}=useWorkspace();const sources=[...data.submissions.filter(s=>s.authorId===me.userId&&s.status==='approved'&&!data.outcomes.some(o=>o.submissionId===s.id)).map(s=>({id:`submission:${s.id}`,title:data.missions.find(m=>m.id===s.missionId)?.title||'Mission proof',purposeId:null as string|null})),...data.contributions.filter(c=>c.userId===me.userId&&c.status==='recognised'&&!data.outcomes.some(o=>o.contributionId===c.id)).map(c=>({id:`contribution:${c.id}`,title:c.title,purposeId:data.projects.find(p=>p.id===c.projectId)?.purposeId??null}))];const [sourceId,S]=useState(sources[0]?.id||'');const source=sources.find(s=>s.id===sourceId);const options=data.purposes.filter(p=>p.status==='active'&&(!source?.purposeId||p.id===source.purposeId));return <Modal title={existing?'Refine the outcome':'What changed because of the work?'} onClose={onClose}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),[kind,id]=read(f,'source').split(':');const common={title:read(f,'title'),summary:read(f,'summary'),evidenceUrl:read(f,'url')};if(await command(existing?{type:'outcome.resubmit',outcomeId:existing.id,...common}:{type:'outcome.submit',purposeId:read(f,'purpose'),submissionId:kind==='submission'?id:null,contributionId:kind==='contribution'?id:null,...common}))onClose();}}>{!existing&&<><label>Community purpose<select name="purpose" key={sourceId} required>{options.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label>Reviewed evidence<select name="source" value={sourceId} onChange={e=>S(e.target.value)} required>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label></>}<label>The outcome<input required name="title" maxLength={160} defaultValue={existing?.title||''} placeholder="The first usable version is now in a creator’s hands"/></label><label>What happened, and what evidence supports it?<textarea required name="summary" rows={4} maxLength={5000} defaultValue={existing?.summary||''}/></label><label>Additional evidence link (optional)<input name="url" type="url" maxLength={2000} defaultValue={existing?.evidenceUrl||''} placeholder="https://…"/></label><p className="sample-note">This starts as an unverified record. Another administrator must review it. Verification here means a community review, not independent accreditation.</p><button className="button primary" disabled={busy||(!existing&&(!sources.length||!options.length))}>Submit outcome</button></form></Modal>}

function GoalActions({goal:g,onRefine}:{goal:MemberGoal;onRefine:()=>void}){
    const {data,me,command,busy}=useWorkspace();const [outcomeId,O]=useState(g.outcomeId||'');
    const choices=data.outcomes.filter(o=>o.authorId===me.userId&&o.purposeId===g.purposeId&&o.status==='verified');
    return <div className="goal-actions"><button className="button secondary compact" onClick={onRefine}>Refine goal</button><button className="button secondary compact" disabled={busy} onClick={()=>command({type:'goal.status',goalId:g.id,status:g.status==='paused'?'active':'paused'})}>{g.status==='paused'?'Resume':'Pause'}</button>{g.status!=='completed'&&<><label>Completion evidence<select aria-label="Goal completion evidence" value={outcomeId} onChange={e=>O(e.target.value)}><option value="">Completed linked path</option>{choices.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><button className="button secondary compact" disabled={busy} onClick={()=>command({type:'goal.status',goalId:g.id,status:'completed',outcomeId:outcomeId||null})}>Mark evidenced goal complete</button></>}{g.status==='completed'&&<small>{g.outcomeId?'Completed with a specifically linked reviewed outcome.':'Completed through evidence on the linked path.'}</small>}</div>;
}

export function ProfileEvidence({userId}:{userId:string}){
    const {data,me,command,busy}=useWorkspace();const [goal,G]=useState<MemberGoal|true|null>(null);const own=me.userId===userId;const goals=data.memberGoals.filter(g=>g.userId===userId);const contributions=data.contributions.filter(c=>c.userId===userId&&c.status==='recognised');const outcomes=data.outcomes.filter(o=>o.authorId===userId&&o.status==='verified');
    return <><section className="panel profile-purpose"><SectionTitle title={own?'What I’m working towards':'A direction taking shape'} aside={own?<button className="button secondary compact" onClick={()=>G(true)} disabled={!data.purposes.some(p=>p.status==='active')}><Plus size={14}/>Set a goal</button>:undefined}/>{goals.map(g=><article className="goal-row" key={g.id}><header><Pill tone="violet">{g.status}</Pill>{own&&<small>{g.visibility==='private'?<><Lock size={12}/>Private to you</>:'Shared with members'}</small>}</header><h3>{g.title}</h3>{g.pathId&&<Link className="text-link" to={`/paths/${g.pathId}`}>{data.paths.find(p=>p.id===g.pathId)?.title} <ArrowRight size={14}/></Link>}{own&&<GoalActions goal={g} onRefine={()=>G(g)}/>}</article>)}{!goals.length&&<p className="muted">{own?'Choose a small, meaningful next step.':'No goals have been shared with this community.'}</p>}</section><section className="panel"><SectionTitle title="Contributions, not just a bio" aside={<Pill>{contributions.length} recognised</Pill>}/>{contributions.map(c=><Link key={c.id} to={`/projects/${c.projectId}`} className="proof-item"><ShieldCheck size={22}/><span><strong>{c.title}</strong><small>{data.projects.find(p=>p.id===c.projectId)?.title} · Reviewed by {data.members.find(m=>m.userId===c.reviewerId)?.name}</small></span><ArrowUpRight size={16}/></Link>)}{!contributions.length&&<p className="muted">Recognised project work will appear here. A skill in a bio is self-described; a contribution has evidence and a reviewer.</p>}</section><CreditedOn userId={userId}/><section className="panel"><SectionTitle title="What changed" aside={<Pill tone="mint">{outcomes.length} reviewed</Pill>}/>{outcomes.map(o=><Link className="proof-item" to="/outputs" key={o.id}><Flag size={21}/><span><strong>{o.title}</strong><small>Outcome reviewed inside this community</small></span><ArrowUpRight size={16}/></Link>)}{!outcomes.length&&<p className="muted">Reviewed outcomes will form a living record of the difference this work made.</p>}</section>{goal&&<GoalModal existing={goal===true?undefined:goal} onClose={()=>G(null)}/>}</>;
}

export function KnowledgePage(){const {data}=useWorkspace();return <><PageHeading eyebrow="KEEP WHAT THE COMMUNITY LEARNS" title="Useful beyond the conversation." body="Keep the insights, resources and lessons that help the next person move forward."/><div className="path-subnav"><Link to="/learn"><BookOpen size={16}/>Course library</Link><Link to="/outputs"><ShieldCheck size={16}/>Community outputs</Link></div><div className="reading-width post-list">{data.posts.filter(p=>p.kind==='resource'&&!p.hidden).map(p=><PostCard key={p.id} post={p}/>)}{!data.posts.some(p=>p.kind==='resource'&&!p.hidden)&&<Empty title="Something useful deserves to stay." body="Resource posts shared in your accessible spaces will collect here." action={<Link to="/discussions" className="button secondary">Share a resource</Link>}/>}</div></>}
