#!/usr/bin/env python3
"""Render the local HTML handover. Optional docs-only dependency: mistune==3.2.1."""
from pathlib import Path
from html import escape
try:
    import mistune
except ImportError as exc:
    raise SystemExit('Install the optional docs dependency: python3 -m pip install -r scripts/requirements-docs.txt') from exc
root=Path(__file__).resolve().parents[1]
sections=[('review','Research into product','research/notes/10_RESEARCH_TO_BUILD_ALPHA_05.md'),('build','Build and verification','platform/docs/BUILD_STATUS.md'),('prd','Product requirements','platform/docs/PRD.md'),('doctrine','Product doctrine','platform/docs/PRODUCT_DOCTRINE.md'),('architecture','Architecture','platform/docs/ARCHITECTURE.md'),('decision','Workspace decision','platform/docs/decisions/005-project-workspaces.md'),('roadmap','Roadmap','platform/docs/ROADMAP.md'),('release','Connected release gates','platform/docs/RELEASE_GATES.md')]
render=mistune.create_markdown(escape=True,plugins=['table','strikethrough','url'])
nav=''.join(f'<a href="#{key}"><small>{n:02}</small>{escape(title)}</a>' for n,(key,title,path) in enumerate(sections,1))
body=''.join(f'<section id="{key}"><div class="section-label">{n:02} / {escape(title)}</div>'+render((root/path).read_text())+'</section>' for n,(key,title,path) in enumerate(sections,1))
html='''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>REUNIR Alpha 05 · Research, product and build</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#101115;color:#e7e6ef;font:15px/1.8 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:#c5b0ff}aside{width:260px;position:fixed;inset:0 auto 0 0;background:#15161c;border-right:1px solid #30303b;padding:30px 24px;overflow:auto}aside strong{letter-spacing:.28em;font-size:22px}aside p{font-size:12px;color:#b4aabd;margin:12px 0 30px}nav a{display:flex;align-items:center;gap:15px;text-decoration:none;padding:10px;border-radius:8px;font-size:12px;color:#c8c6d5}nav a:hover{background:#2a233a}nav small{font-size:10px;color:#a997c5}main{margin-left:260px;padding:60px clamp(24px,5vw,90px);max-width:1440px}header{padding-bottom:50px;border-bottom:1px solid #36313f}.kicker,.section-label{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#b7a2da}.chip{display:inline-block;color:#d4c19e;border:1px solid #5a4730;background:#282119;padding:5px 12px;border-radius:20px;font-size:11px;margin-bottom:20px}header h1{font-size:clamp(35px,5vw,60px);line-height:1.12;letter-spacing:-.045em;max-width:700px;margin:10px 0 25px}header p{color:#bbb5c7;max-width:760px;font-size:16px}.stats{display:flex;gap:35px;margin-top:30px;flex-wrap:wrap}.stats strong{display:block;font-size:26px;color:#c9b5f4}.stats span{font-size:11px;color:#b4adbf}section{padding:50px 0;scroll-margin-top:25px;border-bottom:1px solid #30303a}.section-label{margin-bottom:25px}section h1{font-size:30px;line-height:1.3;letter-spacing:-.025em}h2{font-size:23px;margin-top:38px;line-height:1.4}h3{font-size:18px;margin-top:30px}p,li{color:#c8c5d2}strong{color:#f2eff7}table{border-collapse:collapse;width:100%;display:block;overflow-x:auto;font-size:12px;margin:24px 0}th,td{text-align:left;padding:14px 15px;border:1px solid #38333f;vertical-align:top;min-width:100px}th{background:#25212e;color:#e2d7f5}td{background:#18191f}pre{padding:22px;overflow:auto;background:#080a10;border:1px solid #303443;border-radius:10px;font-size:12px;line-height:1.65}code{font-size:.85em;background:#20202c;padding:2px 5px;border-radius:4px}pre code{background:none;padding:0}blockquote{border-left:3px solid #b895f6;margin:25px 0;padding:5px 22px;background:#1b1821}hr{border:0;border-top:1px solid #36303f;margin:32px 0}footer{margin:45px 0;color:#b6aeca;font-size:12px}@media(max-width:850px){aside{position:relative;width:auto;border-right:0;border-bottom:1px solid #33303f}aside p{margin-bottom:15px}nav{display:flex;flex-wrap:wrap;gap:2px}nav a{font-size:11px}main{margin:0;padding:35px 20px}header{padding-bottom:30px}section{padding-top:35px}table{font-size:11px}}@media print{aside{display:none}main{margin:0;padding:0}body{background:white;color:black}p,li,strong,header p{color:black}section{break-before:page}a{color:#444}}
</style></head><body><aside><strong>REUNIR</strong><p>ALPHA 05 / PRODUCT & ENGINEERING<br>24 September 2026</p><nav>'''+nav+'''</nav></aside><main><header><span class="chip">LOCAL ENGINEERING RELEASE · NOT DEPLOYED</span><div class="kicker">People + Purpose + Progress + Projects + Proof</div><h1>Useful work.<br>Visible proof.</h1><p>Project workspaces connect a clear brief and a teammate’s effort to reviewed contribution. This handbook records the research, implementation, tests and limits of the existing React and PostgreSQL application.</p><div class="stats"><div><strong>328</strong><span>application tests passed</span></div><div><strong>131</strong><span>demo-browser checks passed</span></div><div><strong>0</strong><span>new runtime dependencies</span></div><div><strong>6</strong><span>pinned research sources</span></div></div></header>'''+body+'''<footer>REUNIR Alpha 05. Application 0.5.0 · PRD revision 0.6. Fictional preview and local test evidence are not a live hosted pilot.</footer></main></body></html>'''
(root/'REUNIR-PRD.html').write_text(html)
print('Rendered REUNIR-PRD.html from',len(sections),'source documents.')
