import { pgTable, text, boolean, timestamp, integer, bigint, index, uniqueIndex } from 'drizzle-orm/pg-core';
// Better Auth's canonical fields, mapped to explicit PostgreSQL names.
export const user = pgTable('auth_user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('email_verified').notNull().default(false), image: text('image'), twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() });
export const session = pgTable('auth_session', { id: text('id').primaryKey(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), token: text('token').notNull().unique(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(), ipAddress: text('ip_address'), userAgent: text('user_agent'), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }) }, t => [index('auth_session_user_idx').on(t.userId)]);
export const account = pgTable('auth_account', { id: text('id').primaryKey(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('access_token'), refreshToken: text('refresh_token'), idToken: text('id_token'), accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }), refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }), scope: text('scope'), password: text('password'), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() }, t => [index('auth_account_user_idx').on(t.userId), uniqueIndex('auth_account_provider_idx').on(t.providerId, t.accountId)]);
export const verification = pgTable('auth_verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() }, t => [index('auth_verification_identifier_idx').on(t.identifier)]);
export const rateLimit = pgTable('auth_rate_limit', { id: text('id').primaryKey(), key: text('key').notNull().unique(), count: integer('count').notNull(), lastRequest: bigint('last_request', { mode: 'number' }).notNull() });
// Two-step sign-in (migration 0021). The plugin stores the secret and backup codes encrypted; they never leave the server.
export const twoFactor = pgTable('auth_two_factor', { id: text('id').primaryKey(), secret: text('secret').notNull(), backupCodes: text('backup_codes').notNull(), userId: text('user_id').notNull().unique().references(() => user.id, { onDelete: 'cascade' }), verified: boolean('verified').notNull().default(true), failedVerificationCount: integer('failed_verification_count').notNull().default(0), lockedUntil: timestamp('locked_until', { withTimezone: true }) });
