import { randomUUID } from 'node:crypto';
import { plainLessonDocument } from '../packages/contracts/src/lesson-document';
import { lessonContent } from '../packages/domain/src/authoring';
/** Opt-in integration test against a disposable local PostgreSQL CI service, never Neon/customer data. */
import {strict as assert} from 'node:assert';
import {mkdir,writeFile} from 'node:fs/promises';
import {openDatabase} from '../packages/db/src/connection';
import {migrate} from '../packages/db/src/migrate';
import {grantRuntimeTables} from '../packages/db/src/runtime-role';
import {runtimeRoleIsSafe} from '../packages/db/src/runtime-safety';
import {WorkspaceRepository,setContext} from '../packages/db/src/repository';
import {createSeed,DEMO_USER,DEMO_ADMIN} from '../packages/domain/src/seed';
import {PilotOperations} from '../apps/api/src/operations';
import {inspectMigrations} from '../packages/db/src/inspection';
const url=new URL(process.env.POSTGRES_TEST_URL||'http://unconfigured');
if(!['postgres:','postgresql:'].includes(url.protocol)||!['127.0.0.1','localhost','[::1]'].includes(url.hostname)||url.pathname!=='/reunir_ci')throw new Error('This test requires a disposable loopback database named reunir_ci. It cannot target remote or customer databases.');
const admin=await openDatabase(url.toString());
const results:{name:string;passed:boolean}[]=[];const check=async(name:string,fn:()=>Promise<void>)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
let runtime:Awaited<ReturnType<typeof openDatabase>>|undefined;
try{
    const existing=await admin.query("SELECT tablename FROM pg_tables WHERE schemaname='public'");
    assert.equal(existing.rows.length,0,'CI database must be empty; existing data has not been overwritten.');
    await check('ordered migrations apply on actual PostgreSQL',async()=>{await migrate(admin);assert((await inspectMigrations(admin)).every(r=>r.state==='matching'));});
    const seed=new WorkspaceRepository(admin);await seed.seed(createSeed());await seed.seed(createSeed('studio-north'));
    await admin.query("CREATE ROLE reunir_app LOGIN PASSWORD 'LOCAL_CI_TEST_ONLY_12345678901234567890' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS");
    await admin.transaction(grantRuntimeTables);url.username='reunir_app';url.password='LOCAL_CI_TEST_ONLY_12345678901234567890';runtime=await openDatabase(url.toString());
    await check('separate runtime connection is non-owner and cannot bypass RLS',async()=>{assert(await runtimeRoleIsSafe(runtime!));await assert.rejects(()=>runtime!.query('SELECT * FROM schema_migrations'));});
    await check('missing tenant context denies rows on a fresh connection',async()=>{assert.equal((await runtime!.query('SELECT id FROM posts')).rows.length,0);});
    await check('parallel connection-pool reads keep two tenant contexts separate',async()=>{const repo=new WorkspaceRepository(runtime!);const slugs=Array.from({length:20},(_,i)=>i%2?'code-black':'studio-north');const rows=await Promise.all(slugs.map(s=>repo.snapshot(s,DEMO_USER)));rows.forEach((r,i)=>assert.equal(r.organisation.slug,slugs[i]));});
    await check('transaction context is reset before a pooled connection is reused',async()=>{await runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_USER);assert((await tx.query('SELECT id FROM posts')).rows.length>0);});assert.equal((await runtime!.query('SELECT id FROM posts')).rows.length,0);});
    await check('owner console runs through the restricted PostgreSQL connection',async()=>{const ops=new PilotOperations(new WorkspaceRepository(runtime!),{NODE_ENV:'test',DATABASE_URL:url.toString()});const status=await ops.snapshot('code-black',DEMO_ADMIN);assert.equal(status.checks.find(x=>x.key==='runtime-role')!.state,'pass');assert.equal(status.community.activeMembers,8);});
    await check('rich lessons publish and restore through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!);
        const exec=(cmd:unknown)=>repo.execute('code-black',DEMO_ADMIN,cmd,randomUUID(),'rich-postgres');
        let r=await exec({type:'lesson.draft.create',trackId:'track_product',lessonId:'lesson_4'}),d=r.workspace.lessonDrafts[0];
        const richBody=plainLessonDocument('Private rich lesson for PostgreSQL');richBody.content[0].content![0].marks=[{type:'bold'}];
        r=await exec({type:'lesson.draft.save',draftId:d.id,expectedVersion:d.version,...lessonContent(d),richBody});d=r.workspace.lessonDrafts[0];
        assert.deepEqual(d.richBody,richBody);
        assert(!JSON.stringify(await repo.snapshot('code-black',DEMO_USER)).includes('Private rich lesson for PostgreSQL'));
        r=await exec({type:'lesson.draft.publish',draftId:d.id,expectedVersion:d.version});
        assert.deepEqual((await repo.snapshot('code-black',DEMO_USER)).lessons.find(l=>l.id==='lesson_4')!.richBody,richBody);
        assert(!JSON.stringify(await repo.snapshot('studio-north',DEMO_ADMIN)).includes('Private rich lesson for PostgreSQL'));
        r=await exec({type:'lesson.draft.restore',draftId:d.id,expectedVersion:d.version,revisionId:r.workspace.lessonRevisions[0].id});
        assert.equal(r.workspace.lessonDrafts[0].richBody,null);
        assert.deepEqual(r.workspace.lessons.find(l=>l.id==='lesson_4')!.richBody,richBody);
        await assert.rejects(()=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_ADMIN);await tx.query('UPDATE lesson_revisions SET rich_body=NULL');}));
    });
    await check('lesson files verify, publish and stay tenant-private through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),pdf=new TextEncoder().encode('%PDF-1.4\n% fictional PostgreSQL lesson file\n');
        const {upload}=await repo.beginResourceUpload('code-black',DEMO_ADMIN,{purpose:'lesson_resource',trackId:'track_product',name:'Postgres guide.pdf',contentType:'application/pdf',sizeBytes:pdf.length},(org,id)=>`organisations/${org}/lesson-resources/track_product/${id}.pdf`,'resources-postgres');
        assert.equal((await repo.completeResourceUpload('code-black',DEMO_ADMIN,upload.id,{sizeBytes:pdf.length,contentType:'application/pdf',generation:'1712345678901234',signatureMatches:true},'resources-postgres')).outcome,'ready');
        const exec=(cmd:unknown)=>repo.execute('code-black',DEMO_ADMIN,cmd,randomUUID(),'resources-postgres');
        let r=await exec({type:'lesson.draft.create',trackId:'track_product',lessonId:'lesson_4'}),d=r.workspace.lessonDrafts[0];
        r=await exec({type:'lesson.draft.save',draftId:d.id,expectedVersion:d.version,...lessonContent(d),resources:[...lessonContent(d).resources,{id:'resource_pg',fileId:upload.id,name:'Postgres guide'}]});d=r.workspace.lessonDrafts[0];
        const files=(org:string,user:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<{id:string}>("SELECT id FROM upload_intents WHERE purpose='lesson_resource'")).rows.map(x=>x.id);});
        assert(!(await files('org_code_black',DEMO_USER)).includes(upload.id));assert((await files('org_code_black',DEMO_ADMIN)).includes(upload.id));
        await assert.rejects(()=>repo.resourceDownload('code-black',DEMO_USER,{context:'lesson',recordId:'lesson_4',resourceId:'resource_pg'}),{code:'NOT_FOUND'});
        await exec({type:'lesson.draft.publish',draftId:d.id,expectedVersion:d.version});
        assert((await files('org_code_black',DEMO_USER)).includes(upload.id));assert.deepEqual(await files('org_studio_north',DEMO_ADMIN),[]);
        assert.equal((await repo.resourceDownload('code-black',DEMO_USER,{context:'lesson',recordId:'lesson_4',resourceId:'resource_pg'})).filename,'Postgres guide.pdf');
        await assert.rejects(()=>repo.resourceDownload('studio-north',DEMO_USER,{context:'lesson',recordId:'lesson_4',resourceId:'resource_pg'}),{code:'NOT_FOUND'});
        await assert.rejects(()=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_ADMIN);await tx.query("UPDATE lesson_revisions SET resources='[]'::jsonb");}));
    });
    await mkdir('evidence/alpha04',{recursive:true});await writeFile('evidence/alpha04/postgres-results.json',JSON.stringify({generatedAt:new Date().toISOString(),method:'Disposable local PostgreSQL service, not Neon.',results},null,2));
}finally{await runtime?.close();await admin.close();}
