import { RetentionJob } from '../packages/db/src/retention';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { plainLessonDocument } from '../packages/contracts/src/lesson-document';
import { lessonContent } from '../packages/domain/src/authoring';
import { quizFingerprint } from '../packages/contracts/src/assessments';
/** Opt-in integration test against a disposable local PostgreSQL CI service, never Neon/customer data. */
import {strict as assert} from 'node:assert';
import {mkdir,writeFile} from 'node:fs/promises';
import {openDatabase} from '../packages/db/src/connection';
import {migrate} from '../packages/db/src/migrate';
import {grantRuntimeTables} from '../packages/db/src/runtime-role';
import {runtimeRoleIsSafe} from '../packages/db/src/runtime-safety';
import {WorkspaceRepository,setContext} from '../packages/db/src/repository';
import {createSeed,DEMO_USER,DEMO_ADMIN} from '../packages/domain/src/seed';
import {PilotOperations} from '../apps/api/src/operations';
import {InvitationService} from '../apps/api/src/invitations';
import {MailQueue} from '../apps/api/src/mail';
import {DigestService} from '../apps/api/src/digests';
import {inspectMigrations} from '../packages/db/src/inspection';
import {MessagingRepository} from '../packages/db/src/messaging';
const url=new URL(process.env.POSTGRES_TEST_URL||'http://unconfigured');
if(!['postgres:','postgresql:'].includes(url.protocol)||!['127.0.0.1','localhost','[::1]'].includes(url.hostname)||url.pathname!=='/reunir_ci')throw new Error('This test requires a disposable loopback database named reunir_ci. It cannot target remote or customer databases.');
const admin=await openDatabase(url.toString());
const results:{name:string;passed:boolean}[]=[];const check=async(name:string,fn:()=>Promise<void>)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
let runtime:Awaited<ReturnType<typeof openDatabase>>|undefined;
try{
    const existing=await admin.query("SELECT tablename FROM pg_tables WHERE schemaname='public'");
    assert.equal(existing.rows.length,0,'CI database must be empty; existing data has not been overwritten.');
    await check('ordered migrations apply on actual PostgreSQL',async()=>{await migrate(admin);assert((await inspectMigrations(admin)).every(r=>r.state==='matching'));});
    const seed=new WorkspaceRepository(admin);await seed.seed(createSeed());await seed.seed(createSeed('studio-north'));
    await admin.query("CREATE ROLE reunir_app LOGIN PASSWORD 'LOCAL_CI_TEST_ONLY_12345678901234567890' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS");
    await admin.transaction(grantRuntimeTables);url.username='reunir_app';url.password='LOCAL_CI_TEST_ONLY_12345678901234567890';runtime=await openDatabase(url.toString());
    await check('separate runtime connection is non-owner and cannot bypass RLS',async()=>{assert(await runtimeRoleIsSafe(runtime!));await assert.rejects(()=>runtime!.query('SELECT * FROM schema_migrations'));});
    await check('the runtime role is granted the two-step sign-in table (migration 0021)',async()=>{for(const action of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal((await admin.query<{ok:boolean}>("SELECT has_table_privilege('reunir_app','auth_two_factor',$1) AS ok",[action])).rows[0].ok,true,action);assert.equal((await runtime!.query<{n:number}>('SELECT count(*)::int AS n FROM auth_two_factor')).rows[0].n,0);});
    await check('the runtime role may change only the decision fields of moderation appeals (migration 0031)',async()=>{
        const table=async(p:string)=>(await admin.query<{ok:boolean}>("SELECT has_table_privilege('reunir_app','moderation_appeals',$1) AS ok",[p])).rows[0].ok;
        const column=async(c:string)=>(await admin.query<{ok:boolean}>("SELECT has_column_privilege('reunir_app','moderation_appeals',$1,'UPDATE') AS ok",[c])).rows[0].ok;
        for(const p of ['SELECT','INSERT','DELETE'])assert.equal(await table(p),true,p);
        assert.equal(await table('UPDATE'),false,'no table-wide UPDATE');
        for(const c of ['status','decided_by','decided_at','response'])assert.equal(await column(c),true,c);
        for(const c of ['reason','appellant_id','subject_id','subject','created_at'])assert.equal(await column(c),false,c);
        for(const c of ['moderated_by','moderated_at'])assert.equal((await admin.query<{ok:boolean}>("SELECT has_column_privilege('reunir_app','posts',$1,'UPDATE') AS ok",[c])).rows[0].ok,true,c);
        const rls=(await admin.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>("SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='moderation_appeals'")).rows[0];
        assert.deepEqual(rls,{relrowsecurity:true,relforcerowsecurity:true});
    });
    await check('people added to a group later read only newer messages, and leaving works, under row security (migration 0022)',async()=>{
        const m=new MessagingRepository(new WorkspaceRepository(runtime!));
        const g=(await m.startGroup('code-black',DEMO_USER,{title:'Postgres crew',userIds:[DEMO_ADMIN,'member_theo']})).id;
        await m.send('code-black',DEMO_USER,g,'Before Jordan joined.','pg-group-1');
        await m.add('code-black','member_theo',g,{userIds:['member_jordan']});
        await m.send('code-black','member_jordan',g,'After I joined.','pg-group-2');
        assert.deepEqual((await m.messages('code-black','member_jordan',g)).items.map(x=>x.body),['After I joined.']);
        await runtime!.transaction(async tx=>{await setContext(tx,'org_code_black','member_jordan');assert.equal((await tx.query('SELECT id FROM messages WHERE conversation_id=$1',[g])).rows.length,1);});
        await m.leave('code-black',DEMO_ADMIN,g);
        await assert.rejects(()=>m.messages('code-black',DEMO_ADMIN,g));
        assert.equal((await m.messages('code-black',DEMO_USER,g)).items.length,2);
        assert.equal((await admin.query<{ok:boolean}>("SELECT has_table_privilege('reunir_app','conversation_joins','INSERT') AS ok")).rows[0].ok,true);
    });
    await check('the retention job lists communities only as its own worker, then clears housekeeping as the runtime role (migration 0030)',async()=>{
        const listed=(worker:string)=>runtime!.transaction(async tx=>{await tx.query("SELECT set_config('app.worker',$1,true)",[worker]);return (await tx.query('SELECT id FROM organisations')).rows.length;});
        assert.equal(await listed(''),0);assert.ok(await listed('retention')>0);
        await admin.query("INSERT INTO request_limits(key,count,window_start) VALUES('retention-check',1,now()-interval '3 days')");
        const dry=await new RetentionJob(runtime!).run(new Date(),false);assert.ok(dry.counts.rateCounters>=1);
        assert.equal((await admin.query("SELECT 1 FROM request_limits WHERE key='retention-check'")).rows.length,1,'a dry run changes nothing');
        await new RetentionJob(runtime!).run(new Date(),true);
        assert.equal((await admin.query("SELECT 1 FROM request_limits WHERE key='retention-check'")).rows.length,0);});
    await check('curated collections: drafts stay with the team, writes are curators’ only and one collection is featured',async()=>{
        const repo=new WorkspaceRepository(runtime!);
        const ids=(org:string,user:string,sql:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<{id:string}>(sql)).rows.map(r=>r.id);});
        assert.deepEqual(await ids('org_code_black',DEMO_USER,'SELECT id FROM collections ORDER BY id'),['collection_start']);
        assert.deepEqual(await ids('org_code_black','member_maya','SELECT id FROM collections ORDER BY id'),['collection_feedback','collection_start']);
        assert.deepEqual(await ids('org_studio_north',DEMO_ADMIN,'SELECT id FROM collections'),[]);
        assert(!(await repo.snapshot('code-black',DEMO_USER)).collectionItems.some(i=>i.id==='collected_team_notes'),'the team-only post never reaches a member');
        await assert.rejects(()=>repo.execute('code-black',DEMO_USER,{type:'collection.save',title:'Mine'},randomUUID(),'collections-postgres'),{code:'CURATOR_REQUIRED'});
        const made=await repo.execute('code-black','member_maya',{type:'collection.save',title:'Worth an evening'},randomUUID(),'collections-postgres');
        await repo.execute('code-black','member_maya',{type:'collection.item.add',collectionId:made.objectId,kind:'track',targetId:'track_story',note:''},randomUUID(),'collections-postgres');
        await repo.execute('code-black','member_maya',{type:'collection.publish',collectionId:made.objectId,published:true},randomUUID(),'collections-postgres');
        await repo.execute('code-black',DEMO_ADMIN,{type:'collection.feature',collectionId:made.objectId,featured:true},randomUUID(),'collections-postgres');
        assert.deepEqual(await ids('org_code_black',DEMO_USER,'SELECT id FROM collections WHERE featured'),[made.objectId]);
        await assert.rejects(()=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_ADMIN);await tx.query("UPDATE collection_items SET post_id='post_win' WHERE id='collected_welcome'");}),'what an item points at is fixed');
        await assert.rejects(()=>admin.transaction(async tx=>{await tx.query("UPDATE collections SET featured=true WHERE organization_id='org_code_black' AND status='published'");}),'one featured collection per community');
        await runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_USER);await tx.query("DELETE FROM collection_items");});
        assert.equal((await admin.query<{n:number}>("SELECT count(*)::int AS n FROM collection_items WHERE organization_id='org_code_black'")).rows[0].n,8,'a member removes nothing');
    });
    await check('missing tenant context denies rows on a fresh connection',async()=>{assert.equal((await runtime!.query('SELECT id FROM posts')).rows.length,0);});
    await check('parallel connection-pool reads keep two tenant contexts separate',async()=>{const repo=new WorkspaceRepository(runtime!);const slugs=Array.from({length:20},(_,i)=>i%2?'code-black':'studio-north');const rows=await Promise.all(slugs.map(s=>repo.snapshot(s,DEMO_USER)));rows.forEach((r,i)=>assert.equal(r.organisation.slug,slugs[i]));});
    await check('transaction context is reset before a pooled connection is reused',async()=>{await runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_USER);assert((await tx.query('SELECT id FROM posts')).rows.length>0);});assert.equal((await runtime!.query('SELECT id FROM posts')).rows.length,0);});
    await check('owner console runs through the restricted PostgreSQL connection',async()=>{const ops=new PilotOperations(new WorkspaceRepository(runtime!),{NODE_ENV:'test',DATABASE_URL:url.toString()});const status=await ops.snapshot('code-black',DEMO_ADMIN);assert.equal(status.checks.find(x=>x.key==='runtime-role')!.state,'pass');assert.equal(status.community.activeMembers,8);});
    await check('rich lessons publish and restore through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!);
        const exec=(cmd:unknown)=>repo.execute('code-black',DEMO_ADMIN,cmd,randomUUID(),'rich-postgres');
        let r=await exec({type:'lesson.draft.create',trackId:'track_product',lessonId:'lesson_4'}),d=r.workspace.lessonDrafts[0];
        const richBody=plainLessonDocument('Private rich lesson for PostgreSQL');richBody.content[0].content![0].marks=[{type:'bold'}];
        r=await exec({type:'lesson.draft.save',draftId:d.id,expectedVersion:d.version,...lessonContent(d),richBody});d=r.workspace.lessonDrafts[0];
        assert.deepEqual(d.richBody,richBody);
        assert(!JSON.stringify(await repo.snapshot('code-black',DEMO_USER)).includes('Private rich lesson for PostgreSQL'));
        r=await exec({type:'lesson.draft.publish',draftId:d.id,expectedVersion:d.version});
        assert.deepEqual((await repo.snapshot('code-black',DEMO_USER)).lessons.find(l=>l.id==='lesson_4')!.richBody,richBody);
        assert(!JSON.stringify(await repo.snapshot('studio-north',DEMO_ADMIN)).includes('Private rich lesson for PostgreSQL'));
        r=await exec({type:'lesson.draft.restore',draftId:d.id,expectedVersion:d.version,revisionId:r.workspace.lessonRevisions[0].id});
        assert.equal(r.workspace.lessonDrafts[0].richBody,null);
        assert.deepEqual(r.workspace.lessons.find(l=>l.id==='lesson_4')!.richBody,richBody);
        await assert.rejects(()=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_ADMIN);await tx.query('UPDATE lesson_revisions SET rich_body=NULL');}));
    });
    await check('lesson files verify, publish and stay tenant-private through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),pdf=new TextEncoder().encode('%PDF-1.4\n% fictional PostgreSQL lesson file\n');
        const {upload}=await repo.beginResourceUpload('code-black',DEMO_ADMIN,{purpose:'lesson_resource',trackId:'track_product',name:'Postgres guide.pdf',contentType:'application/pdf',sizeBytes:pdf.length},(org,id)=>`organisations/${org}/lesson-resources/track_product/${id}.pdf`,'resources-postgres');
        assert.equal((await repo.completeResourceUpload('code-black',DEMO_ADMIN,upload.id,{sizeBytes:pdf.length,contentType:'application/pdf',generation:'1712345678901234',signatureMatches:true},'resources-postgres')).outcome,'ready');
        const exec=(cmd:unknown)=>repo.execute('code-black',DEMO_ADMIN,cmd,randomUUID(),'resources-postgres');
        let r=await exec({type:'lesson.draft.create',trackId:'track_product',lessonId:'lesson_4'}),d=r.workspace.lessonDrafts[0];
        r=await exec({type:'lesson.draft.save',draftId:d.id,expectedVersion:d.version,...lessonContent(d),resources:[...lessonContent(d).resources,{id:'resource_pg',fileId:upload.id,name:'Postgres guide'}]});d=r.workspace.lessonDrafts[0];
        const files=(org:string,user:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<{id:string}>("SELECT id FROM upload_intents WHERE purpose='lesson_resource'")).rows.map(x=>x.id);});
        assert(!(await files('org_code_black',DEMO_USER)).includes(upload.id));assert((await files('org_code_black',DEMO_ADMIN)).includes(upload.id));
        await assert.rejects(()=>repo.resourceDownload('code-black',DEMO_USER,{context:'lesson',recordId:'lesson_4',resourceId:'resource_pg'}),{code:'NOT_FOUND'});
        await exec({type:'lesson.draft.publish',draftId:d.id,expectedVersion:d.version});
        assert((await files('org_code_black',DEMO_USER)).includes(upload.id));assert.deepEqual(await files('org_studio_north',DEMO_ADMIN),[]);
        assert.equal((await repo.resourceDownload('code-black',DEMO_USER,{context:'lesson',recordId:'lesson_4',resourceId:'resource_pg'})).filename,'Postgres guide.pdf');
        await assert.rejects(()=>repo.resourceDownload('studio-north',DEMO_USER,{context:'lesson',recordId:'lesson_4',resourceId:'resource_pg'}),{code:'NOT_FOUND'});
        await assert.rejects(()=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_ADMIN);await tx.query("UPDATE lesson_revisions SET resources='[]'::jsonb");}));
    });
    await check('knowledge checks score, review and stay evidence through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!);
        const exec=(cmd:unknown,user=DEMO_USER)=>repo.execute('code-black',user,cmd,randomUUID(),'assessments-postgres');
        const rows=(org:string,user:string,sql:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<Record<string,unknown>>(sql)).rows;});
        const seen=(await repo.snapshot('code-black',DEMO_USER)).lessons.find(l=>l.id==='lesson_5')!.quiz!;
        assert(!JSON.stringify(seen).includes('acceptedAnswers'),'members receive no answer keys');
        const r=await exec({type:'quiz.attempt.submit',lessonId:'lesson_5',fingerprint:quizFingerprint(seen),answers:[{questionId:'q5_feedback',optionIds:['a']},{questionId:'q5_essentials',optionIds:['a','b']},{questionId:'q5_outcome',text:'Useful'}]});
        const mine=r.workspace.quizAttempts.find(a=>a.userId===DEMO_USER)!;assert.deepEqual([mine.status,mine.score,mine.passed],['scored',4,true]);
        await exec({type:'quiz.attempt.review',attemptId:'attempt_sofia',expectedVersion:1,marks:[{questionId:'q6_change',points:2}],feedback:'Observed and specific.'},DEMO_ADMIN);
        assert.deepEqual((await rows('org_code_black','member_sofia','SELECT status,score,reviewer_id FROM quiz_attempts')),[{status:'reviewed',score:3,reviewer_id:DEMO_ADMIN}]);
        assert.deepEqual((await rows('org_code_black',DEMO_USER,'SELECT user_id FROM quiz_attempts')).map(x=>x.user_id),[DEMO_USER]);
        assert.equal((await rows('org_studio_north',DEMO_ADMIN,'SELECT id FROM quiz_attempts')).length,0);
        await assert.rejects(()=>rows('org_code_black',DEMO_ADMIN,"UPDATE quiz_attempts SET answers='[]'::jsonb"),/permission denied/);
        assert.equal((await rows('org_code_black',DEMO_ADMIN,'DELETE FROM quiz_attempts RETURNING id')).length,0,'no attempt is deleted outside a member’s own account deletion');
        assert.equal((await rows('org_code_black',DEMO_USER,"UPDATE quiz_attempts SET feedback='Forged' WHERE id='attempt_sofia' RETURNING id")).length,0);
        assert.equal((await rows('org_code_black',DEMO_ADMIN,"UPDATE quiz_attempts SET feedback='Rewritten',score=0,version=2 WHERE id='attempt_sofia' RETURNING id")).length,0,'a finished review cannot be rewritten');
    });
    await check('covers verify, display and stay tenant-scoped through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!);
        const {upload}=await repo.beginCoverUpload('code-black',DEMO_ADMIN,{purpose:'cover_image',subject:'track',subjectId:'track_story',contentType:'image/png',sizeBytes:4096},(org,id)=>`organisations/${org}/covers/tracks/track_story/${id}.png`,'covers-postgres');
        assert.equal((await repo.completeCoverUpload('code-black',DEMO_ADMIN,upload.id,{sizeBytes:4096,contentType:'image/png',generation:'1712345678909999',bytesAcceptable:true},'covers-postgres')).outcome,'ready');
        const covers=(org:string,user:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<{id:string}>("SELECT id FROM upload_intents WHERE purpose='cover_image'")).rows.map(x=>x.id);});
        assert(!(await covers('org_code_black',DEMO_USER)).includes(upload.id),'members cannot read a cover nothing displays');
        await assert.rejects(()=>repo.coverImage('code-black',DEMO_USER,'track','track_story',upload.id),{code:'NOT_FOUND'});
        await assert.rejects(()=>repo.execute('code-black',DEMO_USER,{type:'track.cover.set',trackId:'track_story',fileId:upload.id},randomUUID(),'covers-postgres'),{code:'COVER_EDITOR_REQUIRED'});
        await repo.execute('code-black',DEMO_ADMIN,{type:'track.cover.set',trackId:'track_story',fileId:upload.id,focusX:40,focusY:60},randomUUID(),'covers-postgres');
        assert((await covers('org_code_black',DEMO_USER)).includes(upload.id));assert.deepEqual(await covers('org_studio_north',DEMO_ADMIN),[]);
        assert.deepEqual(await repo.coverImage('code-black',DEMO_USER,'track','track_story',upload.id),{objectKey:`organisations/org_code_black/covers/tracks/track_story/${upload.id}.png`,generation:'1712345678909999',contentType:'image/png',sizeBytes:4096});
        await assert.rejects(()=>repo.coverImage('studio-north',DEMO_USER,'track','track_story',upload.id),{code:'NOT_FOUND'});
        await repo.execute('code-black',DEMO_ADMIN,{type:'track.cover.set',trackId:'track_story',fileId:null},randomUUID(),'covers-postgres');
        assert(!(await covers('org_code_black',DEMO_USER)).includes(upload.id),'a removed cover is private again');
    });
    await check('track instructors author and review only their own track through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),IDRIS='member_idris';
        const exec=(cmd:unknown,user:string)=>repo.execute('code-black',user,cmd,randomUUID(),'instructors-postgres');
        const rows=(user:string,sql:string)=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',user);return (await tx.query<Record<string,unknown>>(sql)).rows;});
        await exec({type:'lesson.draft.create',trackId:'track_product'},IDRIS);
        await assert.rejects(()=>exec({type:'lesson.draft.create',trackId:'track_story'},IDRIS),{code:'NOT_FOUND'});
        assert.deepEqual((await rows(IDRIS,'SELECT DISTINCT track_id FROM lesson_drafts')).map(r=>r.track_id),['track_product']);
        assert.deepEqual(await rows(DEMO_USER,'SELECT id FROM lesson_drafts'),[]);
        const seen=(await repo.snapshot('code-black',DEMO_USER)).lessons.find(l=>l.id==='lesson_6')!.quiz!;
        const attempt=(await exec({type:'quiz.attempt.submit',lessonId:'lesson_6',fingerprint:quizFingerprint(seen),answers:[{questionId:'q6_watch',optionIds:['a']},{questionId:'q6_change',text:'Autosave, because people lost their work.'}]},DEMO_USER)).objectId!;
        await exec({type:'quiz.attempt.review',attemptId:attempt,expectedVersion:1,marks:[{questionId:'q6_change',points:2}],feedback:'Observed and specific.'},IDRIS);
        assert.deepEqual(await rows(IDRIS,`SELECT status,reviewer_id FROM quiz_attempts WHERE id='${attempt}'`),[{status:'reviewed',reviewer_id:IDRIS}]);
        await assert.rejects(()=>rows(IDRIS,"INSERT INTO track_instructors(id,organization_id,created_at,track_id,user_id,granted_by) VALUES('g_pg','org_code_black',now(),'track_story','member_idris','member_idris')"),/row-level security/);
        await assert.rejects(()=>rows(DEMO_ADMIN,"UPDATE track_instructors SET track_id='track_story'"),/permission denied/);
    });
    await check('the cover library lists, serves and removes pictures through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),key=(org:string,id:string)=>`organisations/${org}/covers/library/${id}.png`;
        const exec=(cmd:unknown,user:string)=>repo.execute('code-black',user,cmd,randomUUID(),'library-postgres');
        const rows=(user:string,sql:string)=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',user);return (await tx.query<Record<string,unknown>>(sql)).rows;});
        await assert.rejects(()=>repo.beginCoverLibraryUpload('code-black',DEMO_USER,{purpose:'cover_library',contentType:'image/png',sizeBytes:4096},key,'library-postgres'),{code:'ADMIN_REQUIRED'});
        const {upload}=await repo.beginCoverLibraryUpload('code-black',DEMO_ADMIN,{purpose:'cover_library',contentType:'image/png',sizeBytes:4096},key,'library-postgres');
        assert.equal((await repo.completeCoverUpload('code-black',DEMO_ADMIN,upload.id,{sizeBytes:4096,contentType:'image/png',generation:'1712345678908888',bytesAcceptable:true},'library-postgres')).outcome,'ready');
        const unlisted=async()=>(await rows(DEMO_USER,"SELECT id FROM upload_intents WHERE purpose='cover_library'")).map(r=>r.id);
        assert(!(await unlisted()).includes(upload.id),'members cannot read an unlisted picture');
        const item=(await exec({type:'cover.library.add',fileId:upload.id,label:'Harbour'},DEMO_ADMIN)).objectId!;
        assert((await unlisted()).includes(upload.id));
        assert.deepEqual(await repo.coverLibraryPicture('code-black',DEMO_USER,item),{objectKey:key('org_code_black',upload.id),generation:'1712345678908888',contentType:'image/png',sizeBytes:4096});
        await assert.rejects(()=>repo.coverLibraryPicture('studio-north',DEMO_USER,item),{code:'NOT_FOUND'});
        await exec({type:'project.cover.set',projectId:'project_still',fileId:upload.id},'member_jordan');
        await assert.rejects(()=>repo.removeCoverLibraryItem('code-black',DEMO_ADMIN,item,'library-postgres'),{code:'COVER_IN_USE'});
        await assert.rejects(()=>rows(DEMO_USER,`INSERT INTO cover_library(id,organization_id,created_at,file_id,label,content_type,size_bytes,added_by) VALUES('l_pg','org_code_black',now(),'${upload.id}','x','image/png',4096,'${DEMO_USER}')`),/row-level security/);
        await assert.rejects(()=>rows(DEMO_ADMIN,"UPDATE cover_library SET file_id='other'"),/permission denied/);
        await exec({type:'project.cover.set',projectId:'project_still',fileId:null},'member_jordan');
        assert.deepEqual(await repo.removeCoverLibraryItem('code-black',DEMO_ADMIN,item,'library-postgres'),{id:item,objectKey:key('org_code_black',upload.id),thumbnailObjectKey:null});
        assert.deepEqual(await rows(DEMO_ADMIN,`SELECT id FROM upload_intents WHERE id='${upload.id}'`),[]);
    });
    await check('a hidden post is appealed and reversed, private to the appellant and administrators, through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),MAYA='member_maya',NIA='member_nia';
        const exec=(cmd:unknown,user:string)=>repo.execute('code-black',user,cmd,randomUUID(),'appeals-postgres');
        const rows=(org:string,user:string,sql:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<Record<string,unknown>>(sql)).rows;});
        await exec({type:'post.moderate',postId:'post_win',hidden:true},MAYA);
        assert.deepEqual(await rows('org_code_black',NIA,"SELECT hidden,moderated_by FROM posts WHERE id='post_win'"),[{hidden:true,moderated_by:MAYA}]);
        const id=(await exec({type:'moderation.appeal',postId:'post_win',reason:'A celebration, not an advert.'},NIA)).objectId!;
        await assert.rejects(()=>exec({type:'moderation.appeal',postId:'post_win',reason:'Twice.'},NIA),{code:'APPEAL_OPEN'});
        assert.equal((await rows('org_code_black',NIA,'SELECT id FROM moderation_appeals')).length,1);
        assert.equal((await rows('org_code_black',DEMO_ADMIN,'SELECT id FROM moderation_appeals')).length,1);
        assert.deepEqual(await rows('org_code_black',MAYA,'SELECT id FROM moderation_appeals'),[],'the moderator does not read appeals');
        assert.deepEqual(await rows('org_code_black',DEMO_USER,'SELECT id FROM moderation_appeals'),[]);
        assert.deepEqual(await rows('org_studio_north',DEMO_ADMIN,'SELECT id FROM moderation_appeals'),[],'another community reads none');
        await assert.rejects(()=>exec({type:'moderation.appeal.decide',appealId:id,decision:'reversed',response:'Mine?'},MAYA),{code:'NOT_FOUND'});
        await rows('org_code_black',MAYA,`UPDATE moderation_appeals SET status='reversed',decided_by='${MAYA}',decided_at=now() WHERE id='${id}'`);
        await assert.rejects(()=>rows('org_code_black',DEMO_ADMIN,`UPDATE moderation_appeals SET reason='Rewritten' WHERE id='${id}'`),/permission denied/);
        await exec({type:'moderation.appeal.decide',appealId:id,decision:'reversed',response:'Restored. Celebrations are welcome.'},DEMO_ADMIN);
        assert.deepEqual(await rows('org_code_black',NIA,`SELECT status,decided_by,reason FROM moderation_appeals WHERE id='${id}'`),[{status:'reversed',decided_by:DEMO_ADMIN,reason:'A celebration, not an advert.'}]);
        assert((await repo.snapshot('code-black',DEMO_USER)).posts.some(p=>p.id==='post_win'),'members see the restored post');
        await assert.rejects(()=>rows('org_code_black',DEMO_USER,"INSERT INTO moderation_appeals(id,organization_id,created_at,subject,subject_id,appellant_id,reason) VALUES('forged_pg','org_code_black',now(),'post','post_common','member_alex','Forged')"),/row-level security/);
    });
    await check('library pictures are renamed and tagged, and covers keep verified small copies, through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!);
        const rows=(user:string,org:string,sql:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<Record<string,unknown>>(sql)).rows;});
        assert.deepEqual(await repo.updateCoverLibraryItem('code-black',DEMO_ADMIN,'library_mountain',{label:'Ridge at noon',tags:['Hills','hills']},'library-postgres'),{id:'library_mountain',label:'Ridge at noon',tags:['hills'],changed:true});
        await assert.rejects(()=>repo.updateCoverLibraryItem('code-black',DEMO_USER,'library_mountain',{label:'Mine',tags:[]},'library-postgres'),{code:'ADMIN_REQUIRED'});
        await assert.rejects(()=>repo.updateCoverLibraryItem('studio-north',DEMO_ADMIN,'library_mountain',{label:'Taken',tags:[]},'library-postgres'),{code:'NOT_FOUND'});
        assert.deepEqual(await rows(DEMO_USER,'org_code_black',"UPDATE cover_library SET label='Member' RETURNING id"),[],'a member\u2019s update matches nothing');
        assert.deepEqual(await rows(DEMO_ADMIN,'org_studio_north',"UPDATE cover_library SET label='Elsewhere' WHERE organization_id='org_code_black' RETURNING id"),[],'another community\u2019s rows are out of sight');
        await admin.query("UPDATE members SET status='suspended' WHERE organization_id='org_code_black' AND user_id=$1",[DEMO_ADMIN]);
        try { assert.deepEqual(await rows(DEMO_ADMIN,'org_code_black',"UPDATE cover_library SET label='Suspended' RETURNING id"),[],'a suspended owner updates nothing'); }
        finally { await admin.query("UPDATE members SET status='active' WHERE organization_id='org_code_black' AND user_id=$1",[DEMO_ADMIN]); }
        await assert.rejects(()=>rows(DEMO_ADMIN,'org_code_black',`UPDATE cover_library SET tags='["Upper"]'::jsonb`),/check constraint/);
        await repo.updateCoverLibraryItem('code-black',DEMO_ADMIN,'library_mountain',{label:'Mountain ridge',tags:['landscape','outdoors']},'library-postgres');
        const key=(org:string,id:string)=>`organisations/${org}/covers/tracks/track_story/${id}.png`,thumb=(org:string,id:string)=>`organisations/${org}/covers/tracks/track_story/${id}-thumb.webp`;
        const {upload}=await repo.beginCoverUpload('code-black',DEMO_ADMIN,{purpose:'cover_image',subject:'track',subjectId:'track_story',contentType:'image/png',sizeBytes:4096,thumbnail:{contentType:'image/webp',sizeBytes:2048}},key,'library-postgres',thumb);
        const done=await repo.completeCoverUpload('code-black',DEMO_ADMIN,upload.id,{sizeBytes:4096,contentType:'image/png',generation:'1712345678907777',bytesAcceptable:true,thumbnail:{sizeBytes:2048,contentType:'image/webp',generation:'1712345678907778',bytesAcceptable:true}},'library-postgres');
        assert.equal(done.upload.thumbnailGeneration,'1712345678907778');
        await repo.execute('code-black',DEMO_ADMIN,{type:'track.cover.set',trackId:'track_story',fileId:upload.id,focusX:50,focusY:50},randomUUID(),'library-postgres');
        assert.deepEqual(await repo.coverImage('code-black',DEMO_USER,'track','track_story',upload.id,'thumbnail'),{objectKey:thumb('org_code_black',upload.id),generation:'1712345678907778',contentType:'image/webp',sizeBytes:2048});
        const {releasedFiles}=await repo.executeCommand('code-black',DEMO_ADMIN,{type:'track.cover.set',trackId:'track_story',fileId:null},randomUUID(),'library-postgres');
        assert.deepEqual(releasedFiles,[key('org_code_black',upload.id),thumb('org_code_black',upload.id)]);
    });
    await check('an owner-authorised erasure removes one member\u2019s answers through a role without row-security bypass',async()=>{
        // A stand-in for a hosted migration role: table privileges, but no superuser and no BYPASSRLS.
        await admin.query('CREATE ROLE reunir_operator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS');
        await admin.query('GRANT USAGE ON SCHEMA public TO reunir_operator');await admin.query('GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO reunir_operator');
        const scoped=Object.create(admin) as typeof admin;scoped.transaction=fn=>admin.transaction(async tx=>{await tx.query('SET LOCAL ROLE reunir_operator');return fn(tx);});
        const operator=new WorkspaceRepository(scoped),left=async()=>(await admin.query<{n:number}>("SELECT count(*)::int AS n FROM quiz_attempts WHERE organization_id='org_code_black' AND user_id='member_sofia'")).rows[0].n;
        const planned=await operator.eraseLearnerAnswers('code-black',DEMO_ADMIN,'member_sofia','request pg-1',false);
        assert(planned.attempts>=1);assert.equal(await left(),planned.attempts,'a dry run changes nothing');
        await assert.rejects(()=>operator.eraseLearnerAnswers('code-black',DEMO_USER,'member_sofia','request pg-1',true),{code:'OWNER_REQUIRED'});
        assert.deepEqual(await operator.eraseLearnerAnswers('code-black',DEMO_ADMIN,'member_sofia','request pg-1',true),{...planned,applied:true});
        assert.equal(await left(),0);
        assert.deepEqual((await admin.query("SELECT metadata FROM audit WHERE action='learner.answers.erased' AND object_id='member_sofia'")).rows,[{metadata:{reference:'request pg-1',attempts:planned.attempts,notifications:planned.notifications}}]);
        assert.equal(await runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',DEMO_ADMIN);await tx.query("SELECT set_config('app.erasure_subject','member_alex',true)");return (await tx.query("DELETE FROM quiz_attempts WHERE user_id='member_alex' RETURNING id")).rows.length;}),0,'the runtime role cannot use the operator erasure');
    });
    await check('unused cover files are listed and cleared through a role without row-security bypass',async()=>{
        const scoped=Object.create(admin) as typeof admin;scoped.transaction=fn=>admin.transaction(async tx=>{await tx.query('SET LOCAL ROLE reunir_operator');return fn(tx);});
        const operator=new WorkspaceRepository(scoped);
        await admin.query("INSERT INTO upload_intents(organization_id,id,user_id,object_key,content_type,size_bytes,original_name,created_at,status,purpose,cover_track_id) VALUES('org_code_black','pg_stale_cover','member_amina','k-pg-stale','image/png',10,'c',now()-interval '2 hours','pending','cover_image','track_story'),('org_code_black','pg_fresh_cover','member_amina','k-pg-fresh','image/png',10,'c',now(),'pending','cover_image','track_story')");
        await assert.rejects(()=>operator.staleCoverUploads('code-black',DEMO_USER),{code:'OWNER_REQUIRED'});
        const stale=(await operator.staleCoverUploads('code-black',DEMO_ADMIN)).map(u=>u.id);
        assert(stale.includes('pg_stale_cover')&&!stale.includes('pg_fresh_cover'));
        assert.deepEqual(await operator.removeStaleCoverUploads('code-black',DEMO_ADMIN,['pg_stale_cover','pg_fresh_cover']),['pg_stale_cover']);
        assert.deepEqual((await admin.query("SELECT id FROM upload_intents WHERE id IN ('pg_stale_cover','pg_fresh_cover')")).rows,[{id:'pg_fresh_cover'}]);
    });
    await check('task files verify and stay with the project team, and task edits refuse lost updates, through a restricted PostgreSQL connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),lead='member_idris',outsider='member_nia',key=(org:string,project:string,id:string)=>`organisations/${org}/task-files/${project}/${id}.pdf`;
        const request={purpose:'task_file' as const,taskId:'task_test',name:'Postgres notes.pdf',contentType:'application/pdf' as const,sizeBytes:64};
        await assert.rejects(()=>repo.beginTaskFileUpload('code-black',outsider,request,key,'task-files-postgres'),{code:'NOT_FOUND'});
        const {upload}=await repo.beginTaskFileUpload('code-black',DEMO_USER,request,key,'task-files-postgres');
        assert.equal((await repo.completeTaskFileUpload('code-black',DEMO_USER,upload.id,{sizeBytes:64,contentType:'application/pdf',generation:'1712345678907777',signatureMatches:true},'task-files-postgres')).outcome,'ready');
        const files=(org:string,user:string)=>runtime!.transaction(async tx=>{await setContext(tx,org,user);return (await tx.query<{id:string}>("SELECT id FROM upload_intents WHERE purpose='task_file'")).rows.map(x=>x.id);});
        assert((await files('org_code_black',lead)).includes(upload.id));assert.deepEqual(await files('org_code_black',outsider),[]);assert.deepEqual(await files('org_studio_north',DEMO_USER),[]);
        await assert.rejects(()=>runtime!.transaction(async tx=>{await setContext(tx,'org_code_black',outsider);await tx.query("INSERT INTO upload_intents(organization_id,id,user_id,object_key,content_type,size_bytes,original_name,created_at,status,purpose,task_id) VALUES('org_code_black','pg_forged',$1,'k','application/pdf',10,'a.pdf',now(),'pending','task_file','task_test')",[outsider]);}));
        assert.deepEqual(await repo.taskFileDownload('code-black',lead,'task_test',upload.id),{objectKey:key('org_code_black','project_common',upload.id),generation:'1712345678907777',contentType:'application/pdf',filename:'Postgres notes.pdf'});
        await assert.rejects(()=>repo.taskFileDownload('code-black',outsider,'task_test',upload.id),{code:'NOT_FOUND'});
        await admin.query("UPDATE members SET status='suspended' WHERE organization_id='org_code_black' AND user_id=$1",[lead]);
        try{assert.deepEqual(await files('org_code_black',lead),[]);await assert.rejects(()=>repo.taskFileDownload('code-black',lead,'task_test',upload.id),{code:'NOT_FOUND'});}
        finally{await admin.query("UPDATE members SET status='active' WHERE organization_id='org_code_black' AND user_id=$1",[lead]);}
        const version=await repo.projectWorkVersion('code-black',DEMO_USER,'project_common');
        await assert.rejects(()=>repo.projectWorkVersion('code-black',outsider,'project_common'),{code:'NOT_FOUND'});
        const t=(await repo.snapshot('code-black',lead)).projectTasks.find(x=>x.id==='task_flow')!,edit=(user:string,title:string)=>repo.execute('code-black',user,{type:'task.edit',taskId:t.id,expectedVersion:t.version,title,brief:t.brief,criteria:t.criteria,assigneeId:t.assigneeId},randomUUID(),'task-files-postgres');
        await edit(lead,'Saved first');await assert.rejects(()=>edit(DEMO_ADMIN,'Saved second'),{code:'STALE_TASK'});
        assert.notEqual(await repo.projectWorkVersion('code-black',DEMO_USER,'project_common'),version);
        const {releasedFiles}=await repo.executeCommand('code-black',lead,{type:'task.file.remove',taskId:'task_test',fileId:upload.id},randomUUID(),'task-files-postgres');
        assert.deepEqual(releasedFiles,[key('org_code_black','project_common',upload.id)]);assert.deepEqual(await files('org_code_black',lead),[]);
    });
    await check('a member deletes their own account through the restricted runtime connection, keeping shared work as Former member',async()=>{
        const theo='member_theo',now=new Date().toISOString(),repo=new WorkspaceRepository(runtime!);
        for(const [id,name,email] of [[theo,'Theo Williams','theo@example.test'],[DEMO_ADMIN,'Amina Okafor','amina@example.test']])await admin.query('INSERT INTO auth_user(id,name,email,email_verified,created_at,updated_at) VALUES($1,$2,$3,true,$4,$4)',[id,name,email,now]);
        await admin.query("INSERT INTO auth_session(id,expires_at,token,created_at,updated_at,user_id) VALUES('pg_theo_session',now()+interval '1 day','pg_theo_token',$1,$1,$2)",[now,theo]);
        await repo.execute('code-black',theo,{type:'track.enrol',trackId:'track_product'},randomUUID(),'pg-account');
        const seen=(await repo.snapshot('code-black',theo)).lessons.find(l=>l.id==='lesson_5')!.quiz!;
        await repo.execute('code-black',theo,{type:'quiz.attempt.submit',lessonId:'lesson_5',fingerprint:quizFingerprint(seen),answers:[{questionId:'q5_feedback',optionIds:['a']},{questionId:'q5_essentials',optionIds:['a']},{questionId:'q5_outcome',text:'useful'}]},randomUUID(),'pg-account');
        await repo.execute('code-black',DEMO_ADMIN,{type:'track.instructor.add',trackId:'track_product',userId:theo},randomUUID(),'pg-account');
        await admin.query("UPDATE members SET status='suspended' WHERE organization_id='org_studio_north' AND user_id=$1",[theo]);
        await assert.rejects(()=>repo.deleteAccount(DEMO_ADMIN),{code:'OWNER_CANNOT_DELETE'});
        assert.equal((await admin.query('SELECT count(*)::int AS n FROM auth_user WHERE id=$1',[DEMO_ADMIN])).rows[0].n,1,'a refused owner keeps their account');
        const {summary}=await repo.deleteAccount(theo);
        assert.equal(summary.communities,2);assert.equal(summary.removed.quizAttempts,1);assert.equal(summary.removed.trackInstructors,1);
        assert.deepEqual((await admin.query('SELECT DISTINCT name,status,avatar,bio,role FROM members WHERE user_id=$1',[theo])).rows,[{name:'Former member',status:'left',avatar:'',bio:'',role:'member'}]);
        for(const table of ['quiz_attempts','track_instructors','enrolments','reactions','rsvps','notifications','reputation','auth_session'])assert.equal((await admin.query(`SELECT count(*)::int AS n FROM ${table} WHERE user_id=$1`,[theo])).rows[0].n,0,table);
        assert.equal((await admin.query('SELECT count(*)::int AS n FROM auth_user WHERE id=$1',[theo])).rows[0].n,0);
        assert.equal((await admin.query('SELECT count(*)::int AS n FROM project_members WHERE user_id=$1',[theo])).rows[0].n,2,'team places stay with the work');
        await assert.rejects(()=>repo.snapshot('code-black',theo),{code:'NOT_FOUND'});
    });
    await check('an owner hands a community to one administrator at a time through the restricted runtime connection',async()=>{
        const repo=new WorkspaceRepository(runtime!),owners=async()=>(await admin.query("SELECT user_id FROM members WHERE organization_id='org_studio_north' AND role='owner'")).rows.map(r=>r.user_id);
        await assert.rejects(()=>admin.query("UPDATE members SET role='owner' WHERE organization_id='org_studio_north' AND user_id='member_maya'"),/members_single_owner_idx/);
        for(const id of ['member_maya','member_sofia'])await repo.execute('studio-north',DEMO_ADMIN,{type:'member.role',memberId:id,role:'admin'},randomUUID(),'pg-ownership');
        // Two handovers at once, on separate pooled connections: the community lock lets exactly one through.
        const outcomes=await Promise.all(['member_maya','member_sofia'].map(id=>repo.transferOwnership('studio-north',DEMO_ADMIN,id,'Studio North','pg-ownership').then(()=>'handed',(e:{code?:string})=>e.code??'failed')));
        assert.deepEqual([...outcomes].sort(),['OWNER_REQUIRED','handed']);
        const now=await owners();assert.equal(now.length,1);assert(['member_maya','member_sofia'].includes(String(now[0])));
        assert.equal((await admin.query("SELECT role FROM members WHERE organization_id='org_studio_north' AND user_id=$1",[DEMO_ADMIN])).rows[0].role,'admin');
        assert.equal((await admin.query("SELECT count(*)::int AS n FROM audit WHERE organization_id='org_studio_north' AND action='member.owner.transferred'")).rows[0].n,1);
        await repo.transferOwnership('code-black',DEMO_ADMIN,(await repo.execute('code-black',DEMO_ADMIN,{type:'member.role',memberId:'member_maya',role:'admin'},randomUUID(),'pg-ownership')).objectId!,'Code Black','pg-ownership');
        const {summary}=await repo.deleteAccount(DEMO_ADMIN);
        assert.equal(summary.communities,2,'once they own nothing, the previous owner can delete their account');
    });
    await check('accepting an invitation waits for an account deletion under way, and adds no membership after it',async()=>{
        const person='pg_newcomer',now=new Date().toISOString(),token=randomBytes(32).toString('base64url');
        await admin.query("INSERT INTO auth_user(id,name,email,email_verified,created_at,updated_at) VALUES($1,'Noor Patel','noor@example.test',true,$2,$2)",[person,now]);
        await admin.query("INSERT INTO invitations(id,organization_id,email,token_hash,created_by,expires_at) VALUES($1,'org_studio_north','noor@example.test',$2,$3,now()+interval '7 days')",[randomUUID(),createHash('sha256').update(token).digest('hex'),DEMO_ADMIN]);
        const invitations=new InvitationService(new WorkspaceRepository(runtime!),'http://127.0.0.1:5173',new MailQueue(runtime!,'postgres_check_secret_5a4b3c2d1e0f9a8b7c6d'));
        let accepting:Promise<string>|undefined;
        // The deletion's first step, locking the account, is held open while the acceptance starts on another connection.
        await runtime!.transaction(async tx=>{
            await setContext(tx,'',person);await tx.query("SELECT set_config('app.account_deletion',$1,true)",[person]);
            await tx.query('SELECT id FROM auth_user WHERE id=$1 FOR UPDATE',[person]);
            accepting=invitations.accept(token,person).then(()=>'accepted',(e:{code?:string})=>e.code??'failed');
            assert.equal(await Promise.race([accepting,new Promise(r=>setTimeout(()=>r('waiting'),500))]),'waiting','acceptance waits on the account lock');
            await tx.query('DELETE FROM auth_user WHERE id=$1',[person]);
        });
        assert.equal(await accepting,'INVITE_ACCOUNT_MISMATCH');
        assert.equal((await admin.query('SELECT count(*)::int AS n FROM members WHERE user_id=$1',[person])).rows[0].n,0,'no membership outlives the account');
    });
    await check('an account deletion that starts while an acceptance holds the account waits, then removes the new membership too',async()=>{
        const person='pg_late_joiner',now=new Date().toISOString();
        await admin.query("INSERT INTO auth_user(id,name,email,email_verified,created_at,updated_at) VALUES($1,'Ravi Shah','ravi@example.test',true,$2,$2)",[person,now]);
        await admin.query("INSERT INTO members(organization_id,id,created_at,user_id,name,headline,bio,skills,colour,avatar,role,status) VALUES('org_studio_north',$1,now(),$2,'Ravi Shah','','','[]','violet','','member','active')",[randomUUID(),person]);
        let deleting:Promise<number|string>|undefined;
        // The acceptance's first step, a share lock on the account, is held open while the deletion starts on another connection.
        await admin.transaction(async tx=>{
            await tx.query('SELECT id FROM auth_user WHERE id=$1 FOR SHARE',[person]);
            deleting=new WorkspaceRepository(runtime!).deleteAccount(person).then(r=>r.summary.communities,(e:{code?:string;message?:string})=>e.code??e.message??'failed');
            assert.equal(await Promise.race([deleting,new Promise(r=>setTimeout(()=>r('waiting'),500))]),'waiting','deletion waits on the account lock');
            await tx.query("INSERT INTO members(organization_id,id,created_at,user_id,name,headline,bio,skills,colour,avatar,role,status) VALUES('org_code_black',$1,now(),$2,'Ravi Shah','','','[]','violet','','member','active')",[randomUUID(),person]);
        });
        assert.equal(await deleting,2,'the deletion sees the membership the acceptance committed');
        assert.equal((await admin.query("SELECT count(*)::int AS n FROM members WHERE user_id=$1 AND (status<>'left' OR name<>'Former member')",[person])).rows[0].n,0,'no active membership outlives the account');
        assert.equal((await admin.query('SELECT count(*)::int AS n FROM auth_user WHERE id=$1',[person])).rows[0].n,0);
    });
    await check('overlapping digest runs through the restricted runtime connection queue one email, and only for the member who asked',async()=>{
        const person='pg_digest_reader',past=new Date(Date.now()-8*864e5).toISOString(),now=new Date().toISOString();
        await admin.query("INSERT INTO auth_user(id,name,email,email_verified,created_at,updated_at) VALUES($1,'Lena Park','lena@example.test',true,$2,$2)",[person,now]);
        await admin.query("INSERT INTO members(organization_id,id,created_at,user_id,name,headline,bio,skills,colour,avatar,role,status) VALUES('org_code_black',$1,now(),$2,'Lena Park','','','[]','violet','','member','active')",[randomUUID(),person]);
        await admin.query("INSERT INTO notification_preferences(id,organization_id,created_at,user_id,muted,digest,updated_at) VALUES($1,'org_code_black',$2,$3,'[]','weekly',$2)",[randomUUID(),past,person]);
        await admin.query("INSERT INTO notifications(id,organization_id,created_at,user_id,title,body,href,read_at) VALUES($1,'org_code_black',$2,$3,'Unread for Lena','Body','/home',NULL)",[randomUUID(),new Date(Date.now()-864e5).toISOString(),person]);
        const before=(await admin.query<{n:number}>("SELECT count(*)::int AS n FROM email_outbox")).rows[0].n;
        const digests=new DigestService(runtime!,new MailQueue(runtime!,'LOCAL_CI_DIGEST_ONLY_123456789012345678'),'https://ferven.test');
        const runs=await Promise.all([digests.run(),digests.run()]);
        assert.equal(runs.reduce((n,r)=>n+r.queued,0),1,'one digest however the runs overlap');
        assert.equal((await admin.query<{n:number}>("SELECT count(*)::int AS n FROM email_outbox")).rows[0].n,before+1);
        assert.notEqual((await admin.query<{t:Date|null}>('SELECT last_digest_at AS t FROM notification_preferences WHERE user_id=$1',[person])).rows[0].t,null);
    });
    await mkdir('evidence/alpha04',{recursive:true});await writeFile('evidence/alpha04/postgres-results.json',JSON.stringify({generatedAt:new Date().toISOString(),method:'Disposable local PostgreSQL service, not Neon.',results},null,2));
}finally{await runtime?.close();await admin.close();}
