/** Actual bundled editor, fictional local data. No external media is requested. */
import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { switchPreviewRole, answerConfirmations } from './ui-test-helpers';
const root=resolve(import.meta.dirname,'..'),dir=root+'/evidence/rich-lessons';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1512,height:1000}});const page=await context.newPage();page.setDefaultTimeout(10000);
const results:{name:string;passed:boolean}[]=[],errors:string[]=[],mediaRequests:string[]=[];
page.on('pageerror',e=>errors.push(e.message));await answerConfirmations(page);
await page.route(/(?:youtube|vimeo|images\.example\.com)/,route=>{mediaRequests.push(route.request().url());return route.abort();});
const check=async(name:string,fn:()=>Promise<void>)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
const editor=()=>page.locator('.creator-editor'),body=()=>editor().getByRole('textbox',{name:'Lesson body',exact:true});
const track=async()=>{await page.locator('.sidebar a[href="/paths"]').first().click();await page.locator('a[href="/learn"]').first().click();await page.locator('.track-card[href="/learn/track_product"]').click();};
const studio=async()=>{await track();await page.getByRole('link',{name:'Creator studio',exact:true}).click();await page.locator('.creator-title').filter({hasText:'Choose one real problem'}).click();};
const save=async()=>{await editor().getByRole('button',{name:'Save draft',exact:true}).click();await expect(editor()).toContainText('Saved privately');};
try{
    await page.setContent(await readFile(root+'/.preview/REUNIR-preview.html','utf8'),{waitUntil:'load'});await switchPreviewRole(page,'admin');await studio();
    await check('legacy text opens without creating unsaved edits',async()=>{await expect(body()).toContainText('Name one person');await expect(editor().getByRole('button',{name:'Save draft',exact:true})).toBeDisabled();});
    await check('heading and bold controls format the actual editable document',async()=>{await body().fill('Observe before you build');await editor().getByRole('button',{name:'Heading 2',exact:true}).click();await expect(body().locator('h2')).toHaveText('Observe before you build');await body().press('End');await body().press('Enter');await editor().getByRole('button',{name:'Bold',exact:true}).click();await body().pressSequentially('One useful next step.');await expect(body().locator('strong')).toHaveText('One useful next step.');});
    await check('video insertion rejects arbitrary iframe providers',async()=>{await body().press('End');await body().press('Enter');await editor().getByRole('button',{name:'Add video',exact:true}).click();await editor().getByLabel('Video URL',{exact:true}).fill('https://evil.example.com/embed/123');await editor().getByLabel('Video title',{exact:true}).fill('A workshop');await editor().getByRole('button',{name:'Insert video',exact:true}).click();await expect(editor().getByRole('alert')).toContainText('YouTube or Vimeo');});
    await check('supported video and image insert labelled non-fetching editor blocks',async()=>{await editor().getByLabel('Video URL',{exact:true}).fill('https://youtu.be/dQw4w9WgXcQ?autoplay=1');await editor().getByRole('button',{name:'Insert video',exact:true}).click();await expect(body().locator('[data-lesson-media="video"]')).toContainText('A workshop');await editor().getByRole('button',{name:'Add image',exact:true}).click();await editor().getByLabel('Image URL',{exact:true}).fill('https://images.example.com/photo.jpg');await editor().getByLabel('Image description',{exact:true}).fill('A creative team');await editor().getByRole('button',{name:'Insert image',exact:true}).click();await expect(body().locator('[data-lesson-media="image"]')).toContainText('A creative team');await expect(body().locator('[data-lesson-media="video"]')).toContainText('A workshop');expect(mediaRequests).toEqual([]);});
    await check('private preview renders headings and click-to-load media, not iframes',async()=>{await editor().getByRole('button',{name:'Preview',exact:true}).click();await expect(editor().locator('.rich-lesson h2')).toHaveText('Observe before you build');await expect(editor().getByRole('button',{name:'Load video',exact:true})).toBeVisible();await expect(editor().locator('iframe,img')).toHaveCount(0);expect(mediaRequests).toEqual([]);await editor().getByRole('button',{name:'Write',exact:true}).click();});
    await check('saving is private and survives reopening',async()=>{await save();await page.getByRole('link',{name:'Back to the learning track',exact:false}).click();await expect(page.locator('.lesson-content')).not.toContainText('Observe before you build');await page.getByRole('link',{name:'Creator studio',exact:true}).click();await page.locator('.creator-title').filter({hasText:'Choose one real problem'}).click();await expect(body().locator('h2')).toHaveText('Observe before you build');});
    await check('explicit publication displays rich content without resetting completion',async()=>{await editor().getByRole('button',{name:'Publish saved lesson',exact:true}).click();await switchPreviewRole(page,'member');await track();await page.locator('.lesson-step[href="/learn/track_product/lesson_4"]').click();await expect(page.locator('.lesson-content .rich-lesson h2')).toHaveText('Observe before you build');await expect(page.getByRole('button',{name:'Lesson completed',exact:true})).toBeDisabled();await expect(page.locator('.lesson-content iframe,.lesson-content img')).toHaveCount(0);expect(mediaRequests).toEqual([]);});
    await switchPreviewRole(page,'admin');await studio();
    await check('rich authoring has no desktop accessibility violations',async()=>{const scan=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(scan.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);await page.screenshot({path:dir+'/editor-desktop.png',fullPage:true});});
    await check('formatting controls remain usable at 360px without overflow',async()=>{await page.setViewportSize({width:360,height:800});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(editor().getByRole('button',{name:'Add video',exact:true})).toBeVisible();await page.screenshot({path:dir+'/editor-mobile.png',fullPage:true});});
    await check('restoring a plain revision only changes the draft until republished',async()=>{await page.setViewportSize({width:1512,height:1000});await editor().locator('summary').click();await editor().locator('.creator-revision').filter({hasText:'Captured existing lesson'}).getByRole('button',{name:'Restore as draft',exact:true}).click();await expect(body()).toContainText('Name one person');await expect(body().locator('[data-lesson-media]')).toHaveCount(0);await page.getByRole('link',{name:'Back to the learning track',exact:false}).click();await page.locator('.lesson-step[href="/learn/track_product/lesson_4"]').click();await expect(page.locator('.lesson-content .rich-lesson h2')).toHaveText('Observe before you build');});
    await check('rich editor journey has no unhandled exceptions',async()=>expect(errors).toEqual([]));
    await writeFile(dir+'/browser-results.json',JSON.stringify({results,errors,mediaRequests},null,2));console.log(results.length+' rich lesson browser checks passed');
}catch(error){await page.screenshot({path:dir+'/failure.png',fullPage:true}).catch(()=>{});await writeFile(dir+'/browser-results.json',JSON.stringify({results,errors,failure:String(error)},null,2));throw error;}finally{await browser.close();}
