/** Approved v4 rendered by the real React app. Local fictional state, not hosted acceptance. */
import { chromium, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { switchPreviewRole } from './ui-test-helpers';
const root=resolve(import.meta.dirname,'..'),dir=root+'/evidence/alpha07';
await mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true});
const context=await browser.newContext({viewport:{width:1466,height:1080}});
const page=await context.newPage();page.setDefaultTimeout(8000);
const errors:string[]=[],results:{name:string;passed:boolean}[]=[];
page.on('pageerror',e=>errors.push(e.message));
const check=async(name:string,fn:()=>Promise<void>)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
const overflow=async()=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
const shot=async(name:string)=>{await page.screenshot({path:dir+'/'+name+'.png',fullPage:true,animations:'disabled'});};
async function a11y(name:string){const scan=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();await writeFile(dir+'/a11y-'+name+'.json',JSON.stringify({violations:scan.violations,incomplete:scan.incomplete},null,2));expect(scan.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))).toEqual([]);}
async function account(item:string){await page.getByRole('button',{name:'Account menu',exact:true}).click();await page.getByRole('menuitem',{name:item,exact:true}).click();}
try{
 await page.setContent(await readFile(root+'/.preview/REUNIR-preview.html','utf8'),{waitUntil:'load'});
 await check('v4 is rendered by the existing React application, not an embedded HTML mock',async()=>{await expect(page.locator('.v4-home h1')).toContainText('Build together.');await expect(page.locator('iframe')).toHaveCount(0);await expect(page.locator('.app-footer')).toContainText('FICTIONAL DEMO');});
 await check('far-left rail retains both independent demo communities',async()=>{await expect(page.locator('.workspace-rail')).toBeVisible();await expect(page.getByRole('button',{name:'Open Code Black',exact:true})).toHaveAttribute('aria-current','true');await expect(page.getByRole('button',{name:'Open Studio North demo community'})).toBeVisible();});
 await check('second sidebar retains product navigation without search or a community switcher',async()=>{for(const p of ['/','/paths','/projects','/events','/members','/discussions','/messages','/knowledge','/collections','/missions','/outputs','/saved'])await expect(page.locator('.sidebar a[href="'+p+'"]').first()).toBeVisible();await expect(page.locator('.sidebar input,.sidebar-search,.community-name,.community-switch')).toHaveCount(0);});
 await check('one account trigger replaces duplicated bottom profile controls',async()=>{await expect(page.getByRole('button',{name:'Account menu',exact:true})).toHaveCount(1);await expect(page.locator('.sidebar [data-slot="avatar"],.workspace-rail [data-slot="avatar"],.account-block,.profile-mini')).toHaveCount(0);});
 await check('real portrait images load for supplied fictional people without colour-tile initials',async()=>{await expect(page.locator('.top-avatar img')).toBeVisible();expect(await page.locator('.top-avatar img').evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true);expect(await page.locator('.v4-hero-people img').count()).toBeGreaterThan(0);expect(await page.locator('.top-avatar img').evaluate(el=>getComputedStyle(el).filter)).toBe('none');});
 await check('navigation uses library SVG icons without side-highlight stripes',async()=>{expect(await page.locator('.primary-nav a svg').count()).toBe(9);expect(await page.locator('.workspace-icon.current').evaluate(el=>getComputedStyle(el).boxShadow)).toBe('none');expect(await page.locator('.workspace-icon.current').evaluate(el=>getComputedStyle(el,'::before').display)).toBe('none');});
 await check('shadcn buttons and photo avatars are mounted as actual components',async()=>{await expect(page.locator('.v4-hero-actions [data-slot="button"]')).toHaveCount(2);await expect(page.locator('.v4-hero-actions [data-variant="default"]')).toHaveAttribute('href','/paths/path_product');expect(await page.locator('[data-slot="avatar-image"]').count()).toBeGreaterThan(4);});
 await check('home progress is derived from the member’s evidenced milestones',async()=>{await expect(page.getByRole('progressbar',{name:'Milestones evidenced'})).toHaveAttribute('aria-valuenow','25');await expect(page.locator('.v4-progress')).toContainText('1 of 4 milestones evidenced');await page.locator('.v4-hero-actions a').first().click();await expect(page.locator('.path-progress-summary')).toContainText('1 of 4');await page.locator('.sidebar a[href="/"]').first().click();});
 await check('global search stays in the header and navigates to authorised results',async()=>{await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('textbox',{name:'Search your community'}).fill('Common Ground');await page.locator('.search-results button').filter({hasText:'Common Ground'}).click();await expect(page.locator('h1')).toHaveText('Common Ground');await page.locator('.sidebar a[href="/"]').first().click();});
 await check('Create opens existing member creation actions',async()=>{await page.getByRole('button',{name:'Create',exact:true}).click();const d=page.getByRole('dialog');await expect(d).toContainText('Start a conversation');await expect(d).toContainText('Start a project');await expect(d).not.toContainText('Create a learning track');await page.keyboard.press('Escape');});
 await check('account menu is keyboard operable and Escape restores focus',async()=>{const trigger=page.getByRole('button',{name:'Account menu',exact:true});await trigger.focus();await page.keyboard.press('Enter');await expect(page.getByRole('menu')).toBeVisible();await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>document.activeElement?.getAttribute('role'))).toBe('menuitem');await a11y('account');await shot('account-menu');await page.keyboard.press('Escape');await expect(trigger).toBeFocused();});
 await check('profile and authorised administration remain reachable through the new menu',async()=>{await account('Your profile');await expect(page.locator('.profile-purpose')).toBeVisible();await switchPreviewRole(page,'admin');await expect(page.locator('.sidebar a[href="/operations"]')).toBeVisible();await expect(page.locator('.sidebar a[href="/access"]')).toBeVisible();await switchPreviewRole(page,'member');await expect(page.locator('.sidebar a[href="/operations"]')).toHaveCount(0);});
 await check('desktop Home has no horizontal overflow and passes automated accessibility',async()=>{await overflow();await a11y('home-desktop');await shot('desktop');});
 await check('all planned narrow viewports retain readable layout without horizontal scrolling',async()=>{for(const width of [1200,1000,999,768,640,390,360]){await page.setViewportSize({width,height:900});await overflow();}await shot('mobile');});
 await check('mobile navigation keeps every route and traps focus inside the drawer',async()=>{await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open navigation',exact:true}).click();const d=page.getByRole('dialog',{name:'Main navigation'});await expect(d).toBeVisible();const first=page.getByRole('button',{name:'Close navigation panel',exact:true});await expect(first).toBeFocused();await page.keyboard.press('Shift+Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('.sidebar.open'))).toBe(true);await page.keyboard.press('Tab');await expect(first).toBeFocused();await expect(d.locator('[data-slot="avatar"]')).toHaveCount(0);await a11y('mobile-navigation');await shot('mobile-navigation');});
 await check('Escape closes the mobile drawer and returns focus to its trigger',async()=>{await page.keyboard.press('Escape');await expect(page.locator('.sidebar')).not.toHaveClass(/open/);await expect(page.getByRole('button',{name:'Open navigation',exact:true})).toBeFocused();});
 await check('community switching remains accessible from the single account menu on mobile',async()=>{await account('Your communities');await page.getByRole('dialog').getByRole('button',{name:/Studio North/}).click();await expect(page.locator('.breadcrumb')).toContainText('Studio North');await account('Your communities');await page.getByRole('dialog').getByRole('button',{name:/Code Black/}).click();await expect(page.locator('.breadcrumb')).toContainText('Code Black');});
 await check('mobile Home and top account controls pass automated accessibility',async()=>{await overflow();await a11y('home-mobile');await shot('mobile');});
 await check('Home does not invent upcoming events when fixture dates have passed',async()=>{await page.clock.setFixedTime(new Date('2027-01-01T12:00:00Z'));await page.locator('.mobile-bottom a[href="/projects"]').click();await page.locator('.mobile-bottom a[href="/"]').click();await expect(page.locator('.v4-events')).toContainText('No upcoming events');await expect(page.locator('.v4-event-row')).toHaveCount(0);});
 await check('complete shell and home interactions produce no uncaught JavaScript errors',async()=>{expect(errors).toEqual([]);});
 await writeFile(dir+'/browser-results.json',JSON.stringify({method:'Bundled actual React, Chromium, fictional local state. Not hosted API acceptance. Final empty-events assertion fixes Date to 2027.',results,errors},null,2));console.log(results.length+' v4 integration browser checks passed');
}catch(e){await page.screenshot({path:dir+'/failure.png',fullPage:true}).catch(()=>{});await writeFile(dir+'/browser-results.json',JSON.stringify({results,errors,failure:String(e)},null,2));throw e;}finally{await browser.close();}
